<!--
function f(fn,ft,fd){
 this.fn=fn;
 this.ft=ft;
 this.fd=fd;
}
var Fs=new Array (
new f("//videos.videomusica.es/Aaron.Neville.html","Videomúsica sección videos, Aaron Neville","Videomúsica, información y videos. Aaron Neville"),new f("//videos.videomusica.es/Abba.html","Videomúsica sección videos, Abba","Videomúsica, información y videos. Abba"),new f("//videos.videomusica.es/Al.Green.html","Videomúsica sección videos, Al Green","Videomúsica, información y videos. Al Green"),new f("//videos.videomusica.es/Al.Jarreau.html","Videomúsica sección videos, Al Jarreau","Videomúsica, información y videos. Al Jarreau"),new f("//videos.videomusica.es/Amaral.html","Videomúsica sección videos, Amaral","Videomúsica, información y videos. Amaral"),new f("//videos.videomusica.es/Ana.Belen.html","Videomúsica sección videos, Ana Belén","Videomúsica, información y videos. Ana Belén"),new f("//videos.videomusica.es/Antonio.Vega.html","Videomúsica sección videos, Antonio Vega","Videomúsica, información y videos. Antonio Vega"),new f("//videos.videomusica.es/Baron.Rojo.html","Videomúsica sección videos, Barón Rojo","Videomúsica, información y videos. Barón Rojo"),new f("//videos.videomusica.es/Barry.White.html","Videomúsica sección videos, Barry White","Videomúsica, información y videos. Barry White"),new f("//videos.videomusica.es/Bee.Gees.html","Videomúsica sección videos, Bee Gees","Videomúsica, información y videos. Bee Gees"),
new f("//videos.videomusica.es/Billy.Joel.html","Videomúsica sección videos, Billy Joel","Videomúsica, información y videos. Billy Joel"),new f("//videos.videomusica.es/Bobby.Caldwell.html","Videomúsica sección videos, Bobby Caldwell","Videomúsica, información y videos. Bobby Caldwell"),new f("//videos.videomusica.es/Boney.M.html","Videomúsica sección videos, Boney M","Videomúsica, información y videos. Boney M"),new f("//videos.videomusica.es/Camilo.Sesto.html","Videomúsica sección videos, Camilo Sesto","Videomúsica, información y videos. Camilo Sesto"),new f("//videos.videomusica.es/Candi.Staton.html","Videomúsica sección videos, Candi Staton","Videomúsica, información y videos. Candi Staton"),new f("//videos.videomusica.es/Carole.King.html","Videomúsica sección videos, Carole King","Videomúsica, información y videos. Carole King"),new f("//videos.videomusica.es/Charles.Eddie.html","Videomúsica sección videos, Charles & Eddie","Videomúsica, información y videos. Charles & Eddie"),new f("//videos.videomusica.es/David.Bowie.html","Videomúsica, David Bowie","Videomúsica, información y videos. David Bowie"),new f("//videos.videomusica.es/Donald.Fagen.html","Videomúsica sección videos, Donald Fagen","Videomúsica, información y videos. Donald Fagen"),new f("//videos.videomusica.es/Earth.Wind.Fire.html","Videomúsica sección videos, Earth Wind & Fire","Videomúsica, información y videos. Earth Wind & Fire"),
new f("//videos.videomusica.es/Elton.John.html","Videomúsica sección videos, Elton John","Videomúsica, información y videos. Elton John"),new f("//videos.videomusica.es/Fito.Fitipaldis.html","Videomúsica sección videos, Fito & Fitipaldis","Videomúsica, información y videos. Fito & Fitipaldis"),new f("//videos.videomusica.es/Fleetwood.Mac.html","Videomúsica sección videos, Fleetwood Mac","Videomúsica, información y videos. Fleetwood Mac"),new f("//videos.videomusica.es/George.Benson.html","Videomúsica sección videos, George Benson","Videomúsica, información y videos. George Benson"),new f("//videos.videomusica.es/George.Michael.html","Videomúsica sección videos, George Michael","Videomúsica, información y videos. George Michael"),new f("//videos.videomusica.es/Incognito.html","Videomúsica sección videos, Incognito","Videomúsica, información y videos. Incognito"),new f("//videos.videomusica.es/Jamiroquai.html","Videomúsica sección videos, Jamiroquai","Videomúsica, información y videos. Jamiroquai"),new f("//videos.videomusica.es/Jose.Feliciano.html","Videomúsica sección videos, José Feliciano","Videomúsica, información y videos. José Feliciano"),new f("//videos.videomusica.es/Joss.Stone.html","Videomúsica sección videos, Joss Stone","Videomúsica, información y videos. Joss Stone"),new f("//videos.videomusica.es/Juan.Luis.Guerra.html","Videomúsica sección videos, Juan Luis Guerra","Videomúsica, información y videos. Juan Luis Guerra"),
new f("//videos.videomusica.es/Julio.Iglesias.html","Videomúsica sección videos, Julio Iglesias","Videomúsica, información y videos. Julio Iglesias"),new f("//videos.videomusica.es/Katie.Melua.html","Videomúsica sección videos, Katie Melua","Videomúsica, información y videos. Katie Melua"),new f("//videos.videomusica.es/Ketama.html","Videomúsica sección videos, Ketama","Videomúsica, información y videos. Ketama"),new f("//videos.videomusica.es/La.Oreja.De.Van.Gogh.html","Videomúsica sección videos, La Oreja de Van Gogh","Videomúsica, información y videos. La Oreja de Van Gogh"),new f("//videos.videomusica.es/Laura.Izibor.html","Videomúsica sección videos, Laura Izibor","Videomúsica, información y videos. Laura Izibor"),new f("//videos.videomusica.es/Lionel.Richie.html","Videomúsica sección videos, Lionel Richie","Videomúsica, información y videos. Lionel Richie"),new f("//videos.videomusica.es/Los.Modulos.html","Videomúsica sección videos, Los Módulos","Videomúsica, información y videos. Los Módulos"),new f("//videos.videomusica.es/Los.Panchos.html","Videomúsica sección videos, Los Panchos","Videomúsica, información y videos. Los Panchos"),new f("//videos.videomusica.es/Lou.Rawls.html","Videomúsica sección videos, Lou Rawls","Videomúsica, información y videos. Lou Rawls"),new f("//videos.videomusica.es/Luis.Eduardo.Aute.html","Videomúsica sección videos, Luis Eduardo Aute","Videomúsica, información y videos. Luis Eduardo Aute"),
new f("//videos.videomusica.es/Luis.Miguel.html","Videomúsica sección videos, Luis Miguel","Videomúsica, información y videos. Luis Miguel"),new f("//videos.videomusica.es/M-Clan.html","Videomúsica sección videos, M-Clan","Videomúsica, información y videos. M-Clan"),new f("//videos.videomusica.es/Manolo.Garcia.html","Videomúsica sección videos, Manolo García","Videomúsica, información y videos. Manolo García"),new f("//videos.videomusica.es/Marc.Anthony.html","Videomúsica sección videos, Marc Anthony","Videomúsica, información y videos. Marc Anthony"),new f("//videos.videomusica.es/Mariah.Carey.html","Videomúsica sección videos, Mariah Carey","Videomúsica, información y videos. Mariah Carey"),new f("//videos.videomusica.es/Marvin.Gaye.html","Videomúsica sección videos, Marvin Gaye","Videomúsica, información y videos. Marvin Gaye"),new f("//videos.videomusica.es/Mary.J.Blige.html","Videomúsica sección videos, Mary J. Blige","Videomúsica, información y videos. Mary J. Blige"),new f("//videos.videomusica.es/Mecano.html","Videomúsica sección videos, Mecano","Videomúsica, información y videos. Mecano"),new f("//videos.videomusica.es/Mocedades.html","Videomúsica sección videos, Mocedades","Videomúsica, información y videos. Mocedades"),new f("//videos.videomusica.es/Monica.Naranjo.html","Videomúsica sección videos, Mónica Naranjo","Videomúsica, información y videos. Mónica Naranjo"),
new f("//videos.videomusica.es/Nino.Bravo.html","Videomúsica sección videos, Aaron Neville","Videomúsica, información y videos. Aaron Neville"),new f("//videos.videomusica.es/Oleta.Adams.html","Videomúsica sección videos, Oleta Adams","Videomúsica, información y videos. Oleta Adams"),new f("//videos.videomusica.es/Otis.Redding.html","Videomúsica sección videos, Otis Redding","Videomúsica, información y videos. Otis Redding"),new f("//videos.videomusica.es/Paul.Carrack.html","Videomúsica sección videos, Paul Carrack","Videomúsica, información y videos. Paul Carrack"),new f("//videos.videomusica.es/Pink.Floyd.html","Videomúsica sección videos, Pink Floyd","Videomúsica, información y videos. Pink Floyd"),new f("//videos.videomusica.es/Prince.html","Videomúsica sección videos, Prince","Videomúsica, información y videos. Prince-The Artist"),new f("//videos.videomusica.es/Queen.html","Videomúsica sección videos, Queen","Videomúsica, información y videos. Queen"),new f("//videos.videomusica.es/Radio.Futura.html","Videomúsica sección videos, Radio Futura","Videomúsica, información y videos. Radio Futura"),new f("//videos.videomusica.es/Raphael.html","Videomúsica sección videos, Raphael","Videomúsica, información y videos. Raphael"),new f("//videos.videomusica.es/Rem.html","Videomúsica sección videos, R.E.M.","Videomúsica, información y videos. R.E.M."),
new f("//videos.videomusica.es/Rico.html","Videomúsica sección videos, Rico","Videomúsica, información y videos. Rico"),new f("//videos.videomusica.es/Roberto.Carlos.html","Videomúsica sección videos, Roberto Carlos","Videomúsica, información y videos. Roberto Carlos"),new f("//videos.videomusica.es/Roxy.Music.html","Videomúsica sección videos, Roxy Music","Videomúsica, información y videos. Roxy Music"),new f("//videos.videomusica.es/Roy.Orbison.html","Videomúsica sección videos, Roy Orbison","Videomúsica, información y videos. Roy Orbison"),new f("//videos.videomusica.es/Sade.html","Videomúsica sección videos, Sade","Videomúsica, información y videos. Sade"),new f("//videos.videomusica.es/Shakira.html","Videomúsica sección videos, Shakira","Videomúsica, información y videos. Shakira"),new f("//videos.videomusica.es/Simply.Red.html","Videomúsica sección videos, Simply Red","Videomúsica, información y videos. Simply Red"),new f("//videos.videomusica.es/Spandau.Ballet.html","Videomúsica sección videos, Spandau Ballet","Videomúsica, información y videos. Spandau Ballet"),new f("//videos.videomusica.es/Stevie.Wonder.html","Videomúsica sección videos, Stevie Wonder","Videomúsica, información y videos. Stevie Wonder"),new f("//videos.videomusica.es/Sting.html","Videomúsica sección videos, Sting","Videomúsica, información y videos. Sting"),
new f("//videos.videomusica.es/Supertramp.html","Videomúsica sección videos, Supertramp","Videomúsica, información y videos. Supertramp"),new f("//videos.videomusica.es/Tequila.html","Videomúsica sección videos, Tequila","Videomúsica, información y videos. Tequila"),new f("//videos.videomusica.es/Terence.Trent.html","Videomúsica sección videos, Terence Trent D'Arby","Videomúsica, información y videos. Sananda Maitreya-Terence Trent D'Arby"),new f("//videos.videomusica.es/The.Carpenters.html","Videomúsica sección videos, The Carpenters","Videomúsica, información y videos. The Carpenters"),new f("//videos.videomusica.es/The.Doobie.Brothers.html","Videomúsica sección videos, The Doobie Brothers","Videomúsica, información y videos. The Doobie Brothers"),new f("//videos.videomusica.es/The.Jacksons.html","Videomúsica sección videos, The Jacksons","Videomúsica, información y videos. The Jacksons"),new f("//videos.videomusica.es/The.Manhattan.Transfer.html","Videomúsica sección videos, The Manhattan Transfer","Videomúsica, información y videos. The Manhattan Transfer"),new f("//videos.videomusica.es/Tino.Casal.html","Videomúsica sección videos, Tino Casal","Videomúsica, información y videos. Tino Casal"),new f("//videos.videomusica.es/Triana.html","Videomúsica sección videos, Triana","Videomúsica, información y videos. Triana"),new f("//videos.videomusica.es/U2.html","Videomúsica sección videos, U2","Videomúsica, información y videos. U2"),
new f("//videos.videomusica.es/Umberto.Tozzi.html","Videomúsica, Umberto Tozzi","Videomúsica, información y videos. Umberto Tozzi"),new f("//videos.videomusica.es/Van.Morrison.html","Videomúsica sección videos, Van Morrison","Videomúsica, información y videos. Van Morrison"),new f("//videos.videomusica.es/Victor.Manuel.html","Videomúsica sección videos, Victor Manuel","Videomúsica, información y videos. Victor Manuel"),new f("//videos.videomusica.es/Zucchero.html","Videomúsica sección videos, Zucchero","Videomúsica, información y videos. Zucchero"));
var L=1, D=1, M=1, Ws=new Array (
"03itdgP","05lssyqaenoL","07dtavu9rjwM","0iaamtprcvy 2","0kcet4appqY","0omja1ivpx0[","0q0ubkwcueoG","0qtrcbaqtymI","0u30mubqcaw j","10 n^4",
"100K;","10ctifjeojq j","12 o)&","127555569 vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","14 rKAu","15E","150`","158fwcg27zeW","16 o]?","175 0",
"190 r","1927#","1941#","1943]","1951 h","1965W","1967W","1968A","1969S","1970 m[",
"1971 2","1972 o","1973US-","1975Y","1976I","1977F","1978 m","1979 sfY","1980 s(","1981 j>",
"1982>5","1984J&","1985 o","1987;9","1990O","1991^","1992=","1993 t","1994T","1995 d",
"1996D","1998R98'","1999 t","1by k","1coyvkedf00 i","1jl8a20hY","1oedfjxzg5g s","1qrn8c24a b","1xmwiwqju8eQ","20:",
"200,","2002'","2003 tB,","2006I","2007D","2009E)","2010 d","2011^","2012,","2014 oS",
"2016ZJ;4","2017&","2018 vutsrqponmlkjihgfecba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#d","2019T90","2020 vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#J","21Z","22 r","24 3","25R;","26YW",
"2600A","275iksf2fqm 8","28D","2ao901rx t","2ezwaC","2hhzmrmahxu?","2kvivewS","2nf9dwlhvoc t","2q9mtjokc4a o","2tj8v2bmftyX",
"2y2g6dciys8 0","30.","300]Y","35=$","365 3","3aymegoesae&","3qad8385pxa*","3v62a2j k","3v726Q","3x1&",
"3xsq6umd4+","40SH@","46rifqdimea s","46vgynndfziV","46y8E","49gy4oslg40 f","4cagg2qmaay 0","4dwcpqjcw3y?","4e?","4e4B",
"4jkis37a2je=","4k9f>","4n8jjod1h04D","4qszlr6pn_","4tyv2phg89a c","50 tg]7","5000A","52 0","57ykv1d0qeeP","5mfeja7ydcqA",
"5qn2sjsqaje)","5roiw^","5ww/","5yc r","60 n]PJGA:4","6cpaoyri8d4 e","6cs3pvmmv0e;","6dedzscgbsq r","6f4bwqffZ","6g8tmiqxnec 4",
"6inwzoooxru l","6kgvcwcb6ik k","6lfxgbb4ugu t","6pprs1mc4sc(","6yok4d53s5uJ","6ywytbX","6yychgx1fmw-","6yziz1flaws;","6z 2","70 uqljYSPF=:21/,s96+%",
"7bdwW","7bmahc'","7bwwo7ctg10F","7cqheq4 j","7eyihajlt0g.","7kae99g`","7mro=","7o a","7olcdlxgc0u 3","7oqnqy9bfj8T",
"7suvaslqiamU","7vstpwvmqgi'","80 rnkjihec^\\ZXVSRMKFC,+s*","89am8kcD","8cufkd=","8etpsn3qdeiS","8gewtiL","8nxvha7k p","8pkju1u8zk0 v","8qz8fqmtsjy 8",
"8qzi s","8xnapx6mkluQ","90 jc_^ZXRQ-M","92.","9aykowwrf i","9b4f 9","9c5ypiq3lqi/","9cinkkn4$","9klbkgcvz i","9mfcbhk02s 3",
"9vjj6j7gxpy g","9xdnsZ","9yktvB","álbum vsrmk\\POJE92)o^Y,3","álbumes qi[RPDB?","álgidoX","ángelesP","ánimoX","â¡qué i","árabe d",
"árabesM","áspera?%","â¡tan c","â¡utópicoZ","â¿Z","â¿o,","ã“peraT","â€œwhatâ€™sP","â© vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","él qk]PA954",
"época sWPF1&%","éste r","éxito ronmljhb^YTSRNMLDA>;320/+*(u9sd","éxitos jd^]TPJI?76/-&$n","â® vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","ã‰l vJ>","Ésta r","Éxitos e","ãlvaroD","ãngeles+",
"a152e46obm0:","ópera 0","órganoG","a8gj9vvuh 9","a8rwz6zbjse d","añadieron f","añadir o","año sojf`^[TSJB,('dD>9","años utpjhged\\WUQPNMLKIHCB=:974210.+$srka_TSE?63/%]n","aún k",
"aaron#","abandonóJD40","abarcar o","abba$","abbey p","abc n","abeja@","abierta c","abiertoM","abiertosM",
"aboutIB","abríaP","abrazarte u","abre q","abrióM8/","abriendoC","abrilZJ","absolutoP","abuelo u","acabó q)",
"acabando p","acabar h","acabaron l","acabo 8","acústicos\\B","acaparado'","acaricia`+","accidentalZ","accidente qpUAW","according k",
"aceite t","aceptar c","acercándose 3","aceroB","acertada t","acid<=","ackymdc4 r","acompañadas 2-","acompañadoZ@;","acompañamiento c",
"acompañando e","acompañar*","acontecíaP","acordesS","acqqvt7itp8`","acreedor t","actúa c","actitud+","activa k","activarE",
"activo g[UJ'","actriz dQ(","actuaciones 6*p","actual g,","actuales 3","actualidad d*","actualmente j","actuandoA","actuar oC","acudir$",
"acuerdo:","acumular=","acurrucarse 6","adam r","adamsV","adaptándolo 3","adaptablesD","adaptaciónR(","adaptacionesR","adaptarse 4",
"adecuado;","adelantado p","adelantarse 4","adelanteT","adelanto n","además tdS","aderezado'","adiós>","adiccionesP","adictivas qm",
"adjetivos g","admiraciónUP","admiradores rC","adolescencia+","adolescenteB","adoptó^","adoradores$","adoroH","adquieran r","adquirióI",
"adquiriendoE","adu c","afamadoI","affairQ","affirmation:","afgt7trnr2k q","afloran e","africa d","africana#","after$6",
"again 1","agapimú(","aglutinarP6,$","agnetha$","agradable/","agradables c","agradecer t","agrandar]","agresiva;","aguasN",
"aguirre'","agustitoC","ahíA$","ahoraN,","ainP","aireR","airearon_","aires,","ajopt7zjar0B","akpebr4gseu&",
"al tsqoc_[YPOMLGFEA@?;83-,)$rkieVRDC>=92%maSNJ6&uX*","albaJ","alberti(","alcalá(","alcance&","alcanzaT","alcanzóP9","alcanzable e","alcanzado rO","alcanzanO",
"alcanzando hTQA?","alcanzar 0+","alcanzaron sonl,R","alcoholQ","alegatoJ","alegra d","alejandro dN","alejo jL","aleluyaJ","alemánA/",
"alemaniaR","algúnQ","algoX#0k","alguien 4","alguna`YS3%","algunas q?*$","algunos tTQPA540","aliño;","alive,","all vutsrqponmlkjihgfedca`_^]\\[ZYXWVUTSRQNMLKJIHGEDCB@?>=<;9876543210/-,+*)('%#PO:$bFA.&",
"allí k+","allá u]Nd","alma vtmeXWSJIH><2(%c#","almasWT","alo7u0sW","alone h%","alrededor c","alright nm","altaU","altasM0)",
"alternativo^","alto onmfbRO;5","always t<","am 1","amaA","américa]U","amados h","amaiaD","amamamos i","amante 0",
"amaral'","amarillasU","amarillo d","amayaS","amazing;","ambiciónP","ambiciosaZ","ambientalP","ambienteC","ambigüedad%",
"ambigua r","ambiguo 4","america i","americanA","americana mA#","americanasE","americans 4","amigo 5","amigos`","amo s",
"amor`SJG@>3+%qT(uK0","amour o","amplio m?","ana uR(","anatomíaE","and trnlkeb^ZY9-*%j","andadura qRD;","andaluz qM","andaluza q","andrés j",
"andrew pc;","angdgp9psb8 u","angel a","angels k","anglo c","anglosajón sNA>","anillo m","animadaI","anitaQ","aniversario$",
"ankirsycetwB","annabel\\","anorexia l","another[YI","antaño 1","ante rpeWP2+(J","anteriormente 6","antes qf^PJ?8","anthonyN","antiguoY",
"antojaba p$","antonio_C)","anuncian$","anunciar;","aohjwgA","última r","últimasO","último 3)","últimos dJ","únicaUTPO#",
"único gd]HB740%","únicos 6","apacibles l","apadrinando+","aparecieron n","aparentementeT","aparición nIE:/","aparienciaZE","aparte&","apbfcvdkmxmI",
"apellido n","apenas nP","apetitosos j","apodadoX","apoderaZX","apodo+","apogeo fC,","apostandoL","apoyado<","apoyarP",
"aprendíH","aprenderM","aprendiH","aptasZ","apuestaD","aquí oNJ","aquel sokSQ53]W","aquella sW","aquellos 3","aquiJ",
"aquiles d","ar8d2yqgq1u f","arafqe94nH","arby 3k","arco m","ardióM","ardiente e","are[F?+g","areethaE","arena&",
"aretha cQ21","argentino j","argumentalP","arguments vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","arie#","ariel j","armaQ","armadura)","armario$","armas n",
"armonía mSO","armoníasC$","armonizadaB","armsW","aromas p","around:","arrancaron\\","arrastrándote 1","arrebatándonos)","arrebatóI",
"arrebatadorL","arrebatadora e","arrebato r","arreglista+","arreglos lS","arriba u","artística p","artísticamente h]","artísticas uM","artístico\\n",
"arte oJ","artes t","artistZ","artista neROA;%kdT0","artistas vutsrqponmlkjihfedcba`_^]\\[ZYWVUTSRONMLKJIHGFDCB@>=;:98765421.-+*)('&%$#XQE?<30/,gAP","artsB","as^Q","así jTMH=<;+tn0","ascapA","ascendenciaJ",
"ascendióA","asesinado f","asi va","ÚltimoM","asomaB","aspecto)","aspirando o","aspirarR","asso6cjpexs b","asturiano u",
"asumiendoP","at.&","aterciopeladaWI+","atlanticE","atmósferaB","atrás qPI,","atractiva c","atractivo c<","atrapado#","atrapan m",
"atrapar c","atraparte eX","atraviesaB","atraviesanX","atrayente c","atrevido v","atronadora%","au8u n","auao50nwnvgW","audiencia`",
"audiencias o","augusto h","aumentar:","aunT","aunan o","aunque e^]XRJB*$","aupóR","auparon)","auraX","aureola c",
"auseron\\","auspicio n","auténticaG&","auténtico@","auténticos j","auteJ","autenticidadN","autodidactaM","automedicarse p","autorF",
"autora d2","autores uA","avalon a","avatares$","avecR","aventura_","avionetaW","awH","awardA","awards`TA",
"away#","axz9cpnwns0 4","ayer)","ayudaba n","ayyyP","azaharaMG","aznavourA","azulM`","b3gbisdtjna d","b6zqd0s'",
"bálsamo t","bésame_H","babaji i","babe+","baby o1","babylon/","bachata@","bache n","back on","baduE",
"bagajeK","bahiaW","baila v","bailar@","bailarina d","baile nh","bailes/","bailey 6","bajón;","bajista hf_[",
"bajo rqnk\\[T,+*p","bakerQ/","balada vN","baladas b;961","balance(","balanceándose m","balazosP","ballet f","baluarte'","bandK",
"banda nf^\\[*$r=,mi","bandas^E963","barón*","barbra,","baron*","barranquilla d","barreras d","barrettY","barricades f","barrioQ",
"barroM","barroco p","barry p,+","basada*","bastantes*","batalla 4","batería rqf[P6*","baterista[","battB","bayW",
"bayf79ylucqA","bayou b","bazasL","bbcX","be[OE?,nlQ73","beach b","beatles bW$","beautiful b5","bebían 3","beber:",
"bebiendoC","becker 5","bee,","been 2W","beforeA","begun l","being%","belén u(","belfast t","believes m",
"bella bB(","bellas ulSL)","bellezaMJ)","bellos ml(","belongI","bendecirnos+","bendición@","bendita@","benegasD","bengalí p",
"benidorm]A","benny$","benson:","beretZ","bernie 7","berryP","besarte j","beseN","besoU","besosK",
"best 1","bfhsf6fkgb4Z","bfqonlm0ggu 3","bgotdgu8cho.","bibliotecaF","bicicleta d","bicyclesB","bien r#,","bigK9","bikinaK",
"bilbaíno 8","bilirrubina@","billboard`A9","billie c","billy(-p","bin3jekig9s(","bipolaridad i","bird#","birdland o","bit i",
"bites[","biznietoC","bjorn$","bkajs8wayd4#","black m","blame n","blanca.","blancasW","blanco mS4(t","blancos eb",
"bligeQ","blue tme,bX","blues vtPLIB697","bluey<","bnlsdqnj0lu)","bob b","bobby/.","boca 83","body n","bohemian[",
"boj6fl8eoxaY","boleroKH","boney/","bonitas f","bono r","boogie n6","boom o","botánico\\","botas*","boteW",
"bottom vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","bout<","bowie 4","boy o?p","boys b","boyzO","brand h","branigan s","brasil o","brasileña`",
"brasileñas(","bravoU","brazilian`","brazos u","break[","breakfast i","breaking 7","breakthru[","breezin:","brian[ra",
"brickY","brillante qkeB","brillantezV","brillosQ","bring h","brit tB","británica i=","británico te7,","británicosY4","broadway:1",
"broken%","bronxQ","brooking_","brota rV","brotherP","brothers m#","brown t</","brusca p","brutal%","bryan a",
"bu26eM","buckingham 9","buen roih[KG?><3-E","buena dP=<:/","buenasG","burbujas@","burlóJ","buscar vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","buzz=","bvauqazuh9oM",
"bw6sfc9u07o b","by vutsrqponlkjihgfdcba`_^]\\[ZYXWVUTSRQONMLKJIHGFEDCBA@?>=<;:987654320/.-,+*)('&%$#mP1e","by2e2m4thnmD","by2ew9 0","c0blkudnyno c","c3nscn89klo 7","c5s6dfiqywo)","c7wjmepf7u0 j","cálida k","cálido 2",
"cálidos cD","cáncerI43)","cárcel+","cómo[S+'","ca46znjrzey h","caído\\","cabeza s","cables k","cabrales 8","cada q.",
"cadenas c","caducidadX","cae q","café@","calabria*","calamaro j","calaronJ","calderónS","caldwell.","calidad tsocUOG<9&$",
"calidez(","caliente m","calificativoT+","california b","californiana m","call 7","callao@","called g1","callejónP","calor\\",
"cama`","camaleón 4","cambió;","cambiando nS","cambiar+","cambio:+","camilo 0","caminaré s","camino qPM","campo?",
"camposM","campuzano*","can n+%#","canaan 2","canción ur`]YGA*SJIFW(","cancion d","canciones urkjgfc_^YWUSROMLKHGECBA@?=;6541.-+*(&%$sqmihb]X70lP)J","candiE1","candidez b","candoroso 2",
"cano(R","canta ut","cantadas>","cantan 0","cantandoI","cantante pgNLEA;762.-%>","cantantes&%","cantar ne]WA?","cantaráS","cantautorJ",
"cantautora 2","cantautores-(","cantidad 0","canzetta 1","capaces qe><6","capacidad r>","capasM","capaz thXUPNM@;0)%k","capitalJ","caprichosU",
"capturaban 2","capturadaW","cara`","caracterR","característico r","caracterizado$","caracterizar@","carasW","carbónM","carcomidoY",
"cardíaco;","careless;","careyO","cariño`","caricia v","cariciasB","carisma\\U","carlos dL`_S","carmonaC","carne]",
"carole 2","carolinaL*","carpenters l","carrackX","carrera nm`XWKI?75+(","carreteraA","carry.","cartasU","casa d_ZW8","casal p",
"casi kebWSGECA0(%p","caskuxI","caso,(%","castellano$","castro*","católica^","catalanaJ","catalizar<","catalogada?","catalogados o",
"catalogar k","catapultó f^","catapultarlo]","catapultaronU","categoríaU","causa t","cautivar:","cay74#","cayendoP","cbs n*",
"cds$","ceI","ceilingF","ceju9kvabao[","celeste v","celine,","celtic t","censuraJ","centrándonos p","centró j",
"centroX","century i","cercana 4","cercanosD","cerebralJ","cerebroYX","certificacionesQ","certificadosA","cewhzel76eeC","chacon 3",
"chainsV","chakaQ","champú p","champions[","changes 4","chanson o","charles cA3","chica)","chico r","child;",
"chileA","chilenas h","china m4","chinaâ´sA","chjt4xdazoc n","chocolate 3","christmasO","chvtmwyplakA","ciega d","ciego g>",
"cieloN","cierto=","cimientos*","cinco l","cineJ","circleV7","circula m","citados 6","city oP","ciudad+(",
"ciudades u","clásicas o","clásico m?3+","clásicos j3","clímaxP","clanL","claptonX","clara k","claridad s","claro o",
"claudicaranW","clayton r","cllore>","close l","clubs o","cndlbu0g^","coF","coche pU","colaboración 3","colaboraciones v",
"colaboradora*","colaborarX","coleR","colectiva[","coletazosJ","coletillaQ","colombia d","colombiana d","color vmeX.","colorido<",
"comaJ","combinabaP","combinaciones a","come o","comentaE","comentábamosS","comentan 1","comenzó];","comenzando o","comenzaronRD",
"comercial mME9","comerciales e","comercialidad i;$&","comerse k","comes:","comfortablyY","comienzo srWSP?pG","comienzos tlcbL*RP","commodoresF","como sri`_\\[URQMKFC@>:872-,vnlfd]ZVNGA?<;54.)%$uqomeXWSJE9610+(tpkhb^TP3c&",
"compás c","compañía*(","compañías+","compañera)","compañero_","compactaba l","compactadas 3","compaginaban i","compaginando 5","comparadaE",
"comparesZ","compartióI","compartirM","comparto 4","complemento*","completo 0","complicadoQ","complicidad 6","componían[","componenteS;",
"componentes o[S","componer 5)","componiendo f","composiciónOIG;","composiciones vcND>2,)($9","compositiva u?<)","compositivoS","compositor pgfXLBA70.-+'%6","compositoraE2'","compositores tsSA2",
"compostura(","compromiso 2","compuesta me(","compuestoC/","compuso 2","comunes^","con e`\\[ZHG982#vlhca_YULEDB41-sribTO?>:53,$tomgRKIFA;760+('qjXVQNC@<*)k^WJ&%p]MSdP","concibióT","concierto&","conciertosYCA",
"concreto^","concursoE","condenadosJ","conduceS","conducir?","conductor%","conduzcaX","conectandoM","conectar hd","confesar k",
"confianzaE","config vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","conjugando$","conjugar k","conmigo:","conmueve 1","conocíamos k","conocerZD:","conocerse 3","conocida r\\1d",
"conocidasYP&","conocido vtohZQA4","conocidos s`D=6,$","conocieseZ","conquista+","consagrándose 8","consagróT","consagrado)","consagraron i","consagrarse n",
"consciente c","consecuencia pdZ;3)","consecutivasR","conseguía&","conseguidoT&","conseguir]XN","conseguirloT","conservan c","conservando c","considerabanS",
"considerada c","considerado rNI-","consideradosC","consigueJ","consiguen e","consiguió sQ%","consiguiendo k","consiguieron 6,'","consiste o","consolidación p",
"consorcioS","constanteA","consumadoW","contó a","contaba 30","contacto:","contador-","contagia<","contagiarnosL","contagiarse 7",
"contagiarte%","contagioso n","contagiosos;/","contaronP?","contarte q","contemplarW","conteníaWP","contenida q","contenidoY","contenidos vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"content vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","contigoDH","continúa ut](","continúeS","continentesA","continuó 53","continuado b[","continuando j","continuarD)","continuaron^",
"continuidadP","contra h4RJ","contradecir?","contradicciones^P","contrapartida^","contraria p","contrario@?","contrastada(","contratiempos)","controlP@n",
"convencional p","converger 3","convertiéndose 3","convertida@","convertido aA4","convertirseQFC","convierteD","conviertenU","conviertieronE","convirtiéndolos/",
"convirtiéndose rdcS8","convirtió kWTCP","convirtiera,","convirtieran;","convirtieronO6","convulsaP","cooke kP","cookieconsent vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","cool/","copa d",
"copia 3","copias^,'","corazón ut`SPJIH>+","corazon u\\H","corporal)","corre#","correctaE","corriendo'","cortes*","corto gN6",
"cosa$","cosas t]","cosechados 6","cosechar d","cosi v","cosmic=","cotidianidadM","country tnbF91#m","cowboy=","coz*",
"cphpfU","cprgk5rksc0N","cqbts6bip1eO","críticaP","crazyY","creación 8","creada f","creado/$","creadorJ","creamZ",
"creando 7","crear t.","creatibidad 2","creativa*)","creatividad pF","creativo g74n","creativos:","crece(","criadaQ","criado+",
"crime i","crisis ki","cristalina lB","cristalinasV","cristiano dP","cristinaJ","criticado&","cropperW","cruce k","cruces>",
"cruzR","cruzar u","crying b","ctdr6brrvx8<","cuéntameDo","cuídateD","cual s2","cualesY","cualidad e","cualidadesTG:.",
"cualquier vedROF:65","cualquiera vRK","cuando rqkbXTMI1,P?","cuantosB","cuarteto o^","cuatro_","cubanos\\","cueca h","cuenta s%","cuente 8",
"cuerdas dQ","cuerpoJ","cuestaR","cuidadasFD8'","culpa h","culto r^C","cumpleañosP","cumplir p","cun7paje8ic]","cuotas,",
"curiosamenteZ","currante]","cut f","cuyaXP","cuyo n0","cww03hjhod4S","cye8et h","d27gtrppayk h","d2yrM","d4 i",
"d5cr9mrlsc0 q","d77tdtsn7nk p","da t","dándonosU","débil)","década utnfd^ZYXQPKC:521+%9/","décadas utebO<:(&","décima)","déjameS","día ut]",
"días'","daba_O","daddyQ/","dado vW","dímeloN","danE5","dance h=;1/k4","dancingF,$","dandoFE<:c","daniel r",
"danza h","danzan h","dúo l3","dúos l","dar vnkjXWM?","daría n","dark vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","darles;","darseD","datalayer vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"date vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","dave r","david 4","davies i","davis v","day hO2","days lk","de#ifa@NLOG4vjgb[THD8.^V=5?>/-_\\KIF;972lhec<1*'&uomZUQ6s`B%RE3$dYXCWM:+0](qSnkJtrA,p)P","deacon[","deadI",
"debajoKE","debería:","debidoWS","debilidadP","debilitóF","debilitamientoP","debut k_OE?53","debutó 1","decíamos^?","decayendo n^",
"decide n","deciden*","decidióP","decir iRM>6S","declaración\\","decliveP,","dedicabanG","dedicadaY>","dedo m","dee 7",
"deep,","define#","definen t","definición@","definir gaN","definitiva;p","definitivamente,","definitivo'","degradamientoP","deja odN<",
"dejándonosJ","dejó ucZW3&","dejabaC)","dejaban/,","dejado 1)","dejando+","dejar k)p","dejaron_GD/","dejarse c=:","del pmiha_]NG=<87/#vuslfcb\\VUTOEDBA@?>;10.-nkge[YXQMLKHF65,*)rqod`^ZWRJC432+'&%$P(jS:9It",
"deleitado&","delicadaB#","delicadas l","delicadeza 72","delicado 6","deliciaX&","delicias i5","deliciosos o","demásSQI'","demoniosP",
"demostró?","denman c","denominado t","denominan^","dentroNB9$","depositarU","depresión)","depresionesQ","depresivas;","deprisa p",
"desátameT","desafiante*","desapareció l","desaparecidoS/","desaparecidos h","desapareciendo 3","desaparición)","desapariciones,","desaveniencias$","desbocado?",
"desbordanteZ","descalzos d","descaro jE_","descartar`","descendió 9","descomunal[","desconfiarC","descorcharQ","describiendo h","describir)",
"descubrióB","descubrimientoVE","descubrir ge","descubrirlos_","descuidada)","desde trmjed^YWTHG9('$SN=4","desempolvando$","desencadenante 3","desenfrenada m","desenvuelvía&",
"deseo p","desesperada q","desgarradaWI","desgarradoraW","deslizándose e","deslocado n","deslumbrante q","desmedida 0","desnuda qB","desnudesJ",
"desparpajo n","despiertaL","después qnS;3","despuntó]","despuntaba n","destacados 8","destacando`","destinoRA+","desván u","desvaneciera l",
"desvanecimiento,","detalles`","deteriorar)","deterioroP*","detonante 3","detrás$","detroitP","deuY","devaneos&","devoción=",
"dfe3s3*","di s","di0 5","dia t\\SPG:(","dió mkWS","diamante v","diamondY","diamondsZ","dianaFA","diariosE",
"dias r^4","dicesH","dicho t","diciembre;","dictadura h","didn-","die=","dieronGC","diez 8","difíciles r",
"diferencias u","diferentesS/&","dificil c`B:&$","dificiles)","dificultadM","difruta 6","digan]","diggin?","digna t","dignasB",
"digo u","diguehwmorc u","dime js","dimensión r","dimmi s","dinamismo 6","dineroP","dion,","dionne,","dios(",
"diosesC","diríaE","dirección pE","directamenteX","directoL:6&","director pJ+","directos 6'","disco nkf_]?><96/.+'W53,","discográficaK?n","discográfico k/E",
"discografía g$","discos r`_YWQK>=;8520*&k]RA","discoteca 5","discurrido 4","discusionesP","disfrutabanW","disfrutado%","disfrutando kj$","disfrutar tok_S<1","disfrutarlo&",
"disfruto.","dislumbraba k","disminuidos u","disolución_^MD$","disparesR>p","dispuestas c","dispuestoM","disquera>","distancia`","distina*",
"distinguidasI","diva(T","divagando%","diversión 6","diversidad,o","diverso o","diversosE8&","divididaY","divinaT7","divino v",
"djfgb<","djklltlmnds'","dkytjloxgmq m","dluhzqhlcme k","dlxpnif0yks^","dmgvs2j05ha e","dnrxd6v4 9","do.3","dockW","doctorados t",
"dojvwB","dollyA,","dolor r","domingoA","dominicano@","don i[XE<ed97.#","donâ€™tV","donald 5","donde utrkid^ZYWUTSPOE843+*J&o","done%",
"donna v","donostiarrasD","doobie m","dorada l&%","dormirL","dos u\\SPN>8J","dosisU)","dotándolo t","dotadoI;","dotesM.+",
"downVQ7n","dr=","dream<","dreamer i","dreamloverO","dreams-b9","drogas lYQ;P","drove b","dtpqoafxc@","dtvbcg6thdk 7",
"dublinesaE","duda c]XSJ9rU","dudoH","dueñoPI","dueños vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210.-,+*)('&%$#/","duela]","duende>","duermanM","duetoV","duetosP",
"duke g","dulceWD1","dulces+","dulzura?B","duophonic 3","duper?","duque 4","dura 4","duraciónY","durante mJ9p",
"duro)","dust[","dut5reu6pqm d","dxdkywilt74F","dylan b","dzhje11cg^","dznqcmpcqxq 5","dzsue5ugxf4 d","e3 r","earth 6",
"easyF3","eazjxniqnqi 0","ecologíaM","económicaP","edén p","edad u]KB","eddie 3","edema p","edge r","editado>",
"eduardo qJ","educaciónYV","eerpl3wkwdiQ","efímero 3","efecto$","eftlkww542g-","egocéntricoZ","egocentrismo k","egs(","ehpe7b4fx8.",
"ehqg6B","ehulq#","ejecuciónJ","ejerce d","ekcicnwa+","el sifb_YVUF<5uljdXRK@>=1-)vh^L2tcNI;:/+(&pom\\WTOE?80.'q[ZHB$r`MDC643k]Q9*%nSJ,AP","elaboradasR;","electrónica 4","electrónico 6","electrónicos\\=",
"electro=","elegancia qaKI<:c","elegante mP9%","elegantes l","elegidas 7","elemento*","elenco 6","elevarles$","elixir)","ella fdcEB21",
"ellas sJ4h5","ello toc^[=0.","ellos rnleb_^\\SHDCB>6-mj[$","elocuente'","eloise p","eltonX7","elvis b","embajadora d","embarcado\\","embelesar s",
"emblemático r","embrujada p","emergentesE","emi 3","emigróB","emisoras 3","emoción uL9#","emocionándonosW","emocionalP","emocionar h",
"emocionarmeJ","emocionarnos@","emocionarteM","emociones utXN>)(","emotividad kF7","empapeB","empaticenX","empezó bPKI","empezarP","empezaron b",
"empiecen 5","empiezaM","empiezanJ","empiezoT","empresariales u","en i`_NG?'lZXWM=<4sfeca^YK@>721.%qm\\[VHF-+$#vrjhUIC:63)(kbOJBunE;8/,&tg]RQD05*9dTSpAoP","enérgica 2","enérgicas m","enérgicoP%","enamoraN",
"enamoró]","enamorado v\\","enamorarN","encandilaN","encanto scWE=<&","encantos;","encargóW","encauzadoG","encerrabaZ","encerradoH",
"encienda 5","encogerJ","encontrabaS","encontraban k","encontramosS","encontrar o=&","encontrarnos;","encontrarse+","encuentre&","encuentres d",
"encuentroH","end^I","endlessF","energía mjW0<6=","enero 4","enfermoT","enganchados-","enganchar e","engancharte>3","englishman h",
"engranajeD","enmascarandoJ","eno ar","enorme`IF0","enoughP+","ensayarG","enseñándonos n","enseguida?","entenderT","enternecernos@",
"enterradas k","enterrados k","entonaciones]","entonces sokSQ3","entradaSD1","entramado(","entrando 2","entre rmN$8%","entrecruzabanT","envidiableKF",
"envidiables rO","envoltorio k","envolturasB","envolvente m","envolverá v&","envolverteX","envolviéndote(","envolviendoB","eo7iwlmfprm=","eo8r1w8qrgo b",
"eoqu h","epmt3g0w i","eqlnl8H","eqp1s#","equivocaría 8","equvoqut1vmE","era pnYVPMIFC;:51,*k","eranJC96$","eresS","ericX",
"erizarmeJ","erranteG","erupción e","erykahE","es rqpoljihfba`_^]\\[UTPOLIGFEDCA?=;832/*)($tkXVRQKH@>976541.-,+'usnmeWNB<:#dY0&%vgcMZSJ","esa srleSE@;52/*%","esas b^QPJ7X","escándalo]","escándalos;","escénicoJ",
"escalofriante m","escapan(","escape 1","escena<","escenario cb[P%","escenas>","esclavitudP","escondeE","esconditeT","escritor 3",
"escucha d","escuchabaW","escuchadas lB","escuchadoS","escuchamos,","escuchando cM","escuchar=<,#","escucharleX","escuche h","escucho.",
"escuela t\\","escultura p","ese siedc`ZG>:,)#nXSE3","esencia qYB6)","esferas 0","esfuerzosA","esguince p","eso_LE&","esos mke_WUSRPE3)6*","españa o\\TJ0*(8",
"español usjgeJCA>*TR0)'","española pTS","españoles uS","espacioDB'","espada 8","espaldarazo'","espaldasD:","esparce)","espírituR6","especial tked\\XTSKH>#",
"especialesH","espectáculos/","espectacular tsZ6+%","espectacularesYQ=","espectacularidad 6","espectante k","espectro s","esperadosT","esperando$","esperarTL9",
"espiritual)","espiritualidad t%","espléndido g","espontaneidad^","esposas h","esrb6yv a","esse`","est#","esta ihc^WVTSQE?=91","estáS.-`",
"estásS","estéM","estã¬loF","estaba m^YQE*","estaban 6","estaciones)","estadoX","estados o]S","estadounidense^3-","estamos l>C",
"estando nkC","estarJ-","estaré k","estaréis:","estas.","estatua\\","estatus i)$","este vtok^WTFC?:910#md&","estilo po]NMGEC?9m","estilos v>8,&",
"esto dS","estos$","estoy gD","estrafalario 7","estrella]IF'","estrellasO","estrellatoPE","estremece 1","estremecedorasJ","estremecedores;",
"estremecerte t","estribillos^","estricta%","estrictasY","estructuraM","estudiabaB","estudio)","estudios p","estupendasG","estuvo oUP",
"etapa rqlF;854*hS)","etapas;","eterna i","eternamente)","eterno 0","eu`","europa o]TS/","europe^","europeos'","eurovisión]SA$",
"eva'","evans r","even i","ever h1&","everybody^#","everything+","everywhere 9","evidente 3","evidentemente k","evitar;",
"evocando=","evoluciónR:","evolucionó 9","evolucionando fY","evolucionarO","ewjciG","ex_","exageraciónS","excéntricoP","excelencia)",
"excelente 5","excentricitésT","excepciónS","excepcional 2(","excepcionales 6","exceptuandoR","exhalan s","existían 9","existencia 7","existencial k",
"exitosa;","exitosas[","exkwkqM","experimental kY4","experimentales a","experimentarM","expertos^","explain t","explicaciones k","explorarM",
"explosión,%","explosionar 6","explosivo j","explotaO","explotado u","explotando 6","exponentesX","expresaW","expresaban^","expresarU",
"exquisita c7","exquisitasC","exquisitoX","extensaJ","extenso t`","exterior e","extraidos<","extraordinariaU/+","extraordinario l4","extravagante[Z4",
"extrayendo'","eye^","eyed meXt","eyes a:X","ezk9rhnnvwe s","f5q4y<","f8ksqdsztugL","fácilE7c","férreo n","fértilesZ",
"faceta uQ?;)p","facetas u","facilidadJ4","factura p","fagen 5","faith h;","fake e","fallecimientoW","fallidoR","fallo;",
"falsete mb6","falsetes 6","falsetto,","famaI2/-%t","fame r94","familia nSC","familyQ","famosaYW&","famosoR$","famosos pH(",
"fans$","fantástica me0","fantásticas v","fantasy 6","farian/","farrell/","fascinantes 6","física#","físicamenteZ","físico)",
"físicos u","fast;","fastuoso 6","fatal_","father;","favorM","fearsV","febrero&","fechaX","feel^n2",
"feelin n","feelingV:","feliciano>","feliz>","fell k?","femenina dVTO2","femeninasO$","femmeR","fenómeno]","fentaniloZ",
"fernando_","ferry a","festival$A","festivales]*","fever,","fgb9cvwdn04 b","fichar>","fiel`MB","fields h","fieles o",
"fiestaR","fiestasD","fifa d","figuerasT","figuras 5","figure;","fijó?","fijarse r","filaM","filántropa d",
"filadelfia+","filipinasJ","filosóficoY","fin tl)(G","fina q","final pljWP,","finales tsjVPMG,","finalizándolaR","finalización q","finalizada 9",
"finalizando h","findI","fine^2","finura c","fire>-6","firmaO","firmado p","firmar p","firmeQ*","first+",
"fitipaldis 8","fito 8","five n","fj9ruzimczq[","fk9iqnq883o v","flackE","flagelantes[","flame.","flamenca q","flamenco qC",
"flamencosMC","fleetwood 9","flicteaV","floodB","flor uCU","floresC","florida 5","floteQ","floydY","fluye=",
"fly fY","fm8ggdigcwyN","fmjgnedhkby p","fnfzfwlm72c,","folk tom'","food o","fool i#m","for fOB.#rV&%","forjada+","forjando'",
"forjarseP","forma spe\\WUMJA>7+)k=5","formó j_F","formaban n9*","formacíones n","formación ncDC<*S","formacionesS","formadaS*","formado lc,","formados'",
"forman q[M,","formar j^\\LE,)","formaron onf^[IG=3,","fornaciari v","fortuna t","forzados)","fotos h","found r","fovcbmkuw0/","fragile h",
"fragilidad)","francésSA","francesaR","franciaR","franciscoS","frankCA/","frankie,","franklin cQE21","franquistaJ","frío@",
"freddie[","free h^[1","frenéticoN","frente rqoliaLC6","fresco,","frescuraDCj","friaL","frialdad q","frida$","friend<2",
"friends[","frivolidad%","frjctJ","from oiE7#3","frontier 5","fruto 3","ftbwo6cetuk u","fué t","fue tskfc_ZYUQOMEDB?;\\WTSRIn3P","fuente^",
"fuentesD","fuera s","fueron pnjh^TPC/&%","fuerteM","fuerza eWRPJ?610%","fuerzasSD","fueseT","fugaP","fun 9","function vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"fundíanM","fundadoresS","fundamental[","fundamentalesF","fundamentalismoP","fundiéndose+","funk nkZK=<1+%6","funky nI?=6;","fuowykvnwyi,","fusión tLC<6",
"fusiona q","fusionandoQ.","fusionar%","futbolA","futura\\","futuro pUP","fuwryuderhcH","fwqpqycqgp8*","g2n0tkfrqhy[","género vtQKC",
"géneros 4","gafas b","gaga[","galardonadasO","gamaU","gamble eI","ganándoloE","ganó]KA2","ganando>","ganar@",
"gang<","garayS","garcía_'M","gardeD","gargantasI","gary f","gato`","gaviota(","gaye fE<3P","gckghm7gmwm g",
"gdza0bfbpim%","gees,","genéticaM","generabaP","generación 2/,g","generaciones t]K-","generalV'","generationZ","generosamenteI","generosidad t",
"genial kZC:%","genialidad qY","genioZ","genios)","genteN","gentleman t","genuina*","genuino g[4","george tQ;:","georgiaB",
"germen*","gerry 2","gestos]","getIVP+","getsemani 0","gettZ","gf8qy f","ghaqfL","ghetto:5+","ghettosP",
"giae7yz7ghiK","gibb,","gigY","gigantes)","gimme$","gira d*$p","giras b]:","girl t=/-4","girlsA","give iP=:+",
"gix2pbrbxcq/","gklpl4fhzus d","glam p4","glamour ca","gloria ts","glorias k","gmmc0z0vg04G","gmt j","go[V93/o7","goffin 2",
"gogh jD","goinQ","goingP","gold fBh","goldenA","golpe[)","goma p","gone 6","gonna=3+","goodI#1",
"goodbye li","goodnight-","gordon h","gordyP","gospel tVI1%","gotPN2eb1","gotta/","gowebnppuom 8","goza`","gozaderaN",
"gozar%","grabado p","gracias mecTQPLA>7(tR","grado o","grammy trokgVQOK>;92-%","grammys oml`^PIFA:,&","gran son[WVTMJFE=/+rm]Xp","grand#","grande<0","grandes vsmcbWUPLFE<:1*(",
"grapevineP","grave]","grease,","greatY","greatest:","green 3%","greyE","griega(","groove 6","groovin o",
"ground ng","grove m","grupo qonec_^[ZXRMLFD86/*($rpmjhaYC<S9,","grupos oYXG8,'p","gs069dndiyk 6","gtag vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","guíaS","guerraP@","guess 7","guille'",
"guilty,","guitarra rq>:'f","guitarras[H","guitarrista[W'C","gusto oiK","guy a","gwendolyneA","gxepv4kolz0-","gxqjx7fkmna 8","gypsy 9",
"h6kyavn8ons 7","h9tevfisdyoZ","ha tqon`[WSROLHGED@=;840-,%d]A1(&v","hábil-","había i","habían)","haber ug80","habernos t","habichuelaC","habiendoK",
"habilidadesE","habilidosaV","habitaciónR","habla r]","hablábamosP","hablamos]I","hablando lg>","hablar rH'Yn","habría*","habreísS",
"hacía q)","hacían:","hace gdYN/","hacen qcT","hacer vq<:","hacernos@","hacerteM","hacia kfYRO=9","haciéndonos 1","haciendo bY:5H",
"had?1","hadley f","hagaS","hale c","hall r91","halo k","han vsqjeda\\SOD=4320*)troKA'$","hao;","happeningP","happiness%",
"happyQ","haráJ","hard k","hardest 7","hardline k","haritzD","hasS)6","hasta trpodWOIB94-*%^S","hat1hc9snweO","hauser o",
"have tr","haven r","hay tr^]J=87.","hayá&","hccbfuziN","hcumwrfxg4e-","he 1","head h5","heal;","healingP",
"heardP","heart hE7#W%","heartbreaker,","hearts 1","heavenB3,#","heavy*p","hecha i","hecho vsd`]XKHE=;2)$tD","hekjnahwihwL","helloF",
"hemorragias d","here:1YV3","herederosD","hermana 3","hermanas hS","hermano f","hermanos nl,#*","hermes*","hermosasK&#","hermosoW",
"hermosos 2","heroína)","herramientas:","heterogéneaJ","hewson r","heyA","hgjsbrubxX","hgzgwkwlmgm[","hh3hgusk7pmS","hhx6rgrkgf0 o",
"hicieron iYO;65p","hieloI","hierro)","highP","higher g","hijoRC","hillsEB","hilo%","himno rJ","hipOQ",
"hipnóticos/","hippie?","hips d","hispana]D","hispano dRHDA>(j","hispanoaméricaS","históricosS","historia urn`RJA42,)q","historiasT-","hit 3",
"hitosS","hizo liQECA3+*)","hjf3e2zgnkg 8","hkm0ih8slcgJ","hlguyxtmwe4 3","hllcc f","hm8ehtn9rmwN","hmhezd9bsb4 k","hmkshplxnxe g","ho7796 n",
"hodgson i","holding k","hollerP","holliday c","hollywoodI","hombre vtpZXSI@&%#P(","hombres 1","home i3/e","homenaje)","homenajeaban f",
"homosexual r","honestidad@","honorT","honoris t","hooker t","hopOQ","hopeV","hora tnk)","horasG","hospital)",
"house<3","howWX,%","hoy u]\\WSR:*(t","hpx'","hro0wkv4yjo\\","hrzgzrqnj58 a","hshyyQ","hspefM","hsq4b-","hubieran/",
"hucknall e","huecoJ@8","huella kc_","huevo p","huff eI","humano u","humanos r","humo l","hung h","hurt 3",
"hurtinI","hurts^","huzwW","hvwnfdadvssX","hwmtfxzxm34 1","hwukrZ","i4uyofazwpa:","i6ibauwboda,","i9st43hymbyX","iâ€™m 1",
"iâ€™veW","iba nkA,","iberoamérica 0","ibn5dzaw4eqV","icY","icktoz7blla%","icteria p","id6zoy h","identidad c\\KHC","identificarR",
"identificaremos]","idiomasRA","ido e=S'","ifBhek","iglesia^","iglesiasA","igualSOFE;96A,","igualdad r","igualmente nhQC","ihs,",
"iiO","iikae8wi0s0$","ik s","ikermdasvtg u","il v","ilegal p","illán_","ilusiónU","ilusionarseM","im1uv8dk00sV",
"imágenes vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","imán c","imagen pnbRP?;74$","imaginaciónM","imborrable 3","imj4t7oidi0.","immortality,","impávidoZ","impasibles]","impecableO",
"impedido 0","impedieron j","impedimentos u","imperio t","impidióW","implicación 2","importante rZS","importantesU?,","imposible 0,$#","impregna#",
"impregnándonos u","imprescindible i","impulsóP","impulsaron k","in rB?:95/.ihbWV6,&Y","inadvertido 3","inalcanzablesS","inamovible b","incalculable)","incial*",
"inciales[","inciaron m","incluía,","incluida m^","incluido t-%","incluso slSQEA4*$t1","incluye-","incluyen,","incluyendo vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","incognito<",
"incombustible]","incomprensión r","incondicionalK","inconformista pZ","inconfundible>]","inconfundibles q","incorporación mS","incorporandoU","increibles q0","incursionarQ",
"india#","indiferente/","indiscutible n","indiscutibles;","indispensables 5","individualidad;","inevitable;","inexorable1$","inexpertaE","infante j",
"infartoJ","infierno*","influencia kb[QM3","influenciado m3","influenciasQ?","influyó,","influyendo+","influyente q","influyentes gR84%","información ge",
"ingeniería r","ingenio r","inglés aS*","inglaterra h&","inglesa=","ingredientes<","ingresó 9","inicial mj","iniciales^Q","iniciarF",
"iniciaron qC","inicio vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","inicios hfed","inimaginablesS%","inmaculada(","inmediato;","inmortal 4","inmortalización+","innatasT","innerP",
"innuendo[","innumerables$","inolvidableJ","inolvidablesU0)","inquietudesM","insaciableM","insanity=","inseparable 7","insertarVE<vutsrqonmljihgfedcba`_^]\\[XWUQONMLKJHGFCBA@?>;:87654210.-,+*)'&%$pkZYTSRPID=93/(#","inside:,",
"inspiración r^D<","inspirada u(","inspiradas q$","inspirado g","instanteW","instrumentación q","instrumentales o","instrumentista tg","instrumentos k^G","insuficiencia p",
"integrante(","intenciones\\","intensidad(","intentaseE","intento pR","interesantes 5","interior oWQ","interminableA","internacional dA*'","internacionales=",
"internacionalizar p","internacionalmente]","internos j","interpretabaP","interpretación k]VO;,0","interpretaciones o]UN0%","interpretado e","interpretar kU>(","interpretarla 0","interpretativaW%",
"intimistaM","introducidos r","introducing k","introspecciónB","intuición d","invita<","ioN","iokadqvk8U","ipiñaS","ir^",
"iris m","irlanda tEB","irlandés t","irlandesa tr","irrefrenable k","irrepetibleZ%","is vutsrqponlkjihgfedba`_^]\\[ZYXVUTSRQPNMLKJHGFEDCBA@?>=<;:987654210/.-+*)('%$mcWO3#I,&","island 5","islands,","isn g",
"isnâ´t g","it m^=$bP72#n","itâ€™s^","italiaA","italiana s","italianas s","italiano vsS1","italianos v","ius84sd0hra>","iv5ojxem6fuH",
"ivan t","ixdnnw99Y","iyiol$","izaskunS","izgwdsrq1eq;","iziborE","izodvbmtdh0 e","izugarria vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","izzpG","j0r7cukawg 3",
"j1sa1t3m?","j3we3 3","j789gid1kay t","j7oqepfe^","jóvenesE","jaén]","jackson onF","jacksons n","jamásWT0","jamiroquai=",
"japón]R","japan.","japonésA","jardín\\","jarreau&","javier jS","jay=","jazz\\VKICB>65.=<:&o","jazzman 2","jcm4h9rom(",
"jdwljhqf4 5","je2scisqmpe f","jealous a","jean d<","jesús q","jesucristo 0","jesus m;","jfjjs0xsm9mG","jhtdwimy 0","jillE",
"jltj5ktfyw8 e","jnvy7srofq#","joaquin j","jocelyn<","joel(-","john tf[X7","jones v","josé qCS>","joseR*(","joshua r",
"joss?","joven kE?","jovencísimaO","joyas ge)","jpmxjmais04C","jppna5pqrpwR","jq2dvwsviio;","jr r","js vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","js6yqyzszmo 5",
"jtxv02tyr5a 6","juan q\\SC@'","judaísmoP","judio 1","jugadorA","julián p","julioA","juntóP","juntaron j","juntarse 3",
"junto cYUMHFD52.)#_","juntos j","just mgB+l1","justiciaT","justoP","juvenil\\R","juventud sEA)","k1ljplq1v6y c","k2ldicb5ejg=","k5zp7eqltde+",
"k7oajjdshs8Z","k9yiq0onism%","kadajqv6sdkK","kamakiriad 5","karen l","katieB","kay=","kc^","kcpc18sg6ua c","keeble f",
"kemp f","kenny me,","ketamaC","kgjfpcjwkyg)","kgrqhwfjq b","khaledC","khanQ","ki5p5veewye^","kiki 7","kind[",
"king c72","kissZc","kjlmejl5yqm]","klvq0iazh1a h","kmz4panwlae p","knd p","know^#e","konde5c7og8 a","kool<","kop3cuvd2qq v",
"kpdjqbthay 4","kqa u","kqvwyu4bdmo;","kszyhtq p","kvc5rcl0bis:","kvdmlk3ksyg/","kwnfwzem6swR","kytmvki 5","kz 0","kzxndlvzs3k&",
"kzzhzlud6xc%","l0cvofsuhc4 6","l0etbwiI","l3d7unj3qck*","l6vyj*","l7vrsuZ","la ofbVH?.-#ha_^7'$lieLF=4vsg]\\@>;62mk[ZRONKIC53/ujXWTQB98`UJ1+%cYEA<&MD:0nS,(tP)*drpq","lópez j","lía(","líder e",
"laderaT","ladoKS","ladyI`","lag4zjyx89gM","lago q","lakjahibl2y@","lamentablemente qJ","landslide 9","líneaP","lanois r",
"lanza 8","lanzándose h","lanzadaT","largaI,)p*","largo eb`A,+(","larry r","las uskigfcb^][ZTRNLKJIDB?>=;760/-,*)'rmlhVUOM54.&tndY$P(S9","last+","late 2","lately t",
"latenteR+","latidoHJ","latina d`]\\","latino dUNK>","latinoamericanoT","latinos>","laura s`E","lava e","lb6a h","le t`ZYVTSQPNI-(#h+)p",
"león t","lead.","learn=","learningY","leave if","lee tc\\","lefhnn7rl4w o","legado t`ZC0","legal p","lejanaW",
"lejosE","lemsuQ","lenguaD","lenguajes m","leon e","les nme^SRH=6/*oD","letVPE7+k64%","letra mh*(","letras tqo^YRMFD87'$","levantarR",
"leyenda`]PA)","leyendas g","leyreD","lhcp4mwabgy r","libertadTC*(u","libertadesJ","libreU","lider n\\8","liderada=<","liderando hX",
"liderazgo i","lie d3","lies 9","lifeV74ogc","light>","likeB#I2","limpia l","limpiamenteB","limpiasV","linares]",
"linda#","lindsay 9","linguaS","lion t7","lionelF","lisC","lista lA,)(","listas mfS9","listen m","little iW9k3",
"live.&","livingX","ljntnoc81oa]","ll fOnI","llama e*","llamaba 4","llamabanS","llamada piE+","llamado qn^<3/+","llamadosS",
"llamandoL","llamativos/","llave/","llegóI-X","llegadoA","llegando vdcMA;.C","llegar^SMEB8","llegarían\\","llegaran;","llegaron k",
"llenaZWVPE6.","llenóJ","llenando[","llenarnos 7","llenas vqbWMKJF76#","lleno thZO(","llenos lca_V?&/","llevaB=<.p","llevóPJ2+)","llevabaQ;",
"llevado;","llevan]H","llevarC=)","llevaríaM","llevarlaE","llevaron nP","lloraD","llueva@","lluvia qZ","lndvH",
"lo vugfeb`\\[ZXRONIFEB@<73/(qkc]UJH4,*)nmSA;+pP","locaS","localizarlo^","loco j","locura kSD","loggins m","logical i","logos vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","lograX","logróWQP",
"lograba;","lograban 3","logrado rSO1-0","logrando rVRO>;","lograron s]/,*","logroR","lokosC","londres[p&","lonely b","long ifFmlXW",
"look j%","looking r","losONLB@><;75.#mhba_][VTKE?81(tqoigdc`\\ZYXQMIF=20)'vurkfeUDA43/&%spn^WJHG9lRC-+jP6*$:,S","lose h","losing^","louI","louisiana#","love rmlhgba^[WPOF932.&%;61c?:I,+","lovedA","lovely g",
"lover&","lovin 1","loving k91#W","lrbsv9svuc8 5","ltP","ltsetg48568Y","lubnaT","lucesP","lucha p)","luciano v",
"luego 4","lugar rkdUSQH6","lugaresS0","luis*KJ@","lujo gb_TE:","lumczizrhwe@","lunaR&","lute/","luzTF@&kG","lw 2",
"lycqvyrzzw0\\","lz8djptsane_","m0k83spgeb8 q","m2 2","m4ozctfmh44 m","m4tjsn0qtme m","m50q19ivxnmT","m7v55glqria#","ma/","más tjfeb_^\\[SH7621.(vurqli`XWPONMKJ=:4*'&$sodZUIC98530,)ng?;%mk]YAR",
"máter c","máximas,","máximo 6","máximosX","méxicoT","ma1u 0","módulosG","mónicaT","mañana q","mac 9",
"madre ur","madres h","madridC","madrileña p\\C","madurezD","maduroR;","maestraG","maestría ro%","maestro t:+&","maestros q:",
"maggieL","magia kcba=<1W","magic[","magistral-","magnetismoD","maitreya k","majestuosidad:","makeP92","mala)","malo*",
"mambo o","mameknqg1gR","mamma$","manI:71$^-","mana@","manantiales:","mandolinas^","mandos rD","manera k%=","manhattan o",
"manilaJ","manoVL1","manoloM","manos h;","mantenerP-(","mantenerse rO","mantenido*","manteniendo[","mantienen*","mantuvoJD",
"manuel(u","manzanera a","múltiplesP","música srqpmlkidb_]YWTNJHEB>;832.-*)&%vne[XUQMA<75/$tg`\\ZP@640c:,","músico`XMF)h","músicos tP6+p","maquillajeR","marA'J","maría 1","maravilla 6",
"maravillándonos 1","maravillarnos+","maravillas q","maravillosa(","maravillosas m:.","maravillosoE","maravillosos o","marcN","marcó\\P2,","marcada c_R2",
"marcado qKG","marcando q","marcar,","marcas vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","mares 8","marga)","marginados 1","mariR(","mariachiK","mariahO",
"marinero 8","mars 4","marta'","martínD","martínezD","marthaP","martin f","marvin fE<3P","maryQ","masas]",
"mascar p","masculina k","masquerade:","massachusetts,","massielJ","místico kG","maticesU:5","mítico[P<6","matter-","matthew h",
"matthewman c","maunick<","maurice 6,","mayL[","mayo])","mayor usof^URO0","mayoría rWDB","mayores dPOIA","maysa<","mcdonald m",
"me oigdb[VNIG=:871+$#SPHF.%kjR?32eA","mecanoD(R","mechanicsX","mediados nheJ-","medicinales<","medinaMG","medio f6)P","mejor qXVOM@9k","mejores uVSPL6('-","melancólica e",
"melancólicas q","melancólico(","melancolíaX1","melina 0","melodíaM<3(","melodías qm_FC7$#","meluaB","memoria][M530","menO","mend%",
"menos jC","mensajeraM","menta v","menteZ","mentes cZ","mentiría=","mercado kB8/TE","mercury?[","mercyP","mereceN",
"mesT","mesaK`","mesesJ9","mestizaje\\C:","meteóricaW","metro 3","mezclaB","mezclanZ","mg i","mgb736cazvsD",
"mgqr4 3","mh'","mhznckwbkam@","mi skRMK@=3(']NH)0","mia$","miéntemeC","michael oQnmF;","mick e","midnightP$","miedoL",
"miedos)","miembro rYS","mientras jWB","miguelK","mikeXB","milenio^?1","miles v","milk 3","millón`","millionB",
"millones r`^]YRKA=;0,'","mineW<I","mineápolisZ","ministroP","minute m","minutosY","mio(","mirabaJ","miraclesP","mirarP",
"mis o&M","miseriaP","mismaSE","mismísimaE","mismo k_S/*","mismos(","missB","mississippi t","misteriosa b","misticismo k",
"mitad k","mitificación^","mito nU$","mitosS","mjewkssl8ic=","mjjzyL","mk7xgm72(","ml5yqmmfx4cR","mmmE","mmoau c",
"mmotazlnpimL","mmydosjjp5u 9","mocedadesS","moda\\0","modelo d","moderna\\","modernoR","modestia%","modulando%","moldeaba+",
"moldeando=","momento miW,S","momentos rmJ","moments i","mondays l","moneyY","montañaT","monteroD","moon^","moondance t",
"moonlighting&","morada*","moralP%","more lka;,3","morir p0","moriria'","mornin&","morrison t","mortis k","mostrarT",
"mostrarnos=","motivados;","motownFn>P","mountainP","movement^","moverse n","moviéndoseW","movida p\\C","movimiento f","moyvynkdecc 2",
"mrW","ms(","msvtomkjdqs,","mtrr8j%","mtv^'","much 7,#","muchas utgeXW(%","mucho vHE+n","muchos rqjb`SQN:7631/&$d","muerte rob[ZUP&p3,J",
"muestraGF<3","muestran h7","muestrasO","mujer dVQE21R","mujeres d1","mullen r","multi tg?","multinstrumentista.","mundial d30*","mundiales]",
"mundo vsrkf`[UTSRONMC@>=40.*dQKHA","muralla(","murcianoL","muroY$","musa c","music`X+maTA","musical umdaXVUTRQPJIFEC50-,('%$poj\\tD","musicales ngeVSMJ?:3'$","musicalmente peM","must t[",
"muy uqkba]TNJ5.H","mv 9","myE>75.g^#hXW+","mysterious r","mystery b","n9w0jvyeie8S","nacha)_","nacho_R","nació hJB#","nacida d",
"nacido]","nacieron 7","nacimiento g>","nacionalE","nacionales'","nacionalidades/","nadaX0","nadandoN","nadie/]","name rk",
"nâºJ","nâº1J","número hbRQG?>9-*r[Op","númerosOF$r;0","naranjoT","narea_","narraciónT","natalE","nativa#","nativo t",
"naturalMI:2=","naturalesD","naturaleza`U","naturalidad q","navajasR","navidad>","ncvjwzdqtbmK","ne6msf1ghfk o","necesariaE<","necesarioFB",
"necesidadM+","necesitado<","necesitoK'","needP","negraP:\\","negro mXV+","negrosW","nelsonZA","nen5efe6jsg)","neoyorkino kQ",
"neoyorkinos o","neumáticos+","neumonía)","never#I+","neville#","new vutsrqnmlkjigedcba`_^]\\[YXWVUTSQPONMLKJIHGFEDCBA@?>=<;:987643210/.-,+*)('&%$#pofZRh5","nfary9e9jo0'","ngultmh88 i","nhsooozymke>","niCu",
"niñaD","niñeraE","niño gJ","niñosI","nicks 9","nietoC","nigel_","nigeriana c","night th:9bF,","nightfly 5",
"nights 1","nigor k","nikita 7","nina c","nineB","ningún t","ninguna c]K","ninoU","nirj5m63oig g","nivelSF(5",
"njcwL","njxX","njz8osfin7mR","nlfi*","nnpygql9piyS","no vtonmkb_\\[XTRQKJED=;76,+&%$#rjdcSPMGCA/*)p]:s3","noche q]","noeliaU","nombre vusk_^\\T=,#ZSn","nombres vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#R",
"nominaciones>","nominadaV","nominado?","nooemrcws l","normal j","norman f","normasY","norte uB","nos ojihZUSKG40,)lJB<&u","nosotros r)",
"nostalgia rl","not 3","notable h>","notablemente 9,","notables n","notas<=","nothingZ.&","notoriedad s","novenoS","noventa 3",
"now[ieW","nqavfx3nxumF","nqxvmlve62u n","nrbjhgx2abq k","nt5rglvmf9o s","ntg50exbbtc f","nube v","nuestra][X0","nuestras u]","nuestroOHX",
"nuestros r^EB4","nueva rokTSD853#","nuevas:4$","nuevo pk_^MIE?9831,P","nuevos utnSC$T","numbY","numerosas s]","numerosos r`=:,*';$","nunca 10M","nuojyuy7riy(",
"nutriéndose c","nuwsf0pk3lkI","nvhncth8pdsY","nvq6vjyte=","nwi9r7xz4J","ny+","nyhmzqt8uumF","nynlvwxmrm8D","nzi9iotro04U","o24dxeqykgg:",
"o41g7woeu6oI","o8^","o8la 2","o9f6w6xd1wi_","oa^","oídoD","oasisC","oawrdidao58B","obús p","obraG",
"obras$","obsesiva s","obstinadaP","obstructiva p","obtenidos$","obteniendo m","obtuviendoB","obtuvieron m/","obtuvo b","oc t",
"océano oM","ocasión q","ocasiones vkb","oceanía d","ochenta f&","ochoB","octubre oh","ocuparD","oddity 4","odioso k",
"odstb4kp91k]","oe3qkbo5sK","oecbz6vtydg=","of i[OA:9753$rogc^X<61/-+%hWV","of8nlfk(","oferta*","offZ","oficial d","ofrece<","ofrecer]",
"ofrecieron m","ogov9k9f17cG","ogw5dhiaeig>","oh ab","ohje r","oido%","oidos oEDB","ojala@","ojbyk54rhtw a","ojosP",
"old a","oldqucmakukO","oletaV","olmkcj03fhw k","olvidéA","olvidar[>5","olvidarnos o","olvidarteR","olvido 0","om5#",
"on kiha[V=:741#n^YWP?3F.","onâ€P","once l","one^[VQO;2$r","only flb","op3kuow+","operaciones p","operator c","opkjnridqxq=","oprimidos 1",
"optimismo_","options vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","opwudidgv1e?","oq5wfx2usl4 q","oqej4lt9lbmC","oqwqg1s0nq4 s","or.r&","orígenes*","orbison b","orchestra p+",
"orden t","ordinary c","oreja jD","origen 1","original&","originalidadG<&","orleans#","oro]XA>","orquesta p+","ortodoxoP",
"ortodoxosC","ory l","osZ","os6ib1mdsbu<","oscar lF","oscura e","oscuras b","oscuro eZ","oscuros k","ostentación%",
"otisE1W","otorgóP","otorgados`","otra uJ8$S","otras vuqmkWs%","otro_SA+)","otros vutsrqponmlkjihgfedca`_^]\\[ZYXWVUTSQPONMLKJIHGFDCBA@?>=<;:98754320/.-*)('&%$#bE61,+R","otvh5cv9z1a&","out^5,","over aX",
"overture i","ovwk77jrww a","owgg5fx7bxyR","own 9","oy9ffrzxz0o.","oyente 2","p9mui4j8kh8 1","pa>","páC","página ge",
"pájaros pM","pálido b","pánico p","pérdidaJ","pócima<","póker p","póstumaW","póstumas b","póstumoW","pabloD",
"padre 3rP","pahxnwxnjm8S","painW;","pais dTE","paisleyZ","palabrasG","palacios q","palmarés g","paloma(","palpable[",
"panal@","panchosH","pangeS","panorama uj\\UTJDC('","panteraT","púber nP","públicoVM;:3'","públicos;3&","púrpuraZ","para vusrqnihgdbZSRQOKD@?<;974+)k_PNIGFBA810,j^ML>*3pTE",
"paró 3","paradógicamenteP","paradise c","parado td]","paradojaS","parecía kF?)","parecido=","pareciendoW","pared 8","parkZ",
"parroquiaG","partículares a","parte rqlf`\\POMJIFE92/[,)","partesF+Y","participacionesA","participar*","particular vebWM4.')","partir rA","partonA,","pasó p3o",
"pasaba rpJ","pasaban]","pasadoP8","pasando$","pasarP","pasarán g0","pasión(&k0","pasionesH","paso qkaT>0]S$","paternaJ",
"paul rpc<X","pavarotti v","pdzcqbgcs74F","pearlsZ","peces(","peculiaridades 6","pegadizas$","pegadizos^/","peggy c","película jI,",
"películas]$","penaNJ","penetrabaI","penetrar 1","pensando>","pensarG","pepeC","pequeñaT","período^","percató+",
"percepción(","percusión qP","percusionista 6","perdóname 0","perdedor p","perderD=:","perdidasT","perdidoYRM","perdudarán)","perdura a",
"perdurará 0","perfección t","perfeccionándose p","perfeccionarG","perfectamente cX","perfecto c9,*%","performingB","periodos:)","permanecerZQ","permanecerá 4",
"permanecerán]","permaneció m","permanecido o","permaneciendoR","permiten$","permitióD","permitido oe","permitieron p","permitir n","permitirse:",
"pero vtrqonlkid`_\\WUTKIFEA>;)(&$sZSPC?%3,","perpetuoH","perro\\","persona`PJ","personajeT","personal kUM:","personalesP9","personalidad]2","personasA7","pertenecía fW",
"perteneciente sYSJ42","pesadillaW","pesar_P","pese d[ZUQO.","pettigrew 3","pez 8","pfgbtb 1","pflI","phil a$","philadelphia eI+",
"philarmonia p","philip 6","pianistaVE72-","pianoE2(-","pido(","piece 3","pieces<","piel u\\.","piensaH","pienso u",
"pies d","piezas o5","pilarP","pilares d","pinkY","pinochet h","pintorJ","pintura p","pioneroP","pioneros eb^I/",
"pistas nY","pistoletazoW","pitifulW","pjfoqxjgbrs l","plácidoA","plásticasM","placerS","plagadaP7","planeta/,","planta u",
"plasmadosE","plasmar)","plastic 4","platero 8","platinoQA?>","play+","plays#","plaza j","plena e","plenamenteY",
"pleno]C<,","pmsqspmtu98E","pmwjk c","poéticasM","pobreQ","pocas gdWQ","poco_^Z3n'","pocosXUN50e","podía?:","podían 6",
"podemos oW=;,&","poder`L21+","poderíoT","poderosa kQ1","poderosasU","poderoso c[P*","poderososS'","podido o","podría raXRME@","poesíaM7(@",
"poetaJ)","pojt93xbs]","police h","polifacética d","polifacéticasK","polifacéticoN","polpularidadR","ponerQP","pop rnifdca\\ZVTNMKFD;:9542.-'&mjO3)_R","popular sh,",
"populares%","popularidad o`MA;90,","popularizóJI","popularizaron$","por jhf`_ZYXWVUTLKGFECA@:621-+%snlkQP?8540/*#omeM><;('&$rpc]Jt=3)S,","poros)","porqueP","portal vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","portetM","portuguésA",
"poseeX","poseedor peI>%","poseedoraV","poseedorasF)","poseer gUF5","poseerlo k","posibilidad 3","posibleK:","positiva 6","positivismo<",
"poso/","posteriores k?","posteriormenteV","powell p","powerZ","ppjnku 9","pqynedi/","prácticamente r5/","practice+","príncipe k",
"preach+","precariedadP","precioN","precursor+","predestinadaQ","predilectos&","prefieroM","preludio p","premiado oI","premio tkO?>%",
"premios trlhg^][QKEBA;:-,`'","prenderse s","preparándonosG","presaE","presenta u","presentándonos u","presentó 5","presentabaO","presentado 0","presentaraE",
"presley b","pretenda 5","pretendía?","pretenderZ","pretty b","pride r","primer mb\\OK3/,p>","primera dY,*","primeras<","primero-",
"primeros a]RJ","primo_)","prince dFCZ","principal 6","principalmente m/","principeP","principio^SP","principios jiZI","prisoner 1","privilegiadasQ",
"pro u8","problemaC","problemas lj^Q;)","procesoM","prodigio g","prodigiosa(","producción j;rp","produccionesB","produceSp","producido_5",
"producirse k","productor pgWSQLA10$","productora dE","profesional]","profunda]?%+","profundamente\\","profundas qC","profundidad q:","profundidadesV","profundoI%W",
"progresivo qiYG","progreso`","prolíficasZ","prometedor p","pronto n]","propia tlkS+","propiedad vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","propio trSL$","propios&","proponeN",
"proporcionó o^","proporcionaban 6","protestaJ","provecho;","provenienteWQ","provocación]","provocador 74","proyecciónUF","proyectosT","prueba.",
"psíquicos u","psicodelia kY6","psychiatriqueT","publicó 5","publicaciónW)","publicados[","publicistasA","pucjagfgdpm q","pudíeramosP","pudiera n",
"pudieras;","pudoP","pueblo j","puede geQMA)","pueden k","puedoR","puerilE?","puerta q(","puertas/","puertoriqueño>",
"puertorriqueñoN","puffQ","pulmón)","pulmonar p","punta 8","punto rjbXQPD,p","puntos%","puntual k","punzante h","pura 6",
"purezaB)","purgatorioT","puristas&","puro j3","purpureZ","push vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","puso uE","put?","pvsc5vdrasw q","pxif9e0465eF",
"pxsgocwifag 4","py5lontuw2a@","pyk6mdcidd0U","pytxtjm 9","pzxaqijiiaa`","q0nnpzt u","q0nviqoeiawC","q38z(","q6ibmvzopfcT","q80M",
"q9rqpaD","qbgtsmyftrg&","qde5nmy7wtu 2","qecaj62vvec'","qf6xu70o73c 9","qgxbbd5bve4#","qjzjhl-","qk h","qkyqntf11eg m","qmvgszwpqT",
"qozm 1","qrdzjj7 v","qskdxzkz 2","qtxlcsvkkvy/","quéN>o]","quédateL","que hb\\LGF8'%#uoea_[ZVUQHB?>41-&qlifKC@7$rgcRI520/.(smjd`^XTON<:9+vtnMDA3,*pW;6E=k)]JSP","quedan qlE","quedar k","quedara i",
"quedaría gN","quedarse 6","quedes d","queen$[","queenâ€™s t","quería j","querer<","queridaJ","querrás v","quién uSNEB%",
"quien hdQMD","quienes q","quieres jG0","quiero uqkj`SGU","quietest i","quijoteA","quilates q","quimiM","quinto r*","quiso p",
"quitóP","quizás rk(H","qwzfgxtuoro:","qxiun1lx7osU","qzg6kwekg:","qzte-","r2rsp43rmg 6","r8pmsmtxy5s u","récord o0","régimenJ",
"raamI","rabia q","radio a^[3\\","rafael(","ragcf0sawjyR","raging&","raices qC?","rainZ","rainy l","ramasM",
"ramilleteE","randb n","rango tTO","raphael]","rapid^","rasgado 1","raspberryZ","rasputin/","rítmica 6","rítmico nj",
"rawlsI","ray c","reP&","real um","realidad o&","realizó b","realizaciónP","realizando]","reasons 6","rebelde j+",
"rebosan<","rebosantes q","rechazoP","recogen 6","recompensado t","recompensados:","reconocidaT","reconocido`","reconociese=","reconocimiento ohM*'",
"reconocimientos[TSK=,'","recopiladosW","recordA","recordadas r","recordar jbS","recordaréis&","recordaremos)","recordarteT","recordsOE3","recorriendo u",
"recreo)","recubierta me","recuerdo 34","recuperarse p","red 3e","reddingE1W","referencia raYQ","referente pU2","referimosK","refinado 5",
"reflejabaY","reflejaban 9","reflejarlo c","reflejarse 2","reflexiónP","reforzadas q","regalaU","regalado i","regalaron l","reggae vC",
"registered vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","registradoS","registro b","reina dcQ","reinoB","reinventarse k]","reinvindicación o@","reinvindicativasM","relación u","relaciones r",
"relataJ","relataba u","relevancia n","religion^","relojH","remake$","remoA","renacimiento p","renal p","renunciar 9",
"repentina 3","repertorioI","reportó h","representantes`","reproductor 5","resistir q","resistiré*","resistirseB$","respectW","respectivos vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"respetado)","respetados 4","respirarM","resto]","resultado cPE","resultadosT","resurgido j","retirada;","retiro-","retomarP",
"retornóT","retorno kR$","retraidos$","revolución\\P","revolucionaron j","revulsivo nEC","rey`N","rhapsody[","rhlS","rhythmV",
"rica q2","ricasC","richard l","richieF","rick i1","rico t`5_","ricosM:","ride l","ridgeley;","riendaM",
"riendas n","right?e","ring/","riqueza 6)","ritmo vrnj_ZNL?9","ritmos_@>;16/","river-","rivers/","rjlsiassuisP","rl 6",
"rnb cVQI3&","road p","robar+","robertaE","roberto`S","robin,","rock vtpnkib^[ZYRG>86520%r\\TM-'qjL94m*","rockeros*","rocket 7","rodeaba)",
"rodeado k","rodearlos k","rodríguez q","rodriguez j","roger i[X","rogersZ,","rojo*","roll trb92-j*","rolling bC$","románticas sb",
"románticoPH","romantic pfR","romanticismo`H+","romeo@","romero v","rompiendoP","ronca t","ronstadt#","room 5","rosa@q",
"rosasJD","rosenvingeJ","rosita'","rossFA","rot j","rotaW","rotundoTR","roxyXa","roy b","royce d",
"rrbfqecpj3aZ","rrvtagpuzze j","rs(","rsecdio9dh0 p","rudeza#","ruiz p","rumbaC","rumor q","rumours 9","run 1",
"running m","rvtvssztu50#","rxgg9izhvakJ","ry0wxgsxdee[","ryan p","rzq1vkbqyfyI","s1piz1olyps?","s1wfoqxkdq8>","s3fbgocjlpiJ","s3q80mk7bxe n",
"s7jtu$","síE0","séK","séptimoS","sólamenteW","sólas h","sólo oe`RQA@=<60*(uWG?$","sólos 0","sabía q","sabe uc]",
"saberE","sabido vL@$(","sabiendoX","sabina j","saborXH3","sacar;","sad 7","sade c","sagrado n","saigon-",
"sailboatB","salónI2-%t","salida cSP","salido$","salir vnQ'","salmonelosis p","salsaCN","salta j","salto n;'","salud)",
"sam kP","samba o>","símboloZ","same a","sanDA)","sanaciónT","sanada k","sananda k","sanar<","sangre m#",
"santiago\\","santos@","sanz dN","satisfyX","saturday,","saxo f","saxofonista t","say g7F","sb7u5xvnI","scene a",
"school iB","scmj8J","scottE","se vtsrqonmligfba^[YXUONIGFA@?=<;:9531-$#eWSQ6,+&pjECkPMZT)","seña c\\KHC","señorA","sean$","seasons 2","sebas'","secasM",
"sección vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","secretariaS","sectaP","seda)","sedosaI","sedosas 6","seducciónZI","seductora+","seeI+","seems 7",
"seguidamente)","seguido$","seguir pnj]P1$","segunda kY","segundo 5)","segundosJ","seguraD","seguro dS","seis 9","selloP",
"semanas mRp","semejante t","semilla\\:","sencillas$","sencillez`","sencillo mO","sencillosO'","sendaPD","sensacionales k","sensibilidad vuhMB@97)",
"sensible ge7#","sensibles b","sensual c+(#%","sensualidad cP/","sentían 1","sentadoW","sentidas 6","sentidos`_+M","sentimental,)","sentimentalmente u(",
"sentimientoVP%#","sentimientos eWUJHF)(","sentir tdM0","sentirme#","senza v","separación 5","separado j","separara i","separarme_","separaron 3",
"september 6","septiembre 0","ser njdcb`XIDB=20.*oA","sera>","será&","seránT","sería*","serían(","seres r","serie lW&",
"seriesE","serpiente%","sesenta 3","sesto 0","set h","seven k9","sex;p","sexoP;%","sexualP","sexy vZ*",
"shake=n","shakira d","shape h","she bg","sherpa*","shineEY3","shining 6","short f","should,","shoulderX",
"show[","showman%","si keNE=<3+(H","sido dKA3/","siempre qo]\\DC=<60%$k4p&c","siendo tdbUQPMB?30+(]","siente k","sientoS","sieteTD","siglo tnd`][ZPI$5",
"sign k","significa*","significó@","significar)","significara l","sigo k","sigue tM3,A","siguen gU5,","siguió k","silbidoO",
"silencioT","simón\\","simbolizanH","simone c","simpatía&","simplemente oj]","simples l","simply 3e","simplyred e","sin rokXSPM@=:/*(&cU9J",
"sinatraCA0","sinfónico iYG","sing l6","single^3","singlesW","sinoA*","sintetizador a,","sintonía&","sinuoso#","sir 7g",
"sirvió+","sister k","sitio)","sitiosRD","sittinW","sj$","sjmmaigigbg l","sk)","skyY","skyway 5",
"slave a","slowlyJ","smooth 3c","snvnvlay\\","so b:7","soñaban n","sobranN","sobre unmgb`_\\KI>7reQ'","sobredosisZ","sobrenombre t",
"sobresalirQ","sobretodo+","sobrevivir)","sobreviviréT","sobreviviremosS","sobrinoC","social 2P","sociales u","sociedadA","sofisticado 5",
"sol u","solapa m","solas h","soldadito 8","solista 965","solitario nhVPF;1)#5","soloKG","soltura n&","sombra*","sombrasP",
"somebody h[,","something=e","son tsponlkihgfdcba_]\\ZYVUTSRQPONLKJIHGEB@?>;:9874210/-+)'&%#vqe`^[XWMFDCA<653.,*(um=$rj","sonandoD,","sonar 53","song i76","songs 7","sonido trmieOIH:953.*YRL=<+$","sonidos lcaZD<81/\\OB6=","sonora v6,",
"sonorasE3)","sonoridadM","sonyT","sopaL","soplarM","sordomuda d","sorpredentemente,","sorprendernos 1","sorprendiéndonos tU","sorry 7",
"sosegado%","sou`","soul ngZLI?=<64#tecVQPE>.+omkW1X:3%","soulmanP","soy`u]A","space=4","spandau f","speak o","spector$","spell?",
"spencer c","spice o","spirito v","squeezeX","sr q","sr2yoB","st0ffuqk3ou`","stand 1","standing 7","star 6",
"stars e","start-","started e","statonE1","stayEk%","stayin,","steely 5","stepE","steve fW","steviePA=<9g",
"steviewonder g","still<72r","sting vh","stivel jL","stone b$?6","stonesC","stop[#W9","story f","stranger i","stream,",
"streetI","streets rm","streisand,","strongW","stuart c","stuck.F","su qlihg`[VH@=:/srme_LC;610(ujf\\TSQONKIEDB>982.'db^RMJGFA73-&$#vncYXU?<,+%]tZ5k4oW)Pp","suaveK9","suaves l8","suavizaciónL",
"sube u","sucedido q","sucias*","sucumbir;","sudafrica d","sudamericana h","sueño^@","sueciaR","suecos$","sueltaM",
"suerte d)_","suficienteR","sugerente c/5","suicidaron k","sujetaba 3","suma 6","sumamos<+","sumarJ7.*","sumarle t","sumergasV",
"sumieron;","sumne h","sunV:7","sunny/","sunrise e","sunshine g","super j?","superación)","superado o)","superarJ",
"superconocida 6","superfluasB","superior(","superlópez j","superstar l0","superstition g","supertramp i","superviviente 1","supo:","supuso[)",
"sureñoL1%","sureñosM","surgían b","surgen q","surgió k5'","surgido q$","surgieron mfQ","surrealistasM","sus vusqpmlig`_\\[ZXWSOKIHFCB>984210-(tronkjfeaVURMLJGEA<65+*'&%dcb^]TND@73.#hQ?=:/,YP;$)","suspender d",
"sustituir,","susurro%","suz4D","swbgjzf3mb0 m","sweetO2","sweetest c","swing o","sxjialnmpnkE","sydY","t0dghhb6ni 1",
"t0on9tbnkd8\\","t2nujwmmhkgT","t3w3izq5sdm m","t7bkgteqgsm`","t8Z","tí u","tándemI97","técnicaV","término^","tómameS",
"ta42xu2uxla/","taboo c","tacones p","take i#","takes$","takin m","tal rk","talón d","talante 7","talento hZXQNFE?4%pW",
"talentosE:","tallaX","también sdZXC?43%&","tambienI6","tammiP","tan nmfbVRQKE?>632pcW0&","tango 9","tanta 0","tantas)","tanto uonkSRNG&",
"tú ud80sKHGS","tapestry 2","típica h","tarde n5","tarqueL","tatareadoS","tatuó,","título 5","taupin 7","taylor[",
"tcqT","tdh1iwb33k p","te vm`XVKJ><1)'soSNdU","tearsV","technologyB","teclados q","tecnoR","tejado 8","telónB","tele q",
"televisión l","tell#","tema upe^R:","temática r","temas oldcbVTSRF932(&p?;,","temperamento'","temptedX","ten*","tenía r?","tendencias 4",
"tendernessW","tendido u","tenemos t","tener k9*","tengoN>","tenido n","teniendo]9","tenor b6","tensiones 9","tentarH",
"tequila j","tercer kf'","terence 3k","ternura lJB)","terrellP","tesoros)","textosM","tez e","than a,","that 76",
"thatâ€™sW","the tkfaXVCBA<95/,$lhgecZE;-o[P1riWF:mb^Y#7n+6","them hYB","theme vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,*)('&%$#+","thereOI<n","theseW","they hl7","thing v<1eI","this a:&","thomas h",
"thriller o","through fP","ti u_>","tiñóZ","ticket l","tiempo qpkYSO8$M","tiempos kSR9,-","tienda k","tiene mkcXNdG","tienen 8",
"tiernoH","tierraL+","tigre p","tildandoX","tildar e","tim o","timbre vdXK1#","time^","times#","tino p",
"tinte e","tintes^","tipo`","tirados p","tired%","titubeantesP","titulada vI","titulado k^>,'","tiza\\","tkdmiyrmbik#",
"tkulh9otlz4(","tmvapchumpeV","to gfbaYEA?=2,nk[WPI;73oml","tocan e","tocandoG","tocar kE","tocarte\\","toda c`\\XWSP:821,(%","todas ut53=","todavía kgWJ",
"todo vpnlge^\\QNFEC>=;5/*('%utmb`_SKJIHGA@70roP","todos vurqponmljhgfedcba`^]\\[ZYXWVUTQPONMLKJIHGFECB@?>=<;:8754210/.+*('%$#tsi_SRD963,)&kA-","together&%","tok v","told tE","tom v","tomando n","tomorrow 2","tonalidadX","tone o",
"tono b","tonto\\","tony f","too=,W;2","top*","topamos<","toque vtke-","toquesM5","torrojaR","tortura d",
"tour#","tov22ntcmc4O","toxasfkzzmq t","tozzi s","tráfico qA","trágico p","trabajo 39","trabajos utjiE9'k)","trademark vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","tradición 1",
"tradicional t9","tragedyN,","train km","tranceG","trans 5","transcurría k","transcurreJ","transfer o","transformaT#","transformación n",
"transformado n","transformaron k","transgresor 4","transmiteNJ","transmiten j","transmitir tX","transmitirnos>","trío,","trapecioM","tras udb_TRPJIDBA54*ZU3",
"trata r","tratabaP?","través utscY)'#","travesM,","trayectoria[PJ7-%","tree r","trent 3k","tres l_]YTJH","trianaMGq","trickle o",
"trioH","triste`","tristemente/;","tristeza?9)","triunfaN","triunfarTS","triunfo d$","troncoso q","trouble+","true f",
"truhanA","trulyF","truncada)p","truncadoUA","trust-","truthE","tryW;","tuZ@)qJ","tuktqs2zety_","turn:",
"tusKD","tutelados(","tuvieron lL","tuvo fbTP+","tv&","tvf8gyhbir0 2","tvnymwpdZ","twilight o","txcdtumlqji r","txoo9t1jn5y 1",
"u2Qr","u2rjyqqp4nqA","u9ba6ffgmjiP","ua vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","uaqslwjxiwc`","ucgd9dt12c0 9","udj(","udkbzka9l4s r","udwpprra6l8\\","uezagfk9o8q p",
"ufupu2wuy>","ugiyrkfdhq0+","uit3dx4an9cO","ujwqinpt4qiK","ulster t","umberto s","un vsjfYVNLKIF?2(#igdcbZXRC>=:6/.+uole_^[WQOMG<9750-,*&qnh`]US@)rTEA%$JHmktP;3p","una uthfbaYQMKGF?<94/-'&srnmlge_[ZEDB=8310$vpc\\XTROLA;76,*`WVUSI52+qk)(%JP","unía:","unas qkTSQHF",
"uneR","unfzfe8f9ni$","unicef d","unida(","unido uKB","unidos o]S","unir&","unirse*","universal u`A","universales v",
"universalizando m","universidad t","universo'","unlimited+","uno vusqolked`YXWUSRIDA8642/-,('&%mgP:9","unos qlSLB6/'P","unpmoab4y8uW","upPEo+","ups4ylw642s 0","uptown-",
"uqyy4nglewu?","ur96bakqg28C","urangaS","uranio]","uribarriS","usY$","usu6tcbmou0%","uunt4*","uusbx3pptxy v","uvi p",
"uvqyambgP","uw90wihrvzaS","uwlnpooY","uxvcr22rm 3","uyfm 7","uz83qy50a e","v4eurtgmp 1","v6nvnkfyy24+","va dNBA","válido v",
"vía 1","vacio k,","vídeo vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","vajx8edq)","valíaN","valióN","valli,","valorado:","valorar b","vamos_",
"vampires k","van j_D*t","vandellasP","vanguardia p","vanguardista 4","variable t","varias me]TQKE<:-(p","varios tpm^QPLIFB;82","vítor u","veNA2l",
"veían 2","veces q]UB","vegaC_)","vehículos+","veinteañeraE","velloJ","venH","vena pe","venía m","venas mV#",
"vendaval l","vendedorS","vendedoresA","vender]YR=;","vendida,","vendidas^'","vendido kRKA,","vendidos r`920","veneno\\","venideros n",
"venta f","ventas mdTQ*","venteC","ver\\WL","veránT","veranoD'","verdaderamenteZ","verdaderoZ+","vergelH","verleW",
"versátil&","versátilesK","versión(","versiones sS?:","vertiginosaA","vez usrk[TS81.,)%","vffbqdv2clcT","viñaA","vióUA)p","viaje_7",
"vibrante%","vibrantes 6","vibrar@","vibrato+","victim 1","victor u(","victoria)","vida vrplcWUSNMJIH>86510,+*PA","vidas]3","video p",
"videoclips=","videomúsica vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","videomusica vutsrqponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","videos vutsrqponmlkjihgfedcba`_^]\\[ZYXVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#W","vie#","viejas k","viejoC1","viejos$","viento^","vigor 3",
"vigorosa[*","vii8phlo2pkT","vinilos$","vinoV","violines+","virtual=$","virtuosa&","virtuoso_>:&","visa@","visadoS",
"visión r","visionO","visionario tP","visionsO","vista,","vistosidad/","visualizarP","vital=","vitalidad_6","viu4iwE",
"viva]5*","vivas g","vive 8","vives d","vivió/","vivir pNA0","vivoI4/","vjk40bq8aasN","vjrczoyxa98.","vkdqyo g",
"vl8nujdtlia 3","vocal pomkXTQ31%#VO","vocales odTQD:S","vocalese o","vocalista 9'#D","vocalistasWV</","voces usrXLKHE<3('US$","volT","volóV","volcán e%",
"volcaseA","volo v","voluntad d","volviendo,","volvieran 9","vos'","voz vtmlfedcba`VUONMKIE?>;9641.'#qkPB0(%]XW&+","vpuW","vqx2xn7ti l","vrr4f2mX",
"vt9t3q,","vu d","vuelo(","vuelvo j","vuplA","vvy0zvqcl7e 5","vxogqn1a7be a","vyltbsyvjbe_","waka d","walker_",
"wallY","walter 5","wannaP","want[O;n","warwick,","water m","waterloo$","watersX&","way i9+6","ways r",
"wbe1qlvygqs\\","wcwhzc8s2i c","wdnxyjkzq80<","we^[F-&l3","weather 5","weaver,","web ge","well k","wembley&","wereBY",
"wham;","what iB5.+rmP%","when fI=","whenever d","where r3","wherever d","whisper;","white 6+","whitesnake*","who k",
"why t7","wiiqtwuiv54N","wild t","wildcard k","will[2","willieA","wind 6","window vutsrqponmlkjihgfedcba`_^]\\[ZYXWUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#V","winner$","wire#",
"wishIY","wishing k","with?7+r","withoutQOr","wk5wlq4pbfgY","wkqbtldfya0]","wlsbl0yuzcc d","wm7 9","wojzo02tmckK","woman@bV2,",
"won.","wonderPA=<g","wonderland 6","wonders 9","wordT7","world^FA56","worry<","would 3","wrong?","wsmryfsy 6",
"wsncZ","wvsa2ceiq7uR","wvvxcwp3v8y 8","wwb779bdmy4*","www ge","wxapadhj0r8_","wxhsb7pdpbi 6","wyclef d","wzldhf1jpiwG","wzrxc68gnjqW",
"x25f3B","x4p0yU","x6qzn9xiuoeP","x6vn3zkekf4H","xabiD","xejlohdbvee$","xers7g3T","xfrguyw1v8s$","xfudbqcplj4 4","xh r",
"xi2egyzo2pw t","xm gD","xpqqju7u5yc,","xra+","xv1dk9tshio g","xw1fxl3s7bk n","xx tn`[ZI$5","xxb0nzhvj5m&","xxi]","xy^",
"xzP","xzologgfwp0@","y3ywicffoj4 9","y7dgdrp3pmsP","ya mi^GB3*)(n","yc(","yd3tq5f9gfkP","yd8dcgplp/","ydd s","yeah a",
"yearsX","yesterday l","yfqqz6tu3fu j","ygu1bc4c4D","yi2ax14erbkA","yn7hxmzxqv8 f","ynihshyaig0 k","yo sjHE`]","yoaoX","yopqnpbl i",
"york h3o","you taQPNA<9rlhfebWOB=.,#g?31nkYIF2%+","youâ€™re+","young=41","your cI;9nk:7,+1","yoursE","youtubeVE<vutsrqonmljihgfedcba`_^]\\[XWUQONMLKJHGFCBA@?>;:87654210.-,+*)'&%$pkZYTSRPID=93/(#","yqk`","yxio6nrgva4 o","yxqviqx6gmyO",
"z0qw9p 7","z1k67uaa h","z7j1uogi02a 7","za8he50xjee k","zalssqlxxyiD","zapateroM","zbnjo88kup8 4","zdbo%","zencru8 l","zenitR",
"zf4kzl9M","zh3y9rwmtri n","zhqpm-","zhwvbirqd2s 7","zitrwccrqms o","zm p","znbj4ev;","znlfuQ","znsxeeveH","zonaN",
"zone o","zpdqjni4ohuQ","ztcu7mctuts e","zubiagaS","zucchero v","zxspivc2gnw v","zzkC");
var FN=Fs.length, WN=Ws.length, BW=window.opener;
var AR=new Array(FN), AI=new Array(FN), M2=FN>1563;
function Let(c){return c>='a'&&c<='z'||c>='0'&&c<='9'||c>'';}
function Dig(s){
 for(var i=0;i<s.length;++i){
	var c=s.charAt(i);
	if(c>='0'&&c<='9') return 0;
 }
 return 1;
}
function C(l){
 location.href=l;
}
function AW(s){
 var i,n;
 for(i=0;Let(s.charAt(i));++i);
 if(s.charAt(i)==' ') ++i;
 for(var m=1;i<s.length;){
	n=s.charCodeAt(i++)-35;
	if(n<0) n=(n+20)*92+s.charCodeAt(i++)-35;
	else if(M2) n=n*92+s.charCodeAt(i++)-35;
	AI[n]+=m++;
 }
}
function MK(s,n){
 var i;
 for(i=0;i<FN;++i) AI[i]=0;
 s=s.replace(/\*/g,'[^ ]*');
 s=s.replace(/\?/g,'[^ ]');
 s = '^'+s;
 for(i=0;i<WN;++i) if(Ws[i].search(s)==0) AW(Ws[i]);
 for(i=0;i<FN;++i) if(n) AR[i]*=AI[i]; else AR[i]=AI[i];
}
function MT(){
 var c,i,n,t="",ss="",s=document.forms[0].s.value.toLowerCase()+' ';
 for(i=0;i<FN;++i) AR[i]=M;
 for(i=n=0;i<s.length;++i){
	c=s.charAt(i);
	ss+=(c=='<')?"&lt;":c;
	if(Let(c)||c=='*'||c=='?') t+=c;
	else {
		if(t.length>L&&(D||Dig(t))) MK(t,n++);
		t="";
	}
 }
 t='La búsqueda para "<b> '+ss+'</b>".<p>\n';
 for(n=0;;++n){
	var m=0,im=-1;
	for(i=0;i<FN;++i) if(AR[i]>m) m=AR[im=i];
	if(im<0){
		if(n==0) t+="<div align=center><p><b>No hay resultados.</b></div><p>\n";
		break;
	}
	AR[im]=0;
	t+=("<b>"+(n+1)+".</b> <a href='javascript:C(\""+Fs[im].fn+"\")'>"+Fs[im].ft+"</a><br>\n"+Fs[im].fd+"<p>\n");
 }
 return t;
}
function NS(){
 if(document.getElementById) document.getElementById('txt').innerHTML=MT();
 else document.forms[0].submit();
 return false;
}
function SS(){
 if(location.search){
	var o="€,??????????????????????????????????????????????????????";
	var t="";
	for(var i=3; i<location.search.length; t+=c) {
		var c=location.search.charAt(i++);
		if(c=='+') c=' ';
		if(c=='%') {
			var v=parseInt(location.search.substring(i,i+2),16);
			if(v<128) c=String.fromCharCode(v);
			else c=o.charAt(v-128);
			i+=2;
		}
	}
	document.forms[0].s.value=t;
 }
}
//-->