<!--
function f(fn,ft,fd){
 this.fn=fn;
 this.ft=ft;
 this.fd=fd;
}
var Fs=new Array (
new f("//videos.videomusica.es/Aaron.Neville.html","Videomúsica sección videos, Aaron Neville","Videomúsica, información y videos. Aaron Neville"),new f("//videos.videomusica.es/Abba.html","Videomúsica sección videos, Abba","Videomúsica, información y videos. Abba"),new f("//videos.videomusica.es/Al.Jarreau.html","Videomúsica sección videos, Al Jarreau","Videomúsica, información y videos. Al Jarreau"),new f("//videos.videomusica.es/Amaral.html","Videomúsica sección videos, Amaral","Videomúsica, información y videos. Amaral"),new f("//videos.videomusica.es/Ana.Belen.html","Videomúsica sección videos, Ana Belén","Videomúsica, información y videos. Ana Belén"),new f("//videos.videomusica.es/Antonio.Vega.html","Videomúsica sección videos, Antonio Vega","Videomúsica, información y videos. Antonio Vega"),new f("//videos.videomusica.es/Baron.Rojo.html","Videomúsica sección videos, Barón Rojo","Videomúsica, información y videos. Barón Rojo"),new f("//videos.videomusica.es/Bee.Gees.html","Videomúsica sección videos, Bee Gees","Videomúsica, información y videos. Bee Gees"),new f("//videos.videomusica.es/Billy.Joel.html","Videomúsica sección videos, Billy Joel","Videomúsica, información y videos. Billy Joel"),new f("//videos.videomusica.es/Bobby.Caldwell.html","Videomúsica sección videos, Bobby Caldwell","Videomúsica, información y videos. Bobby Caldwell"),
new f("//videos.videomusica.es/Boney.M.html","Videomúsica sección videos, Boney M","Videomúsica, información y videos. Boney M"),new f("//videos.videomusica.es/Camilo.Sesto.html","Videomúsica sección videos, Camilo Sesto","Videomúsica, información y videos. Camilo Sesto"),new f("//videos.videomusica.es/Carole.King.html","Videomúsica sección videos, Carole King","Videomúsica, información y videos. Carole King"),new f("//videos.videomusica.es/Charles.Eddie.html","Videomúsica sección videos, Charles & Eddie","Videomúsica, información y videos. Charles & Eddie"),new f("//videos.videomusica.es/David.Bowie.html","Videomúsica, David Bowie","Videomúsica, información y videos. David Bowie"),new f("//videos.videomusica.es/Donald.Fagen.html","Videomúsica sección videos, Donald Fagen","Videomúsica, información y videos. Donald Fagen"),new f("//videos.videomusica.es/Earth.Wind.Fire.html","Videomúsica sección videos, Earth Wind & Fire","Videomúsica, información y videos. Earth Wind & Fire"),new f("//videos.videomusica.es/Elton.John.html","Videomúsica sección videos, Elton John","Videomúsica, información y videos. Elton John"),new f("//videos.videomusica.es/Fito.Fitipaldis.html","Videomúsica sección videos, Fito & Fitipaldis","Videomúsica, información y videos. Fito & Fitipaldis"),new f("//videos.videomusica.es/Fleetwood.Mac.html","Videomúsica sección videos, Fleetwood Mac","Videomúsica, información y videos. Fleetwood Mac"),
new f("//videos.videomusica.es/George.Benson.html","Videomúsica sección videos, George Benson","Videomúsica, información y videos. George Benson"),new f("//videos.videomusica.es/George.Michael.html","Videomúsica sección videos, George Michael","Videomúsica, información y videos. George Michael"),new f("//videos.videomusica.es/Incognito.html","Videomúsica sección videos, Incognito","Videomúsica, información y videos. Incognito"),new f("//videos.videomusica.es/Jamiroquai.html","Videomúsica sección videos, Jamiroquai","Videomúsica, información y videos. Jamiroquai"),new f("//videos.videomusica.es/Jose.Feliciano.html","Videomúsica sección videos, José Feliciano","Videomúsica, información y videos. José Feliciano"),new f("//videos.videomusica.es/Joss.Stone.html","Videomúsica sección videos, Joss Stone","Videomúsica, información y videos. Joss Stone"),new f("//videos.videomusica.es/Juan.Luis.Guerra.html","Videomúsica sección videos, Juan Luis Guerra","Videomúsica, información y videos. Juan Luis Guerra"),new f("//videos.videomusica.es/Katie.Melua.html","Videomúsica sección videos, Katie Melua","Videomúsica, información y videos. Katie Melua"),new f("//videos.videomusica.es/Ketama.html","Videomúsica sección videos, Ketama","Videomúsica, información y videos. Ketama"),new f("//videos.videomusica.es/La.Oreja.De.Van.Gogh.html","Videomúsica sección videos, La Oreja de Van Gogh","Videomúsica, información y videos. La Oreja de Van Gogh"),
new f("//videos.videomusica.es/Laura.Izibor.html","Videomúsica sección videos, Laura Izibor","Videomúsica, información y videos. Laura Izibor"),new f("//videos.videomusica.es/Lionel.Richie.html","Videomúsica sección videos, Lionel Richie","Videomúsica, información y videos. Lionel Richie"),new f("//videos.videomusica.es/Los.Modulos.html","Videomúsica sección videos, Los Módulos","Videomúsica, información y videos. Los Módulos"),new f("//videos.videomusica.es/Los.Panchos.html","Videomúsica sección videos, Los Panchos","Videomúsica, información y videos. Los Panchos"),new f("//videos.videomusica.es/Lou.Rawls.html","Videomúsica sección videos, Lou Rawls","Videomúsica, información y videos. Lou Rawls"),new f("//videos.videomusica.es/Luis.Eduardo.Aute.html","Videomúsica sección videos, Luis Eduardo Aute","Videomúsica, información y videos. Luis Eduardo Aute"),new f("//videos.videomusica.es/Luis.Miguel.html","Videomúsica sección videos, Luis Miguel","Videomúsica, información y videos. Luis Miguel"),new f("//videos.videomusica.es/M-Clan.html","Videomúsica sección videos, M-Clan","Videomúsica, información y videos. M-Clan"),new f("//videos.videomusica.es/Manolo.Garcia.html","Videomúsica sección videos, Manolo García","Videomúsica, información y videos. Manolo García"),new f("//videos.videomusica.es/Marc.Anthony.html","Videomúsica sección videos, Marc Anthony","Videomúsica, información y videos. Marc Anthony"),
new f("//videos.videomusica.es/Marvin.Gaye.html","Videomúsica sección videos, Marvin Gaye","Videomúsica, información y videos. Marvin Gaye"),new f("//videos.videomusica.es/Mecano.html","Videomúsica sección videos, Mecano","Videomúsica, información y videos. Mecano"),new f("//videos.videomusica.es/Mocedades.html","Videomúsica sección videos, Mocedades","Videomúsica, información y videos. Mocedades"),new f("//videos.videomusica.es/Monica.Naranjo.html","Videomúsica sección videos, Mónica Naranjo","Videomúsica, información y videos. Mónica Naranjo"),new f("//videos.videomusica.es/Monitor.html","Monitor.html",""),new f("//videos.videomusica.es/Oleta.Adams.html","Videomúsica sección videos, Oleta Adams","Videomúsica, información y videos. Oleta Adams"),new f("//videos.videomusica.es/Otis.Redding.html","Videomúsica sección videos, Otis Redding","Videomúsica, información y videos. Otis Redding"),new f("//videos.videomusica.es/Paul.Carrack.html","Videomúsica sección videos, Paul Carrack","Videomúsica, información y videos. Paul Carrack"),new f("//videos.videomusica.es/Pink.Floyd.html","Videomúsica sección videos, Pink Floyd","Videomúsica, información y videos. Pink Floyd"),new f("//videos.videomusica.es/Prince.html","Videomúsica sección videos, Prince","Videomúsica, información y videos. Prince-The Artist"),
new f("//videos.videomusica.es/Queen.html","Videomúsica sección videos, Queen","Videomúsica, información y videos. Queen"),new f("//videos.videomusica.es/Radio.Futura.html","Videomúsica sección videos, Radio Futura","Videomúsica, información y videos. Radio Futura"),new f("//videos.videomusica.es/Raphael.html","Videomúsica sección videos, Raphael","Videomúsica, información y videos. Raphael"),new f("//videos.videomusica.es/Rem.html","Videomúsica sección videos, R.E.M.","Videomúsica, información y videos. R.E.M."),new f("//videos.videomusica.es/Rico.html","Videomúsica sección videos, Rico","Videomúsica, información y videos. Rico"),new f("//videos.videomusica.es/Roberto.Carlos.html","Videomúsica sección videos, Roberto Carlos","Videomúsica, información y videos. Roberto Carlos"),new f("//videos.videomusica.es/Roxy.Music.html","Videomúsica sección videos, Roxy Music","Videomúsica, información y videos. Roxy Music"),new f("//videos.videomusica.es/Roy.Orbison.html","Videomúsica sección videos, Roy Orbison","Videomúsica, información y videos. Roy Orbison"),new f("//videos.videomusica.es/Sade.html","Videomúsica sección videos, Sade","Videomúsica, información y videos. Sade"),new f("//videos.videomusica.es/Shakira.html","Videomúsica sección videos, Shakira","Videomúsica, información y videos. Shakira"),
new f("//videos.videomusica.es/Simply.Red.html","Videomúsica sección videos, Simply Red","Videomúsica, información y videos. Simply Red"),new f("//videos.videomusica.es/Spandau.Ballet.html","Videomúsica sección videos, Spandau Ballet","Videomúsica, información y videos. Spandau Ballet"),new f("//videos.videomusica.es/Stevie.Wonder.html","Videomúsica sección videos, Stevie Wonder","Videomúsica, información y videos. Stevie Wonder"),new f("//videos.videomusica.es/Sting.html","Videomúsica sección videos, Sting","Videomúsica, información y videos. Sting"),new f("//videos.videomusica.es/Supertramp.html","Videomúsica sección videos, Supertramp","Videomúsica, información y videos. Supertramp"),new f("//videos.videomusica.es/Tequila.html","Videomúsica sección videos, Tequila","Videomúsica, información y videos. Tequila"),new f("//videos.videomusica.es/Terence.Trent.html","Videomúsica sección videos, Terence Trent D'Arby","Videomúsica, información y videos. Sananda Maitreya-Terence Trent D'Arby"),new f("//videos.videomusica.es/The.Carpenters.html","Videomúsica sección videos, The Carpenters","Videomúsica, información y videos. The Carpenters"),new f("//videos.videomusica.es/The.Doobie.Brothers.html","Videomúsica sección videos, The Doobie Brothers","Videomúsica, información y videos. The Doobie Brothers"),new f("//videos.videomusica.es/The.Jacksons.html","Videomúsica sección videos, The Jacksons","Videomúsica, información y videos. The Jacksons"),
new f("//videos.videomusica.es/The.Manhattan.Transfer.html","Videomúsica sección videos, The Manhattan Transfer","Videomúsica, información y videos. The Manhattan Transfer"),new f("//videos.videomusica.es/Tino.Casal.html","Videomúsica sección videos, Tino Casal","Videomúsica, información y videos. Tino Casal"),new f("//videos.videomusica.es/Triana.html","Videomúsica sección videos, Triana","Videomúsica, información y videos. Triana"),new f("//videos.videomusica.es/U2.html","Videomúsica sección videos, U2","Videomúsica, información y videos. U2"),new f("//videos.videomusica.es/Umberto.Tozzi.html","Videomúsica, Umberto Tozzi","Videomúsica, información y videos. Umberto Tozzi"),new f("//videos.videomusica.es/Van.Morrison.html","Videomúsica sección videos, Van Morrison","Videomúsica, información y videos. Van Morrison"),new f("//videos.videomusica.es/Victor.Manuel.html","Videomúsica sección videos, Victor Manuel","Videomúsica, información y videos. Victor Manuel"),new f("//videos.videomusica.es/Zucchero.html","Videomúsica sección videos, Zucchero","Videomúsica, información y videos. Zucchero"));
var L=1, D=1, M=1, Ws=new Array (
"000000O","03itdgK","05lssyqaenoH","07dtavu9rjwI","0kcet4appqS","0omja1ivpx0U","0q0ubkwcueoC","0qtrcbaqtymE","0u30mubqcaw d","10 hX1",
"100G8","10ctifjeojq d","12 i(%","127555569 ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","14 lGo","15A","150Z","158fwcg27zeQ","16 iW<","175.",
"190 l","1927#","1941#","1943W","1951 b","1965Q","1967Q","1969M","1970 gU","1971/",
"1972 i","1973M+","1975S","1976E","1977B","1978 g","1979 m`S","1980 m'","1981 d;","1982;2",
"1984F%","1985 i","1987 86","1991X","1992:","1993 n","1994N","1995^","1996@","1998L65&",
"1999 n","1by e","1coyvkedf00 c","1jl8a20hS","1oedfjxzg5g m","1qrn8c24a\\","20 7","200*","2002&","2003 n>*",
"2006E","2007@","2009A(","2010^","2011X","2012*","2014 iM","2016TF81","2017%","2018 ponmlkjihgfedcba`_]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#^",
"2019N6.","2020 ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGEDCBA@?>=<;:9876543210/.-,+*)('&%$#F","21T","22 l","24 0","25L8","26SQ","275iksf2fqm 5","28@","2ao901rx n",
"2ezwa?","2hhzmrmahxu<","2kvivewM","2nf9dwlhvoc n","2q9mtjokc4a i","2tj8v2bmftyR","2y2g6dciys8.","30,","300WS","35:$",
"365 0","3aymegoesae%","3qad8385pxa)","3v62a2j e","3x1%","40MD=","46rifqdimea m","46vgynndfziP","46y8A","49gy4oslg40`",
"4cagg2qmaay.","4dwcpqjcw3y<","4e<","4e4>","4jkis37a2je:","4k9f;","4n8jjod1h04@","4qszlr6pnY","4tyv2phg89a]","4yg\\",
"50 naW4","52.","57ykv1d0qeeK","5qn2sjsqaje(","5roiwX","5ww-","5yc l","60 hWKFC71","6cpaoyri8d4_","6cs3pvmmv0e 8",
"6dedzscgbsq l","6f4bwqffT","6g8tmiqxnec 1","6inwzoooxru f","6kgvcwcb6ik e","6lfxgbb4ugu n","6pprs1mc4sc'","6yok4d53s5uF","6ywytbR","6yychgx1fmw+",
"6yziz1flaws 8","6z/","70 okfdSMKB:7/-*m63","7bdwQ","7bmahc&","7bwwo7ctg10B","7cqheq4 d","7eyihajlt0g,","7kae99gZ","7mro:",
"7o[","7olcdlxgc0u 0","7oqnqy9bfj8N","7vstpwvmqgi&","80 lhedcb_]XVTRPMLIGB?*m)","89am8kc@","8cufkd:","8etpsn3qdeiM","8gewtiH","8nxvha7k j",
"8pkju1u8zk0 p","8qz8fqmtsjy 5","8qzi m","90 d]YXTRL+I","92,","9aykowwrf c","9b4f 6","9c5ypiq3lqi-","9cinkkn4$","9klbkgcvz c",
"9mfcbhk02s 0","9vjj6j7gxpy a","9xdnsT","9yktv>","álbum pmlgeVKFA6/(iXS*0","álbumes kcULK@><","álgidoR","ángelesK","ánimoR","â¡qué c",
"árabe^","árabesI","áspera<","â¡tan]","â¡utópicoT","â¿T","â¿o*","ã“peraN","â€œwhatâ€™sK","â© ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"él keWK621","época mQKB%","éste l","éxito lihgfdb\\XSNMLJIH@;80/.-)'o6m^","éxitos d^XWNKFE<43-+%$h","â® ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","ã‰l pF;","ã‰sta l","ã‰xitos_","ãlvaro@",
"a152e46obm0 7","ópera.","órganoC","a8gj9vvuh 6","a8rwz6zbjse^","añadieron`","añadir i","año mid`ZXUNMF>*'&^@;6","años onjdba_^VQKJIHGED?>:7641/.,$mle[YNMA<30-Wh","aún e",
"aaron#","abandonóF@1.","abarcar i","abba$","abbey j","abc h","abeja=","abierta]","abiertoI","abiertosI",
"aboutE>","abríaK","abrazarte o","abre k","abrióI5-","abriendo?","abrilTF","absolutoK","abuelo o","acabó k(",
"acabando j","acabar b","acabaron f","acabo 5","acústicosV>","acaparado&","acariciaZ","accidentalT","accidente kjQ","according e",
"aceite n","aceptar]","acercándose 0","acero>","acertada n","acid 9:","ackymdc4 l","acompañadas/+","acompañadoT=8","acompañamiento]",
"acompañando_","acompañar)","acontecíaK","acordesM","acqqvt7itp8Z","acreedor n","actúa]","activa e","activarA","activo aUF&",
"actriz^'","actuaciones 3)j","actual a*","actuales 0","actualidad^)","actualmente d","actuar i?","acudir$","acuerdo 7","acumular:",
"acurrucarse 3","adam l","adamsP","adaptándolo 0","adaptables@","adaptaciónL'","adaptacionesL","adaptarse 1","adecuado 8","adelantado j",
"adelantarse 1","adelanteN","adelanto h","además n^M","aderezado&","adiós;","adiccionesK","adictivas kg","adjetivos a","admiraciónK",
"admiradores l?","adolescente>","adoptóX","adoradores$","adoroD","adquieran l","adquirióE","adquiriendoA","adu]","afamadoE",
"affirmation 7","afgt7trnr2k k","afloran_","africa^","africana#","after$3","agapimú'","aglutinarK3*$","agnetha$","agradable-",
"agradables]","agradecer n","agrandarW","agresiva 8","aguasJ","aguirre&","agustito?","ahí$","ahoraJ*","ainK",
"aireL","airearonY","aires*","ajopt7zjar0>","akpebr4gseu%","al nmki]YUSKIHCBA=<850+*($lec_PL@?;:6/g[MJF3%oR)","albaF","alberti'","alcalá'","alcance%",
"alcanzaN","alcanzóK6","alcanzable_","alcanzado l","alcanzando bN<","alcanzar.","alcanzaron mihf*L","alegatoF","alegra^","alejandro^J",
"alejo dH","aleluyaF","alemán-","alemaniaL","algoR#.e","alguien 1","algunaZSM0","algunas k<)$","algunos nNK21.","aliño 8",
"alive*","all ponmlkjihgfedcba`_^][ZYXWVUTSRQPNMLJIHGFEDCA@?>=<;:986543210/.-+*)('&#K7$\\B,%","allí e","allá oWJ^","alma png_RQMFED;9/']#","almasQN","alo7u0sQ","alone b","alrededor]","alright hg",
"altasI.(","alternativoX","alto ihg`\\L82","always n9","américaW","amados b","amaia@","amamamos c","amante.","amaral&",
"amarillo^","amayaM","amazing 8","ambiciónK","ambiciosaT","ambientalK","ambiente?","ambigua l","ambiguo 1","america c",
"americana g#","americanasA","americans 1","amigo 2","amigosZ","amo m","amorZMFC=;0kN'oG.","amour i","amplio g<","ana oL'",
"anatomíaA","and nlhfe_\\XTS6+)d","andadura kL@8","andaluz kI","andaluza k","andrés d","andrew j]8","angdgp9psb8 o","angel[","angels e",
"anglo]","anglosajón mJ;","anillo g","animadaE","aniversario$","ankirsycetw>","annabelV","anorexia f","anotherUSE","ante lj_QK/'F",
"anteriormente 3","antes k`XKF<5","anthonyJ","antiguoS","antojaba j$","antonioY?(","anuncian$","anunciar 8","última l","último 0(",
"últimos^F","únicaNK#","único a^WD>41.","únicos 3","apacibles f","aparecieron h","aparentementeN","aparición hEA7-","aparienciaTA","aparte%",
"apbfcvdkmxmE","apellido h","apenas hK","apetitosos d","apodadoR","apoderaTR","apogeo`?*","apostandoH","apoyado 9","apoyarK",
"aprendíD","aprenderI","aprendiD","aptasT","apuesta@","aquí iJF","aquel mieM20WQ","aquella mQ","aquellos 0","aquiF",
"aquiles^","ar8d2yqgq1u`","arafqe94nD","arby 0e","arco g","ardióI","ardiente_","areUB<a","areethaA","arena%",
"aretha]/","argentino d","argumentalK","arguments ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","arie#","ariel d","armadura(","armario$","armas h","armonía gM",
"armonías?$","armonizada>","armsQ","aromas j","around 7","arrancaronV","arrebatándonos(","arrebatóE","arrebatadorH","arrebatadora_",
"arrebato l","arreglos fM","arriba o","artística j","artísticamente bW","artísticas oI","artísticoVh","arte iF","artes n","artistT",
"artista h_L8e^N.","artistas ponmlkjihgfedcb`_^]\\[ZYXWVUTSQPNMLJIHGFEDCB@?>=;:87654321/,+)('&%$#RA<90.-*aK","arts>","asX","así dNID:98nh.","ascendenciaF","asesinado`","asi p[","ãšltimoI","asoma>",
"aspecto(","aspirando i","aspirarL","asturiano o","asumiendoK","at,%","aterciopeladaQE","atlanticA","atmósfera>","atrás kKE*",
"atractiva]","atractivo]9","atrapado#","atrapan g","atrapar]","atraparte_R","atraviesa>","atraviesanR","atrayente]","atrevido p",
"au8u h","auao50nwnvgQ","audienciaZ","audiencias i","augusto b","aumentar 7","aunN","aunan i","aunque_XWRLF>)$","aupóL",
"auparon(","auraR","aureola]","auseronV","auspicio h","auténticaC%","auténtico=","auténticos d","auteF","autenticidadJ",
"autodidactaI","automedicarse j","autorB","autora^/","autores o","avalon[","avatares$","avecL","aventuraY","avionetaQ",
"awD","awardsZN","away#","axz9cpnwns0 1","ayer(","ayudaba h","ayyyK","azaharaIC","azulIZ","b3gbisdtjna^",
"b6zqd0s&","bálsamo n","bésameYD","babaji c","baby i","babylon-","bachata=","bache h","back ih","backgroundO",
"baduA","bagajeG","bahiaQ","baila p","bailar=","bailarina^","baile hb","bailes-","bailey 3","bajón 8",
"bajista b`YU","bajo lkheVUN*)j","baker-","balada pJ","baladas\\863","balance'","balanceándose g","balazosK","ballet`","baluarte&",
"bandG","banda h`XVU)$l:*gc","bandasXA630","barón)","barbra*","baron)","barranquilla^","barreras^","barrettS","barricades`",
"barroI","barroco j","barry j*","basada)","bastantes)","batalla 1","batería lk`UK3)","bateristaU","batt>","bayQ",
"bayou\\","bazasH","bbcR","beUA<*hf40","beach\\","beatles\\Q$","beautiful 2","bebían 0","beber 7","bebiendo?",
"becker 2","bee*","been/Q","begun f","belén o'","belfast n","believes g","bella\\>'","bellas ofMH(","bellezaIF(",
"bellos gf'","belongE","bendición=","bendita=","benegas@","bengalí j","benidormW","benny$","benson 7","beretT",
"bernie 4","berryK","besarte d","beseJ","besosG","bfhsf6fkgb4T","bfqonlm0ggu 0","bgotdgu8cho,","bibliotecaB","bicicleta^",
"bicycles>","bien l#*","bigG6","bikinaG","bilbaíno 5","bilirrubina=","billboardZ6","billie]","billy'+j","bin3jekig9s'",
"bipolaridad c","bird#","birdland i","bit c","bitesU","bizO","biznieto?","bjorn$","bkajs8wayd4#","black g",
"blame h","blanca,","blancasQ","blanco gM1'n","blancos_\\","blue ng_*\\R","blues pnKHE>364","bluey 9","bnlsdqnj0lu(","bob\\",
"bobby-,","boca 50","bodyOh","bohemianU","boj6fl8eoxaS","boleroGD","boney-","bonitas`","bono l","boogie h3",
"boom i","botánicoV","botas)","boteQ","bottom ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","bout 9","bowie 1","boy i<j","boys\\","brand b",
"branigan m","brasil i","brasileñaZ","brasileñas'","brazilianZ","brazos o","breakU","breakfast c","breaking 4","breakthruU",
"breezin 7","brianUl[","brickS","brillante ke_>","brillantezP","bring b","brit n>","británica c:","británico n_4*","británicosS1",
"broadway 7","brookingY","brota lP","brotherK","brothers g#","brown n9-","brusca j","bryan[","bu26eI","buckingham 6",
"buen licbUGC<;90+A","buena^K:97-","buenasC","burbujas=","burlóF","buscar ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","buzz:","bvauqazuh9oI","bw6sfc9u07o\\","by ponmlkjihfedcba`^]\\[ZYXWVUTSRQPNMLJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#gK_",
"by2e2m4thnm@","by2ew9.","c0blkudnyno]","c3nscn89klo 4","c5s6dfiqywo(","c7wjmepf7u0 d","cálida e","cálido/","cálidos]@","cáncerE10(",
"cómoUM&","ca46znjrzey b","caídoV","cabeza m","cables e","cabrales 5","cada k,","cadenas]","caducidadR","cae k",
"café=","calabria)","calamaro d","calaronF","calderónM","caldwell,","calidad nmi]C96%$","calidez'","caliente g","calificativoN",
"california\\","californiana g","call 4","callao=","called a","callejónK","calorV","camaZ","camaleón 1","cambió 8",
"cambiando hM","cambio 7","camilo.","caminaré m","camino kKI","campo<","camposI","campuzano)","can h#","canaan/",
"canción olZWSC)MFEBQ'","cancion^","canciones oleda`]YXSQMLIHGDCA?>=<:8321,+)'%$mkgcb\\WR4.fK(F","candiA","candidez\\","candoroso/","cano'L","canta on","cantadas;","cantan.",
"cantandoE","cantante jaJHA843/,+;","cantantes%","cantar h_WQ<","cantaráM","cantautorF","cantautora/","cantautores+'","cantidad.","capaces k_;93",
"capacidad l;","capasI","capaz nbRKJI=8.(e","capitalF","capturaban/","capturadaQ","caraZ","caracterL","característico l","caracterizado$",
"caracterizar=","carasQ","carbónI","carcomidoS","cardíaco 8","careless 8","cariñoZ","caricia p","caricias>","carismaV",
"carlos^HZYM","carmona?","carneW","carole/","carolinaH)","carpenters f","carrackR","carrera hgZRQGE<42'","carry,","casa^YTQ5",
"casal j","casi e_\\QMCA?.'j","caskuxE","caso*'","castellano$","castro)","católicaX","catalanaF","catalizar 9","catalogada<",
"catalogados i","catalogar e","catapultó`X","catapultarloW","causa n","cautivar 7","cay74#","cayendoK","cbs h)","cds$",
"ceE","ceilingB","ceju9kvabaoU","celeste p","celine*","celtic n","censuraF","centrándonos j","centró d","centroR",
"century c","cercana 1","cercanos@","cerebralF","cerebroSR","cewhzel76ee?","chacon 0","chainsP","champú j","championsU",
"changes 1","chanson i","charles]0","chica(","chico l","child 8","chilenas b","china g1","chjt4xdazoc h","chocolate 0",
"ciega^","ciego a;","cieloJ","cierto:","cimientos)","cinco f","cineF","circleP4","circula g","citados 3",
"city iK","ciudad'","ciudades o","clásicas i","clásico g<0","clásicos d0","clímaxK","clanH","claptonR","clara e",
"claridad m","claro i","claudicaranQ","clayton l","cllore;","close f","clubs i","cndlbu0gX","coB","coche j",
"colaboración 0","colaboraciones p","colaboradora)","colaborarR","coleL","colectivaU","coletazosF","colombia^","colombiana^","color pg_R,",
"colorido 9","comaF","combinabaK","combinaciones[","come i","comentaA","comentábamosM","comenzóW8","comenzando i","comenzaronL@",
"comercial gIA6","comerciales_","comercialidad c8$%","comerse e","comes 7","comfortablyS","comienzo mlQMK<jC","comienzos nf]\\H)LK","commodoresB","como mlcZYVULIGB?=;754/+*phf`^WTPJC<9821,($okig_RQMFA63.'njeb\\XNK0]%",
"compás]","compañía)'","compañera(","compañeroY","compactaba f","compactadas 0","compaginaban c","compaginando 2","comparadaA","comparesT",
"compartióE","compartirI","comparto 1","complemento)","completo.","complicidad 3","componíanU","componenteM8","componentes iUM","componer 2(",
"componiendo`","composiciónEC8","composiciones p]J@;/*('$6","compositiva o<9(","compositivoM","compositor ja`RH>4.,+&3","compositoraA/&","compositores nmM/","compostura'","compromiso/",
"compuesta g_'","compuesto?-","compuso/","comunesX","con_ZVUTDC65/#pfb][YSHA@>1+mlc\\N<;720*$nigaLGEB843.'&kdRPJ?=9)(eXQF%jWIM^K","concibióN","concierto%","conciertosS?","concretoX","concursoA",
"condenadosF","conduceM","conducir<","conduzcaR","conectandoI","conectar b^","confesar e","confianzaA","config ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","conjugando$",
"conjugar e","conmigo 7","conocíamos e","conocerT@7","conocerse 0","conocida lV^","conocidasSK%","conocido pnibT1","conocidos mZ@:3*$","conocieseT",
"consagrándose 5","consagróN","consagrado(","consagraron c","consagrarse h","consciente]","consecuencia j^T80(","consecutivasL","conseguía%","conseguidoN%",
"conseguirWRJ","conseguirloN","conservan]","conservando]","considerabanM","considerada]","considerado lJE+","considerados?","consigueF","consiguen_",
"consiguió m","consiguiendo e","consiguieron 3*&","consiste i","consolidación j","consorcioM","consumadoQ","contó[","contaba 0.","contacto 7",
"contador+","contagia 9","contagiarnosH","contagiarse 4","contagioso h","contagiosos 8-","contaronK<","contarte k","contemplarQ","conteníaQK",
"contenida k","contenidoS","contenidos ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","content ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","contigo@D","continúa onW'","continúeM","continuó 20","continuado\\U","continuando d",
"continuar@(","continuaronX","continuidadK","contra b1LF","contradecir<","contradiccionesXK","contrapartidaX","contraria j","contrario=<","contrastada'",
"contratiempos(","controlK=h","convencional j","converger 0","convertiéndose 0","convertida=","convertido[1","convertirseB?","convierte@","conviertieronA",
"convirtiéndolos-","convirtiéndose l^]M5","convirtió eQN?K","convirtiera*","convirtieran 8","convirtieron 3","convulsaK","cooke eK","cookieconsent ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","cool-",
"copa^","copia 0","copiasX*&","corazón onZMKFED;","corazon oVD","corporal(","corre#","correctaA","corriendo&","cortes)",
"corto aJ3","cosa$","cosas nW","cosechados 3","cosechar^","cosi p","cosmic:","cotidianidadI","country nh\\B6#g","cowboy:",
"coz)","cprgk5rksc0J","críticaK","crazyS","creación 5","creada`","creado-$","creadorF","creamT","creando 4",
"crear n,","creatibidad/","creativa)(","creatividad jB","creativo a41h","creativos 7","crece'","crime c","crisis ec","cristalina f>",
"cristalinasP","cristiano^K","cristinaF","criticado%","cropperQ","cruce e","cruces;","cruzL","cruzar o","crying\\",
"ctdr6brrvx8 9","cuéntame@i","cuídate@","cual m/","cualesS","cualidad_","cualidadesNC7,","cualquier p_^LB732","cualquiera pLG","cuando lke\\RNIE*K<",
"cuantos>","cuarteto iX","cuatroY","cubanosV","cueca b","cuenta m","cuente 5","cuerdas^","cuerpoF","cuestaL",
"cuidadasB@5&","culpa b","culto lX?","cumpleañosK","cumplir j","cun7paje8icW","cuotas*","curiosamenteT","curranteW","cut`",
"cuyaRK","cuyo h.","cww03hjhod4M","cye8et b","d27gtrppayk b","d2yrI","d5cr9mrlsc0 k","d77tdtsn7nk j","da n","débil(",
"década onh`^XTSRKG?72/6-","décadas on_\\97'%","décima(","déjameM","día onW","días&","dabaY","daddy-","dado pQ","dímeloJ",
"danA2","dance b:8-e1","dancingB*$","dandoBA97]","daniel l","danza b","danzan b","dúo f0","dúos f","dar phedRQI<",
"daría h","dark ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","darles 8","darse@","datalayer ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","date ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","dave l","david 1","davies c","davis p",
"day b/","days fe","de#c`[=JHC1pda\\UND@5,XP:2<;-+YVGEB864/fb_]9)&%oigT3mZ>LA0$^SR?QI7.W'kMheFnl*j(K","deaconU","deadE","debajoGA","debería 7","debidoQM","debilidadK","debilitóB",
"debilitamientoK","debut eYA<20","decíamosX<","decayendo hX","decide h","deciden)","decidióK","decir cLI;3M","declaraciónV","decliveK*",
"dedicabanC","dedicadaS;","dedo g","dee 4","deep*","define#","definen n","definición=","definir a[J","definitiva 8j",
"definitivamente*","definitivo&","degradamientoK","deja i^J9","dejándonosF","dejó o]TQ0%","dejaba?(","dejaban-*","dejado(","dejar e(j",
"dejaronYC@-","dejarse]:7","del jgcb[YWJC:954-#pomf`]\\VPNA@>=<;8.,+hea_USRIHGDB32*)(lki^ZXTQLF?10/&%$K'dM76En","deleitado%","delicada>#","delicadas f","delicadeza 4/","delicado 3","deliciaR%","delicias c2",
"deliciosos i","demásME&","demoniosK","demostró<","denman]","denominado n","denominanX","dentroJ>6$","depresión(","depresivas 8",
"deprisa j","desátameN","desafiante)","desapareció f","desaparecidoM-","desaparecidos b","desapareciendo 0","desaparición(","desapariciones*","desaveniencias$",
"desbocado<","desbordanteT","descalzos^","descaro dAY","descartarZ","descendió 6","descomunalU","desconfiar?","describiendo b","describir(",
"descubrió>","descubrimientoPA","descubrir a_","descubrirlosY","descuidada(","desde nlgd_^XSQNDC6'&$MJ:1","desempolvando$","desencadenante 0","desenfrenada g","desenvuelvía%",
"deseo j","desesperada k","desgarradaQE","desgarradoraQ","deslizándose_","deslocado h","deslumbrante k","desmedida.","desnuda k>","desnudesF",
"desparpajo h","despiertaH","después khM80","despuntóW","despuntaba h","destacados 5","destacandoZ","destinoL","desván o","desvaneciera f",
"desvanecimiento*","detallesZ","deteriorar(","deterioroK)","detonante 0","detrás$","detroitK","deuS","devaneos%","devoción:",
"dfe3s3)","di m","di0 2","dia nVMKC7'","dió geQM","diamante p","diamondS","diamondsT","dianaB","diariosA",
"dias lX1","dicesD","dicho n","diciembre 8","dictadura b","didn+","die:","dieronC?","diez 5","difíciles l",
"diferencias o","diferentesM-%","dificil]Z>7%$","dificiles(","dificultadI","difruta 3","diganW","diggin<","digna n","dignas>",
"digo o","diguehwmorc o","dime dm","dimensión l","dimmi m","dinamismo 3","dineroK","dion*","dionne*","dios'",
"dioses?","diríaA","dirección jA","directamenteR","directoH73%","director jF","directos 3&","disco he`YW<;963-,&Q20*","discográficaG<h","discográfico e-A",
"discografía a$","discos lZYSQG;:852/.)%eWL","discoteca 2","discurrido 1","discusionesK","disfrutabanQ","disfrutando ed$","disfrutar nieYM9","disfrutarlo%","disfruto,",
"dislumbraba e","disminuidos o","disoluciónYXI@$","disparesL;j","dispuestas]","dispuestoI","disquera;","distanciaZ","distina)","distinguidasE",
"diva'N","diversión 3","diversidad*i","diverso i","diversosA5%","divididaS","divinaN4","divino p","dje0/","djfgb 9",
"djklltlmnds&","dkytjloxgmq g","dluhzqhlcme e","dlxpnif0yksX","dmgvs2j05ha_","dnrxd6v4 6","do,0","dockQ","doctorados n","dojvw>",
"dolly*","dolor l","dominicano=","don cURA9_^64,#","donâ€™tP","donald 2","donde onlec^XTSQNMKA510)F%i","donna p","donostiarras@","doobie g",
"dorada f%","dormirH","dos oVMKJ;5F","dosis(","dotándolo n","dotadoE8","dotesI,","downP4h","dr:","dream 9",
"dreamer c","dreams+\\6","drogas fS8K","drove\\","dtpqoafxc=","dtvbcg6thdk 4","dublinesaA","duda]WRMF6l","dudoD","dueñoKE",
"dueños ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.,+*)('&%$#-","duelaW","duende;","duermanI","duetoP","duetosK","duke a","dulceQ@","dulzura<>","duophonic 0",
"duper<","duque 1","dura 1","duraciónS","durante gF6j","duro(","dustU","dut5reu6pqm^","dxdkywilt74B","dylan\\",
"dzhje11cgX","dznqcmpcqxq 2","dzsue5ugxf4^","e3 l","earth 3","easyB0","eazjxniqnqi.","ecologíaI","económicaK","edén j",
"edad oWG>","eddie 0","edema j","edge l","editado;","eduardo kF","educaciónSP","efímero 0","efecto$","eftlkww542g+",
"egocéntricoT","egocentrismo e","egs'","ehpe7b4fx8,","ehqg6>","ehulq#","ejecuciónF","ejerce^","el mc`\\YSPB92ofd^RLG=;:+(pbXH/n]JE87-'%jigVQNA<5.,&kUTD>$lZI@?310eW6)hMF*K","elaboradasL8",
"electrónica 1","electrónico 3","electrónicosV:","electro:","elegancia k[GE97]","elegante gK6","elegantes f","elegidas 4","elemento)","elenco 3",
"elevarles$","elixir(","ella`^]A>/","ellas mF1b2","ello ni]XU:.,","ellos lhf_\\YXVMD@?>;3+gdU$","elocuente&","eloise j","eltonR4","elvis\\",
"embajadora^","embarcadoV","embelesar m","emblemático l","embrujada j","emergentesA","emi 0","emigró>","emisoras 0","emoción oH6#",
"emocionándonosQ","emocionalK","emocionar b","emocionarmeF","emocionarnos=","emocionarteI","emociones onRJ;('","emotividad eB4","empape>","empaticenR",
"empezó\\KGE","empezarK","empezaron\\","empiecen 2","empiezaI","empiezanF","empiezoN","empresariales o","en cZYJC<&fTRQI:91m`_][XSG=;4/,kgVUPDB+$#pldbE?730('e\\F>ohA85-*%naWL@.2)6^NMjiK","enérgica/",
"enérgicas g","enérgicoK","enamoraJ","enamoróW","enamorado pV","enamorarJ","encandilaJ","encanto m]QA:9%","encantos 8","encargóQ",
"encauzadoC","encerrabaT","encerradoD","encienda 2","encogerF","encontrabaM","encontraban e","encontramosM","encontrar i:%","encontrarnos 8",
"encuentre%","encuentres^","encuentroD","endXE","endlessB","energía gdQ.93:","enero 1","enfermoN","enganchados+","enganchar_",
"engancharte;0","englishman b","engranaje@","enmascarandoF","eno[l","enormeZEB.","enoughK","ensayarC","enseñándonos h","enseguida<",
"entenderN","enternecernos=","enterradas e","enterrados e","entonacionesW","entonces mieM0","entradaM@","entramado'","entrando/","entre lgJ$5",
"entrecruzabanN","envidiableGB","envidiables l","envoltorio e","envolturas>","envolvente g","envolverá p%","envolverteR","envolviéndote'","envolviendo>",
"eo7iwlmfprm:","eo8r1w8qrgo\\","eoqu b","eqlnl8D","eqp1s#","equivocaría 5","equvoqut1vmA","era jhSPKIEB?872*)e","eranF?63$","eresM",
"ericR","erizarmeF","erranteC","erupción_","erykahA","es lkjifdcb`\\[ZYXWVUNKHECBA@?<:850/-)('$neRPLGD=;64321,+*&omhg_QJ>97#^S.%pa]ITMF","esa mlf_MA=82/-)","esas\\XKF4R","escándaloW","escándalos 8",
"escénicoF","escalofriante g","escapan'","escena 9","escenario]\\UK","escenas;","esclavitudK","escondeA","esconditeN","escritor 0",
"escucha^","escuchabaQ","escuchadas f>","escuchadoM","escuchamos*","escuchando]I","escuchar:9*#","escucharleR","escuche b","escucho,",
"escuela nV","escultura j","ese mc_^]ZTC;7*(#hRMA0","esencia kS>3(","esferas.","esguince j","esoYHA%","esos ge_YQMLKA0(3)","españa iVNF.)'5","español omda_F?;)NL.(&",
"española jNM","españoles oM","espacio@>&","espada 5","espaldarazo&","espaldas@7","esparce(","espírituL3","especial ne_^VRNMGD;#","especialesD",
"espectáculos-","espectacular nmT3","espectacularesS:","espectacularidad 3","espectante e","espectro m","esperadosN","esperando$","esperarNH6","espiritual(",
"espiritualidad n","espléndido a","espontaneidadX","esposas b","esrb6yv[","esseZ","est#","esta cb]XQPNMA<:6","estáM,+Z","estásM",
"estéI","estã¬loB","estaba gXSA)","estaban 3","estaciones(","estadoR","estados iWM","estadounidenseX0+","estamos f;?","estando he?",
"estarF+","estaré e","estaréis 7","estas,","estatuaV","estatus c($","este pnieXQNB?<76.#g^%","estilo jiWJICA?<6g","estilos p;5*%","esto^M",
"estos$","estoy a@","estrafalario 4","estrellaWEB&","estrellatoKA","estremecedorasF","estremecedores 8","estremecerte n","estribillosX","estrictasS",
"estructuraI","estudiaba>","estudio(","estudios j","estupendasC","estuvo iK","etapa lkfB8521)bM(","etapas 8","eterna c","eternamente(",
"eterno.","euZ","europa iWNM-","europeX","europeos&","eurovisiónWM$","eva&","evans l","even c","ever b%",
"everybodyX#","everywhere 6","evidente 0","evidentemente e","evitar 8","evocando:","evoluciónL7","evolucionó 6","evolucionando`S","ewjciC",
"exY","exageraciónM","excéntricoK","excelencia(","excelente 2","excentricitésN","excepciónM","excepcional/'","excepcionales 3","exceptuandoL",
"exhalan m","existían 6","existencia 4","existencial e","exitosa 8","exitosasU","exkwkqI","experimental eS1","experimentales[","experimentarI",
"expertosX","explain n","explicaciones e","explorarI","explosión*","explosionar 3","explosivo d","explotado o","explotando 3","exponentesR",
"expresaQ","expresabanX","exquisita]4","exquisitas?","exquisitoR","extensaF","extenso nZ","exterior_","extraidos 9","extraordinaria-",
"extraordinario f1","extravaganteUT1","extrayendo&","eyeX","eyed g_Rn","eyes[7R","ezk9rhnnvwe m","f5q4y 9","f8ksqdsztugH","fácilA4]",
"férreo h","fértilesT","faceta o<8(j","facetas o","facilidadF1","factura j","fagen 2","faith b8","fake_","fallecimientoQ",
"fallidoL","fallo 8","falsete g\\3","falsetes 3","falsetto*","famaE/-+n","fame l61","familia hM?","famosaSQ%","famosoL$",
"famosos jD'","fans$","fantástica g_.","fantásticas p","fantasy 3","farian-","farrell-","fascinantes 3","física#","físicamenteT",
"físico(","físicos o","fast 8","fastuoso 3","fatalY","father 8","favorI","fearsP","febrero%","fechaR",
"feelXh/","feelin h","feelingP7","feliciano;","feliz;","fell e<","femenina^PN/","femeninas$","femmeL","fenómenoW",
"fentaniloT","fernandoY","ferry[","festival$","festivalesW)","fever*","fgb9cvwdn04\\","fichar;","fielZI>","fields b",
"fieles i","fiestaL","fiestas@","fifa^","figuerasN","figuras 2","figure 8","fijó<","fijarse l","filaI",
"filántropa^","filipinasF","filosóficoS","fin nf('C","fina k","final jfdQK*","finales nmdPKIC*","finalizándolaL","finalización k","finalizada 6",
"finalizando b","findE","fineX/","finura]","fire;+3","firmado j","firmar j","firme)","fitipaldis 5","fito 5",
"five h","fj9ruzimczqU","fk9iqnq883o p","flackA","flagelantesU","flame,","flamenca k","flamenco k?","flamencosI?","fleetwood 6",
"flicteaP","flood>","flor o?","flores?","florida 2","floydS","fluye:","fly`S","fm8ggdigcwyJ","fmjgnedhkby j",
"fnfzfwlm72c*","folk nig&","food i","fool c#g","for`>,#lP%","forjando&","forjarseK","forma mj_VQIF;4(e:2","formó dYB","formaban h6)",
"formacíones h","formación h]@?9)M","formacionesM","formadaM)","formado f]*","formados&","forman kUI*","formar dXVHA*(","formaron ih`XUEC:0*","fornaciari p",
"fortuna n","forzados(","fotos b","found l","fovcbmkuw0-","fragile b","fragilidad(","francésM","francesaL","franciaL",
"franciscoM","frank?-","frankie*","franklin]A/","franquistaF","frío=","freddieU","free bXU","frenéticoJ","frente lkifc[H?3",
"fresco*","frescura@?d","friaH","frialdad k","frida$","friend 9/","friendsU","frjctF","from icA4#0","frontier 2",
"fruto 0","ftbwo6cetuk o","fué n","fue nme`]YTSIA@><8VQNMLEh0K","fuenteX","fuentes@","fuera m","fueron jhdbXNK?-%","fuerteI","fuerza_QLKF<3.",
"fuerzasM@","fueseN","fugaK","fun 6","function ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","fundíanI","fundadoresM","fundamentalU","fundamentalesB","fundamentalismoK",
"funk heTG:93","funky hE<:38","fusión nH?93","fusiona k","fusionando,","futuraV","futuro jK","fuwryuderhcD","fwqpqycqgp8)","g2n0tkfrqhyU",
"género pnG?","géneros 1","gafas\\","gagaU","gamble_E","ganándoloA","ganóWG/","ganando;","ganar=","gang 9",
"garayM","garcíaY&I","garde@","gargantasE","gary`","gatoZ","gaviota'","gaye`A90K","gckghm7gmwm a","gees*",
"genéticaI","generabaK","generación/-*a","generaciones nWG+","generalP&","generationT","generosamenteE","generosidad n","genial eT?7","genialidad kS9",
"genioT","genios(","genteJ","gentleman n","genuina)","genuino aU1","george n87","georgia>","germen)","gerry/",
"gestosW","getEPK","getsemani.","gettT","gf8qy`","ghaqfH","ghetto 72","ghettosK","giae7yz7ghiG","gibb*",
"gigS","gigantes(","gimme$","gira^)$j","giras\\W7","girl n:-+1","give cK:7","gix2pbrbxcq-","gjulpdcct3m c","gklpl4fhzus^",
"glam j1","glamour][","gloria nm","glorias e","gmmc0z0vg04C","gmt d","goUP60-i4","goffin/","gogh d@","goingK",
"gold`>b","golpeU(","goma j","gone 3","gonna:0","goodE#","goodbye fc","goodnight+","gordon b","gordyK",
"gospel nPE","gotKJ/_\\","gotta-","gowebnppuom 5","gozaZ","gozaderaJ","grabado j","gracias g_]NKH;4'nL","grado i","grammy nlieaPG;86/+",
"grammys igfZXKEB7*%","gran mihUQPNIFBA:-lgWRj","grand#","grande 9.","grandes pmg]\\QKHBA97)'","grapevineK","graveW","grease*","greatS","greatest 7",
"green 0","greyA","griega'","groove 3","groovin i","ground ha","grove g","grupo kih_]YXUTRLIHB@53-)'$ljgdb[S?9M6*","grupos iSRC5*&j","gs069dndiyk 3",
"gtag ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","guíaM","guerraK=","guess 4","guille&","guilty*","guitarra lk;7&`","guitarrasUD","guitarristaUQ&?","gusto icG",
"guy[","gxepv4kolz0+","gxqjx7fkmna 5","gypsy 6","h6kyavn8ons 4","h9tevfisdyoT","ha nkihZUQMLHDCA@=:851.+*^W'%p","hábil+","había c","habían(",
"haber oa5.","habernos n","habichuela?","habiendoG","habilidadesA","habilidosaP","habitaciónL","habla lW","hablábamosK","hablamosWE",
"hablando fa;","hablar lD&Sh","habría)","habreísM","hacía k(","hacían 7","hace a^SJ-","hacen k]N","hacer pk97","hacernos=",
"hacerteI","hacia e`SL:6","haciendo\\S72D","had<","hadley`","hagaM","hale]","hall l6","halo e","han pmkd_^[VM@:10/.)(nliG&$",
"hao 8","happeningK","haráF","hard e","hardest 4","hardline e","haritz@","hasM(3","hasta nlji^QE>61+)XM","hauser i",
"have nl","haven l","hay nlXWF:54,","hayá%","hccbfuziJ","hcumwrfxg4e+","head b2","heal 8","healingK","heardK",
"heart bA4#Q","heartbreaker*","heaven>0*#","heavy)j","hecha c","hecho pm^ZWRGDA:8/($n@","hekjnahwihwH","helloB","hemorragias^","here 7SP0",
"herederos@","hermana 0","hermanas bM","hermano`","hermanos hf*#)","hermes)","hermosasG%#","hermosoQ","hermosos/","heroína(",
"herramientas 7","heterogéneaF","hewson l","hgjsbrubxR","hgzgwkwlmgmU","hh3hgusk7pmM","hhx6rgrkgf0 i","hicieron cS832j","hieloE","hierro(",
"highK","higher a","hijoL?","hillsA>","himno lF","hipnóticos-","hippie<","hips^","hispanaW@","hispano^LD@;'d",
"hispanoaméricaM","históricosM","historia olhZLF1/*(k","historiasN+","hit 0","hitosM","hizo fcA?0)(","hjf3e2zgnkg 5","hkm0ih8slcgF","hlguyxtmwe4 0",
"hllcc`","hm8ehtn9rmwJ","hmhezd9bsb4 e","hmkshplxnxe a","ho7796 h","hodgson c","holding e","hollerK","holliday]","hollywoodE",
"hombre pnjTRME=%#K'","home c0-_","homenaje(","homenajeaban`","homosexual l","honestidad=","honorN","honoris n","hooker n","hopeP",
"hora nhe(","horasC","hospital(","house 90","howQR*","hoy oWVQML7)'n","hpx&","hro0wkv4yjoV","hrzgzrqnj58[","hspefI",
"hsq4b+","hubieran-","hucknall_","huecoF=5","huella e]Y","huevo j","huff_E","humano o","humanos l","humo f",
"hung b","hurt 0","hurtinE","hurtsX","huzwQ","hvwnfdadvssR","hwukrT","i4uyofazwpa 7","i6ibauwboda*","i9st43hymbyR",
"iâ€™veQ","iba he*","iberoamérica.","ibn5dzaw4eqP","icS","icteria j","id6zoy b","identidad]VGD?","identificarL","identificaremosW",
"idiomasL","ido_:M&","if>b_e","iglesiaX","igualMBA863*","igualdad l","igualmente hb?","ihs*","iikae8wi0s0$","ik m",
"ikermdasvtg o","il p","ilegal j","illánY","ilusionarseI","im1uv8dk00sP","imágenes ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","imán]","imagen jh\\LK<841$","imaginaciónI",
"imborrable 0","imj4t7oidi0,","immortality*","impávidoT","impasiblesW","impedido.","impedieron d","impedimentos o","imperio n","impidióQ",
"implicación/","importante lTM","importantes<*","imposible.*$#","impregna#","impregnándonos o","imprescindible c","impulsóK","impulsaron e","in l><762-,cb\\QP3*%S",
"inadvertido 0","inalcanzablesM","inamovible\\","incalculable(","incial)","incialesU","inciaron g","incluía*","incluida gX","incluido n+",
"incluso mfMA1)$n","incluye+","incluyen*","incluyendo ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","incognito 9","incombustibleW","incomprensión l","incondicionalG","inconformista jT","inconfundible;W",
"inconfundibles k","incorporación gM","increibles k.","india#","indiferente-","indiscutible h","indiscutibles 8","indispensables 2","individualidad 8","inevitable 8",
"inexorable1$","inexpertaA","infante d","infartoF","infierno)","influencia e\\UI0","influenciado g0","influencias<","influyó*","influyente k",
"influyentes aL51","información a_","ingeniería l","ingenio l","inglés[M)","inglaterra b%","inglesa:","ingredientes 9","ingresó 6","inicial gd",
"inicialesX","iniciarB","iniciaron k?","inicio ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","inicios b`_^","inimaginablesM","inmaculada'","inmediato 8","inmortal 1","innatasN",
"innerK","innuendoU","innumerables$","inolvidableF","inolvidables.(","inquietudesI","insaciableI","insanity:","inseparable 4","insertarPA9ponmlkihgfdcba`_^]\\[ZYXWVURQJIHGFDCB?>=<;8754321/.,+*)(&%$jeTSNMLKE@:60-'#",
"inside 7*","inspiración lX@9","inspirada o'","inspiradas k$","inspirado a","instanteQ","instrumentación k","instrumentales i","instrumentista na","instrumentos eXC",
"insuficiencia j","integrante'","intencionesV","intensidad'","intentaseA","intento jL","interesantes 2","interior iQ","internacional^)&","internacionales:",
"internacionalizar j","internacionalmenteW","internos d","interpretabaK","interpretación eWP8*.","interpretaciones iWJ.","interpretado_","interpretar e;'","interpretarla.","interpretativaQ",
"intimistaI","introducidos l","introducing e","introspección>","intuición^","invita 9","ioJ","ipiñaM","irX","iris g",
"irlanda nA>","irlandés n","irlandesa nl","irrefrenable e","irrepetibleT","is ponmlkjihfedcba`_^\\[ZYXWVUTSRPNMLKJIHGFDCBA@?>=<;:987654321/.-,+)('&$g]Q0#E*%","island 2","islands*","isn a","isnâ´t a",
"it gX:$\\K4/#h","itâ€™sX","italiana m","italianas m","italiano pmM","italianos p","ius84sd0hra;","iv5ojxem6fuD","ivan n","ixdnnw99S",
"iyiol$","izaskunM","izgwdsrq1eq 8","iziborA","izodvbmtdh0_","izugarria ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","izzpC","j0r7cukawg 0","j1sa1t3m<","j3we3 0",
"j789gid1kay n","j7oqepfeX","jóvenesA","jackson ihB","jacksons h","jaenW","jamásQN.","jamiroquai:","japónWL","japan,",
"jardínV","jarreau%","javier dM","jay:","jazzVPGE?>;32,:97%i","jazzman/","jcm4h9rom'","jdwljhqf4 2","je2scisqmpe`","jealous[",
"jean^9","jesús k","jesucristo.","jesus g8","jfjjs0xsm9mC","jhtdwimy.","jillA","jltj5ktfyw8_","jnvy7srofq#","joaquin d",
"jocelyn 9","joel'+","john n`UR4","jones p","josé k?M;","joseL)'","joshua l","joss<","joven eA<","joyas a_(",
"jpmxjmais04?","jppna5pqrpwL","jq2dvwsviio 8","jr l","js ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","js6yqyzszmo 2","jtxv02tyr5a 3","juan kVM?=&","judaísmoK","julián j",
"juntóK","juntaron d","juntarse 0","junto]SIDB@2/,(#Y","juntos d","just ga>f","justiciaN","justoK","juvenilVL","juventud mA(",
"k1ljplq1v6y]","k2ldicb5ejg:","k7oajjdshs8T","kadajqv6sdkG","kamakiriad 2","karen f","katie>","kay:","kcX","kcpc18sg6ua]",
"keeble`","kemp`","kenny g_*","ketama?","kgjfpcjwkyg(","kgrqhwfjq\\","khaled?","ki5p5veewyeX","kiki 4","kindU",
"king]4/","kissT]","kjlmejl5yqmW","klvq0iazh1a b","kmz4panwlae j","knd j","knowX#_","konde5c7og8[","kool 9","kop3cuvd2qq p",
"kpdjqbthay 1","kqa o","kqvwyu4bdmo 8","kszyhtq j","kvc5rcl0bis 7","kvdmlk3ksyg-","kwnfwzem6swL","kytmvki 2","kz.","kzxndlvzs3k%",
"l0cvofsuhc4 3","l0etbwiE","l3d7unj3qck)","l6vyj)","l7vrsuT","la i`\\PD<,+#b[YX4&$fc_HB:1pmaWV=;83/geUTLJGE?20-odRQN>65ZF]SA9%I@7.hM*'nK()^ljk","lópez d","lía'","líder_","laderaN",
"ladoGM","ladyEZ","lag4zjyx89gI","lago k","lakjahibl2y=","lamentablemente kF","landslide 6","líneaK","lanois l","lanza 5",
"lanzándose b","lanzadaN","largaE*(j)","largo_\\Z*'","larry l","las omeca`]\\XWUTNLJHGFE@><;:843.-+*)(&lgfbPI21,%nh^S$K'M6","late/","lately n","latenteL","latidoDF",
"latina^ZWV","latino^JG;","latinoamericanoN","latinos;","laura mZA","lava_","lb6a b","lbjvz0\\","le nZTSPNMKJE+'#b(j","león n",
"lead,","learn:","learningS","leave c`","lee n]V","lefhnn7rl4w i","legado nZT?.","legal j","lejanaQ","lejosA",
"lengua@","lenguajes g","leon_","les hg_XMLD:3-)i@","letPKA4e31","letra gb)'","letras nkiXSLIB@54&$","levantarL","leyendaZWK(","leyendas a",
"leyre@","lhcp4mwabgy l","libertadN?)'o","libertadesF","lider hV5","liderada:9","liderando bR","liderazgo c","lie^0","lies 6",
"lifeP41ia]","light;","like>#E/","limpia f","limpiamente>","limpiasP","linaresW","linda#","lindsay 6","linguaM",
"lion n4","lionelB","lis?","lista f*('","listas g`M6","listen g","little cQ6e0","live,%","livingR","ljntnoc81oaW",
"ll`hE","llama_)","llamaba 1","llamabanM","llamada jcA","llamado khX90-","llamadosM","llamandoH","llamativos-","llave-",
"llegóE+R","llegando p^]I8,?","llegarXMIA>5","llegaríanV","llegaran 8","llegaron e","llenaTQPKA3,","llenóF","llenandoU","llenarnos 4",
"llenas pk\\QIGFB43#","lleno nbT'","llenos f][YP<%-","lleva>:9,j","llevóKF/(","llevaba 8","llevado 8","llevanWD","llevar?:(","llevaríaI",
"llevarlaA","llevaron hK","llora@","llueva=","lluvia kT","lndvD","lo poa`_\\ZVUTRLJEBA>=940-'ke]WFD1*)(hgM8jK","locaM","localizarloX","loco d",
"locura eM@","loggins g","logical c","logos ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","lograR","logróQK","lograba 8","lograban 0","logrado lM+.","logrando lPL;8",
"lograron mW-*)","logroL","lokos?","londresUj%","lonely\\","long c`BgfRQ","look d","looking l","losJH>=;9842,#gb\\[YWUPNGA<5'nkica^]ZVTSRIEB:/.(&pole`_@10-%mjhXQFDC6fL?+dK3)$7*M","lose b",
"losingX","louE","louisiana#","love lgfba[XUQKB60/,%83]<7E*","lovely a","lover%","loving e6#Q","lrbsv9svuc8 2","ltK","ltsetg48568S",
"lubnaN","lucesK","lucha j(","luciano p","luego 1","lugar le^MD3","lugaresM.","luis)GF=","lujo a\\YNA7","lumczizrhwe=",
"lunaL%","lute-","luzNB=%eC","lw/","lycqvyrzzw0V","lz8djptsaneY","m0k83spgeb8 k","m2/","m4ozctfmh44 g","m4tjsn0qtme g",
"m50q19ivxnmN","m7v55glqria#","ma-","más nd`_\\YXVUMD43/,'polkfcZRQKJIGF:71)&%$mi^TE?6520.*(ha<8geWSL","máter]","máximas*","máximo 3","máximosR","méxicoN","ma1u.",
"módulosC","mónicaN","mañana k","mac 6","madre ol","madres b","madrid?","madrileña jV?","madurez@","maduroL8",
"maestraC","maestría li","maestro n7%","maestros k7","maggieH","magia e]\\[:9Q","magicU","magistral+","magnetismo@","maitreya e",
"majestuosidad 7","makeK6/","mala(","malo)","mambo i","mameknqg1gL","mamma$","manE74$X+","mana=","manantiales 7",
"mandolinasX","mandos l@","manera e:","manhattan i","manilaF","manoPH","manoloI","manos b8","mantenerK+'","mantenerse l",
"mantenido)","manteniendoU","mantienen)","mantuvoF@","manuel'o","manzanera[","múltiplesK","música mlkjgfec^\\YWSQNJFDA>;850/,+)(%ph_URI942-$naZVTK=31.]7*","músicoZRIB(b","músicos nK3j",
"maquillajeL","mar&F","maravilla 3","maravillas k","maravillosa'","maravillosas g7,","maravillosoA","maravillosos i","marcJ","marcóVK/*",
"marcada]YL/","marcado kGC","marcando k","marcar*","marcas ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","mares 5","marga(","mariL'","mariachiG","marinero 5",
"mars 1","marta&","martín@","martínez@","marthaK","martin`","marvin`A90K","masasW","mascar j","masculina e",
"masquerade 7","massachusetts*","massielF","místico eC","matices 72","míticoUK93","matter+","matthew b","matthewman]","maunick 9",
"maurice 3*","mayHU","mayoW(","mayor omi`XL.","mayoría lQ@>","mayores^KE","maysa 9","mcdonald g","me ica^\\UPJEC:754$#MKDB,edL<0/_","mecano@'L",
"mechanicsR","mediados hb_F+","medicinales 9","medinaIC","medio`3(K","mejor kRPI=6e","mejores oPMKH3'&+","melancólica_","melancólicas k","melancólico'",
"melancolíaR","melina.","melodíaI90'","melodías kgYB?4$#","melua>","memoriaWUI20.","menos d?","mensajeraI","menta p","menteT",
"mentes]T","mentiría:","mercado e>5-NA","mercury<U","mercyK","mereceJ","mesN","mesaGZ","mesesF6","mestizajeV?7",
"meteóricaQ","metro 0","mezcla>","mezclanT","mg c","mgb736cazvs@","mgqr4 0","mh&","mhznckwbkam=","mi meLIG=:0'&WJD(.",
"mia$","miénteme?","michael ihgB8","mick_","midnightK$","miedoH","miedos(","miembro lSM","mientras dQ>","miguelG",
"mikeR>","milenioX<","miles p","milk 0","millónZ","million>","millones lZXWSLG:8.*&","mineQ9E","mineápolisT","ministroK",
"minute g","minutosS","mio'","mirabaF","miraclesK","mirarK","mis i%I","miseriaK","mismaMA","mismísimaA",
"mismo eYM-)","mismos'","miss>","mississippi n","misteriosa\\","misticismo e","mitad e","mitificaciónX","mito h$","mitosM",
"mjewkssl8ic:","mjjzyH","mk7xgm72'","ml5yqmmfx4cL","mmmA","mmoau]","mmotazlnpimH","mmydosjjp5u 6","mocedadesM","modaV.",
"modelo^","modernaV","modernoL","moldeando:","momento gcQ*M","momentos lgF","moments c","mondays f","moneyS","montañaN",
"montero@","moonX","moondance n","moonlighting%","morada)","moralK","more fe[8*0","morir j.","moriria&","mornin%",
"morrison n","mortis e","mostrarN","mostrarnos:","motivados 8","motownBh;K","mountainK","movementX","moverse h","moviéndoseQ",
"movida jV?","movimiento`","moyvynkdecc/","mrQ","ms'","msvtomkjdqs*","mtvX&","much 4*#","muchas ona_RQ'","mucho pDAh",
"muchos lkd\\ZMJ7430-%$^","muerte li\\UTK%j0*F","muestraCB90","muestran b4","mujer^PA/L","mujeres^","mullen l","multi na<","multinstrumentista,","mundial^0.)",
"mundialesW","mundo pmle`ZUNMLJI?=;:1.,)^GD","muralla'","murcianoH","muroS$","musa]","musicZRg[N","musical og^[RPNLKFEBA?2.+*'&$jidVn@","musicales ha_PMIF<70&$","musicalmente j_I",
"must nU","muy oke\\[WNJF2,D","mv 6","myA;42,aX#bRQ","mysterious l","mystery\\","n9w0jvyeie8M","nacha(Y","nachoYL","nació bF>#",
"nacida^","nacidoW","nacieron 4","nacimiento a;","nacionalA","nacionales&","nacionalidades-","nadaR.","nadandoJ","nadie-W",
"name le","nâºF","nâº1F","número b\\LC<;6+)lUj","númerosB$l8.","naranjoN","nareaY","narraciónN","natalA","nativa#",
"nativo n","naturalIE7/:","naturales@","naturalezaZ","naturalidad k","navajasL","navidad;","ncvjwzdqtbmG","ne6msf1ghfk i","necesariaA9",
"necesarioB>","necesidadI","necesitado 9","necesitoG&","needK","negraK7V","negro gRP","negrosQ","nelsonT","nen5efe6jsg(",
"neoyorkino e","neoyorkinos i","neumonía(","never#E","neville#","new ponmlkhgfedca_^]\\[ZYXWVUSRQPNMKJIHGFEDCBA@?>=<;:987654310/.-,+*)('&%$#ji`TLb2","nfary9e9jo0&","ngultmh88 c","nhsooozymke;","ni?o",
"niña@","niñeraA","niño aF","niñosE","nicks 6","nieto?","nigelY","nigeriana]","night nb76\\B*","nightfly 2",
"nigor e","nikita 4","nina]","nine>","ningún n","ninguna]WG","nirj5m63oig a","nivelMB'2","njcwH","njxR",
"njz8osfin7mL","nlfi)","nnpygql9piyM","no pnihge\\YVURNLGFA@:843*%$#ld^]MKIC?-)(jW7m0","noche kW","nombre pomeYXVN:*#TMh","nombres ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#L","nominaciones;","nominadaP","nominado<",
"nooemrcws f","normal d","norman`","normasS","norte o>","nos idcbTMGC1.*(fF>9%o","nosotros l(","nostalgia lf","not 0","notable b;",
"notablemente 6*","notables h","notas 9:","nothingT,%","notoriedad m","novenoM","noventa 0","nowUc_Q","nqavfx3nxumB","nqxvmlve62u h",
"nrbjhgx2abq e","nt5rglvmf9o m","ntg50exbbtc`","nube p","nuestraWUR.","nuestras oW","nuestroDR","nuestros lXA>1","nueva lieNM@520#","nuevas 71$",
"nuevo jeYXIEA<650*K","nuevos onhM?$N","numbS","numerosas mW","numerosos lZ:7*)&8$","nunca.I","nuojyuy7riy'","nutriéndose]","nuwsf0pk3lkE","nvhncth8pdsS",
"nvq6vjyte:","nwi9r7xz4F","nyhmzqt8uumB","nynlvwxmrm8@","o24dxeqykgg 7","o41g7woeu6oE","o8X","o8la/","o9f6w6xd1wiY","oaX",
"oído@","oasis?","oawrdidao58>","obús j","obraC","obras$","obsesiva m","obstinadaK","obstructiva j","obtenidos$",
"obteniendo g","obtuviendo>","obtuvieron g-","obtuvo\\","oc n","océano iI","ocasión k","ocasiones pe\\","oceanía^","ochenta`%",
"ocho>","octubre ib","ocupar@","oddity 1","odioso e","odstb4kp91kW","oe3qkbo5sG","oecbz6vtydg:","of cU76420$lia]XR93-+bQP","of8nlfk'",
"oferta)","offT","oficial^","ofrece 9","ofrecerW","ofrecieron g","ogov9k9f17cC","ogw5dhiaeig;","oh[\\","ohje l",
"oidos iA@>","ojala=","ojbyk54rhtw[","ojosK","old[","oletaP","olmkcj03fhw e","olvidarU;2","olvidarnos i","olvidarteL",
"olvido.","om5#","on ecb[UP:741#hXSQK<0B,","onâ€K","once f","oneXUP8/$l","only`f\\","operaciones j","operator]","opkjnridqxq:",
"optimismoY","options ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","opwudidgv1e<","oq5wfx2usl4 k","oqej4lt9lbm?","oqwqg1s0nq4 m","or,l%","orígenes)","orbison\\","orchestra j",
"orden n","ordinary]","oreja d@","original%","originalidadC9%","orleans#","oroWR;","orquesta j","ortodoxoK","ortodoxos?",
"ory f","osT","os6ib1mdsbu 9","oscar fB","oscura_","oscuras\\","oscuro_T","oscuros e","otisAQ","otorgóK",
"otorgadosZ","otra oF5$M","otras pokgeQm","otroYM(","otros ponmlkjihgfedcba`_^][ZYXWVUTSRQPNMKJIHGFEDCB@?>=<;:987654210/.-,+)('&%$#\\A3*L","otvh5cv9z1a%","outX2*","over[R","overture c","ovwk77jrww[",
"owgg5fx7bxyL","own 6","oy9ffrzxz0o,","oyente/","pa;","pá?","página a_","pájaros jI","pálido\\","pánico j",
"pérdidaF","pócima 9","póker j","póstumaQ","póstumas\\","póstumoQ","pablo@","padre 0lK","pahxnwxnjm8M","painQ8",
"pais^NA","paisleyT","palabrasC","palacios k","palmarés a","paloma'","palpableU","panal=","panchosD","pangeM",
"panorama odVNF@?'&","panteraN","púber hK","públicoPI870&","públicos 80%","púrpuraT","para pomlkhcba^\\TMLG@=<98641(eYKJECB>5.*dXIH;)0jNA","paró 0","paradógicamenteK","paradise]",
"parado n^W","paradojaM","parecía eB<(","parecido:","pareciendoQ","pared 5","parkT","parroquiaC","partículares[","parte lkf`ZVKIFEBA6/-U*(",
"partesBS","participar)","particular p_\\QI1,&(","partir l","parton*","pasó j0i","pasaba ljF","pasabanW","pasadoK5","pasando$",
"pasarK","pasarán a.","pasión'%e.","pasionesD","paso ke[N;.WM$","paternaF","paul lj]9R","pavarotti p","pdzcqbgcs74B","pearlsT",
"peces'","peculiaridades 3","pegadizas$","pegadizosX-","peggy]","película dE*","películasW$","penaJF","penetrabaE","pensando;",
"pensarC","pepe?","pequeñaN","períodoX","percepción'","percusión kK","percusionista 3","perdóname.","perdedor j","perder@:7",
"perdidasN","perdidoSLI","perdudarán(","perdura[","perdurará.","perfección n","perfeccionándose j","perfeccionarC","perfectamente]R","perfecto]6*)",
"performing>","periodos 7(","permanecerT","permanecerá 1","permaneceránW","permaneció g","permanecido i","permaneciendoL","permiten$","permitió@",
"permitido i_","permitieron j","permitir h","permitirse 7","pero pnlkihfec^ZYVQNGEBA;8('%$mTMK?<0*","perpetuoD","perroV","personaZKF","personajeN","personal eI7",
"personalesK6","personalidadW/","personas 4","pertenecía`Q","perteneciente mSMF1/","pesadillaQ","pesarYK","pese^UT,","pettigrew 0","pez 5",
"pflE","phil[$","philadelphia_E","philarmonia j","philip 3","pianistaPA4/+","pianoA/'+","pido'","piece 0","pieces 9",
"piel oV,","piensaD","pienso o","pies^","piezas i2","pilarK","pilares^","pinkS","pinochet b","pintorF",
"pintura j","pioneroK","pioneros_\\XE-","pistas hS","pistoletazoQ","pitifulQ","pjfoqxjgbrs f","plásticasI","placerM","plagadaK4",
"planeta-*","planta o","plasmadosA","plasmar(","plastic 1","platero 5","platino<;","plays#","plaza d","plena_",
"plenamenteS","plenoW?9*","pmsqspmtu98A","pmwjk]","poéticasI","pocas a^Q","pocoYXT0h&","pocosRJ2._","podía<7","podían 3",
"podemos iQ:8*%","poderZH/","poderíoN","poderosa e","poderoso]UK)","poderososM&","podido i","podría l[RLIA=","poesíaI4'=","poetaF(",
"pojt93xbsW","police b","polifacética^","polifacéticasG","polifacéticoJ","polpularidadL","ponerK","pop lhc`^][VTPNJIGB@87621/,+&%gd0(YL","popular mb*","popularidad iZI86.*",
"popularizóFE","popularizaron$","por db`ZYTSRQPNHGCBA?=73/+mhfeK<521.-)#ig_I;98'&%$lj]WFn:0(M*","poros(","porqueK","portal ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","portetI","poseeR","poseedor j_E;","poseedoraP",
"poseedorasB(","poseer aB2","poseerlo e","posibilidad 0","posibleG7","positiva 3","positivismo 9","poso-","posteriores e<","posteriormenteP",
"powell j","powerT","ppjnku 6","pqynedi-","prácticamente l2-","príncipe e","precariedadK","precioJ","predilectos%","prefieroI",
"preludio j","premiado iE","premio ne<;","premios nlfbaXWUGA>87+*Z&","prenderse m","preparándonosC","presaA","presenta o","presentándonos o","presentó 2",
"presentado.","presentaraA","presley\\","pretenda 2","pretendía<","pretenderT","pretty\\","pride l","primer g\\VG0-*j;","primera^S*)",
"primeras 9","primero+","primeros[WLF","primoY(","prince^B?T","principal 3","principalmente g-","principeK","principioXMK","principios dcTE",
"pro o5","problema?","problemas fdX8(","procesoI","prodigio a","prodigiosa'","producción d8lj","producciones>","produceMj","producidoY2",
"producirse e","productor jaQMH.$","productora^A","profesionalW","profundaW<","profundamenteV","profundas k?","profundidad k7","profundidadesP","profundoEQ",
"progresivo kcSC","progresoZ","prolíficasT","prometedor j","pronto hW","propia nfeM","propiedad ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","propio nlMH$","propios%","proponeJ",
"proporcionó iX","proporcionaban 3","protestaF","provecho 8","provenienteQ","provocaciónW","provocador 41","proyecciónB","proyectosN","prueba,",
"psíquicos o","psicodelia eS3","psychiatriqueN","publicó 2","publicaciónQ(","publicadosU","pucjagfgdpm k","pudíeramosK","pudiera h","pudieras 8",
"pudoK","pueblo d","puede a_I(","pueden e","puedoL","puerilA<","puerta k'","puertas-","puertoriqueño;","puertorriqueñoJ",
"pulmón(","pulmonar j","punta 5","punto ld\\RK@*j","puntual e","punzante b","pura 3","pureza>(","purgatorioN","puristas%",
"puro d0","purpureT","push ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","puso oA","put<","pvsc5vdrasw k","pxif9e0465eB","pxsgocwifag 1","py5lontuw2a=","pytxtjm 6",
"pzxaqijiiaaZ","q0nnpzt o","q0nviqoeiaw?","q38z'","q6ibmvzopfcN","q80I","q9rqpa@","qbgtsmyftrg%","qde5nmy7wtu/","qecaj62vvec&",
"qf6xu70o73c 6","qgxbbd5bve4#","qjzjhl+","qk b","qkyqntf11eg g","qmvgszwpqN","qrdzjj7 p","qskdxzkz/","qtxlcsvkkvy-","quéJ;iW",
"quédateH","que b\\VHCB5&#oi_[YUTPD><;1+%kfc`G?=4$la]LE2/.-,'mgd^ZXRNJ976pnhI@0*)jQ83A:e(WFMK","quedan kfA","quedar e","quedara c","quedaría aJ","quedarse 3","quedes^","queen$U","queenâ€™s n",
"quería d","querer 9","queridaF","querrás p","quién oMJA>","quien b^I@","quienes k","quieres dC.","quiero okedZMC","quietest c",
"quilates k","quimiI","quinto l)","quiso j","quitóK","quizás le'D","qwzfgxtuoro 7","qzg6kwekg 7","qzte+","r2rsp43rmg 3",
"r8pmsmtxy5s o","récord i.","régimenF","raamE","rabia k","radio[XU0V","rafael'","ragcf0sawjyL","raging%","raices k?<",
"rainT","rainy f","ramasI","ramilleteA","randb h","rango nN","raphaelW","rapidX","raspberryT","rasputin-",
"rítmica 3","rítmico hd","rawlsE","ray]","reK%","real og","realidad i%","realizó\\","realizaciónK","realizandoW",
"reasons 3","rebelde d","rebosan 9","rebosantes k","rechazoK","recogen 3","recompensado n","recompensados 7","reconocidaN","reconocidoZ",
"reconociese:","reconocimiento ibI)&","reconocimientosUNMG:*&","recopiladosQ","recordadas l","recordar d\\M","recordaréis%","recordaremos(","recordarteN","recordsA0",
"recorriendo o","recreo(","recubierta g_","recuerdo 01","recuperarse j","red 0_","reddingAQ","referencia l[S","referente j/","referimosG",
"refinado 2","reflejabaS","reflejaban 6","reflejarlo]","reflejarse/","reflexiónK","reforzadas k","regalado c","regalaron f","reggae p?",
"registered ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","registradoM","registro\\","reina^]","reino>","reinventarse eW","reinvindicación i=","reinvindicativasI","relación o","relaciones l",
"relataF","relataba o","relevancia h","religionX","relojD","remake$","renacimiento j","renal j","renunciar 6","repentina 0",
"repertorioE","reportó b","representantesZ","reproductor 2","resistir k","resistiré)","resistirse>$","respectQ","respectivos ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","respetado(",
"respetados 1","respirarI","restoW","resultado]KA","resultadosN","resurgido d","retirada 8","retiro+","retomarK","retornóN",
"retorno eL$","retraidos$","revoluciónVK","revolucionaron d","revulsivo hA?","reyZJ","rhapsodyU","rhlM","rhythmP","rica k/",
"ricas?","richard f","richieB","rick c","rico nZ2Y","ricosI7","ride f","ridgeley 8","riendaI","riendas h",
"right<_","ring-","riqueza 3(","ritmo plhdYTJH<6","ritmosY=;83-","river+","rivers-","rjlsiassuisK","rl 3","rnb]PE0%",
"road j","robertaA","robertoZM","robin*","rock pnjhec\\XUTSLC;532/.lVNI+&kdH61g)","rockeros)","rocket 4","rodeaba(","rodeado e","rodearlos e",
"rodríguez k","rodriguez d","roger cUR","rogersT*","rojo)","roll nl\\6/+d)","rolling\\?$","románticas m\\","románticoKD","romantic j`L",
"romanticismoZD","romeo=","romero p","rompiendoK","ronca n","ronstadt#","room 2","rosa=k","rosasF@","rosenvingeF",
"rosita&","rossB","rot d","rotaQ","rotundoNL","roxyR[","roy\\","royce^","rrbfqecpj3aT","rrvtagpuzze d",
"rs'","rsecdio9dh0 j","rudeza#","ruiz j","rumba?","rumor k","rumours 6","running g","rvtvssztu50#","rxgg9izhvakF",
"ry0wxgsxdeeU","ryan j","rzq1vkbqyfyE","s1piz1olyps<","s1wfoqxkdq8;","s3fbgocjlpiF","s3q80mk7bxe h","s7jtu$","síA.","séG",
"séptimoM","sólamenteQ","sólas b","sólo i_ZL=:93.)'oQC<$","sólos.","sabía k","sabe o]W","saberA","sabido pH=$'","sabiendoR",
"sabina d","saborRD0","sacar 8","sad 4","sade]","sagrado h","saigon+","sailboat>","salónE/+n","salida]MK",
"salido$","salir ph&","salmonelosis j","salsa?J","salta d","salto h8&","salud(","sam eK","samba i;","símboloT",
"same[","san@(","sanaciónN","sanada e","sananda e","sanar 9","sangre g#","santiagoV","santos=","sanz^J",
"satisfyR","saturday*","saxo`","saxofonista n","say a4B","sb7u5xvnE","scene[","school c>","scmj8F","scottA",
"se pnmlkihgfca`\\[XUSRJECB=<:987620+$#_QM3*%jdA?eKITN(","seña]VGD?","sean$","seasons/","sebas&","secasI","sección ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","secretariaM","sectaK","seda(",
"sedosaE","sedosas 3","seducciónTE","seeE","seems 4","seguidamente(","seguido$","seguir jhdWK$","segunda eS","segundo 2(",
"segundosF","segura@","seguro^M","seis 6","selloK","semanas gLj","semejante n","semillaV7","sencillas$","sencillezZ",
"sencillo g","sencillos&","sendaK@","sensacionales e","sensibilidad pobI>=64(","sensible a_4#","sensibles\\","sensual]'#","sensualidad]K-","sentadoQ",
"sentidas 3","sentidosZYI","sentimental*(","sentimentalmente o'","sentimientoPK#","sentimientos_QFDB('","sentir n^I.","sentirme#","senza p","separación 2",
"separado d","separara c","separarmeY","separaron 0","september 3","septiembre.","ser hd^]\\ZRE@>:/.,)i","sera;","será%","seránN",
"sería)","serían'","seres l","serie fQ%","seriesA","sesenta 0","sesto.","set b","seven e6","sex 8j",
"sexoK8","sexualK","sexy pT)","shake:h","shakira^","shape b","she\\a","sherpa)","shineAS0","shining 3",
"short`","should*","shoulderR","showU","si e_JA:90'D","sido^G0-","siempre kiWV@?:93.$e1j%]","siendo n^\\KI><0.'W","siente e","sientoM",
"sieteN@","siglo nh^ZWUTKE$2","sign e","significa)","significó=","significar(","significara f","sigo e","sigue nI0*","siguen a2*",
"siguió e","silencioN","simónV","simbolizanD","simone]","simpatía%","simplemente idW","simples f","simply 0_","simplyred_",
"sin lieRMKI=:7-)'%]6F","sinatra?.","sinfónico cSC","sing f3","singleX0","singlesQ","sino)","sintetizador[*","sintonía%","sinuoso#",
"sir 4a","sister e","sitio(","sitiosL@","sittinQ","sj$","sjmmaigigbg f","sk(","skyS","skyway 2",
"slave[","slowlyF","smooth 0]","snvnvlayV","so 74","soñaban h","sobranJ","sobre ohga\\ZYVGE;4l_&","sobredosisT","sobrenombre n",
"sobrevivir(","sobreviviréN","sobreviviremosM","sobrino?","social/K","sociales o","sofisticado 2","sol o","solapa g","solas b",
"soldadito 5","solista 632","solitario hbPKB8(#2","soloGC","soltura h%","sombra)","sombrasK","somebody bU*","something:_","son nmjihfecba`^]\\[YWVTSPNMLKJHGFEDCA>=<;876541/.-+(&%#pk_ZXURQIB@?9320,*)'og:$ld",
"sonando@*","sonar 20","song c43","songs 4","sonido nlgc_ED7620,)SLH:9$","sonidos f][T@95-V>3:","sonora p3*","sonorasA0(","sonoridadI","sonyN",
"sopaH","soplarI","sordomuda^","sorpredentemente*","sorprendiéndonos n","sorry 4","souZ","soul haTHE<:931#n_]PKA;,igeQR70","soulmanK","soyZoW",
"space:1","spandau`","speak i","spector$","spell<","spencer]","spice i","spirito p","squeezeR","sr k",
"sr2yo>","st0ffuqk3ouZ","standing 4","star 3","stars_","start+","started_","statonA","stayAe","stayin*",
"steely 2","stepA","steve`Q","stevieK:96a","steviewonder a","still 94/l","sting pb","stivel dH","stone\\$<3","stones?",
"stopU#Q6","story`","stranger c","stream*","streetE","streets lg","streisand*","strongQ","stuart]","stuck,B",
"su kfcbaZUPD=:7-mlg_YH?83.'od`VNMJGEA@>;65/,&^\\XLIFCB40+%$#ph]SR<9*WnT2e1iQ(Kj","suaveG6","suaves f5","suavizaciónH","sube o","sucedido k","sucias)","sucumbir 8","sudafrica^","sudamericana b",
"sueñoX=","sueciaL","suecos$","sueltaI","suerte^(Y","suficienteL","sugerente]-2","suicidaron e","sujetaba 0","suma 3",
"sumamos 9","sumarF4,)","sumarle n","sumergasP","sumieron 8","sumne b","sunP74","sunny-","sunrise_","sunshine a",
"super d<","superación(","superado i(","superarF","superconocida 3","superfluas>","superior'","superlópez d","superstar f.","superstition a",
"supertramp c","supo 7","supusoU(","sureñoH","sureñosI","surgían\\","surgen k","surgió e2&","surgido k$","surgieron g`",
"surrealistasI","sus pomkjgfcaZYVUTRQMGEDB?>;651/.+'nlihed`_[PLIHFCA932)&%^]\\XWNJ@=40,#b<:7-*SK8$(","suspender^","sustituir*","suz4@","swbgjzf3mb0 g","sweet/","sweetest]","swing i","sxjialnmpnkA",
"sydS","t0on9tbnkd8V","t2nujwmmhkgN","t3w3izq5sdm g","t7bkgteqgsmZ","t8T","tí o","tándemE64","técnicaP","términoX",
"tómameM","ta42xu2uxla-","taboo]","tacones j","take c#","takes$","takin g","tal le","talón^","talante 4",
"talento bTRJBA<1jQ","talentosA7","tallaR","también m^TR?<10%","tambienE3","tammiK","tan hg`\\PLGA<;30/j]Q.%","tango 6","tanta.","tantas(",
"tanto oiheMLJC%","tú o^5.mGDCM","tapestry/","típica b","tarde h2","tarqueH","tatareadoM","tatuó*","título 2","taupin 4",
"taylorU","tcqN","tdh1iwb33k j","te pgZRPGF;9(&miMJ^","tearsP","technology>","teclados k","tecnoL","tejado 5","telón>",
"tele k","televisión f","tell#","tema oj_XL7","temática l","temas if^]\\PNMLB60/'%j<8*","temperamento&","temptedR","ten)","tenía l<",
"tendencias 1","tendernessQ","tendido o","tenemos n","tener e6)","tengoJ;","tenido h","teniendoW6","tenor\\3","tensiones 6",
"tentarD","tequila d","tercer e`&","terence 0e","ternura fF>(","terrellK","tesoros(","textosI","tez_","than[*",
"that 43","thatâ€™sQ","the ne`[RP?>962-*$fba_]TA8+iUKlcQB7gXS#\\4h3","them bS>","theme ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","thereE9h","theseQ","they bf4","thing p9_E","this[7%",
"thomas b","thriller i","through`K","ti oY;","tiñóT","ticket f","tiempo kjeSM5$I","tiempos eML6*+","tienda e","tiene ge]RJ^C",
"tienen 5","tiernoD","tierraH","tigre j","tildandoR","tildar_","tim i","timbre p^RG#","timeX","times#",
"tino j","tinte_","tintesX","tipoZ","tirados j","titubeantesK","titulada pE","titulado eX;*&","tizaV","tkdmiyrmbik#",
"tkulh9otlz4'","tmvapchumpeP","to a`\\[SA<:/*heUQKE840igf","tocan_","tocandoC","tocar eA","tocarteV","toda]ZVRQMK75/*'","todas on20:","todavía eaQF",
"todo pjhfa_XVJBA?;:82-)'&ong\\ZYMGFEDC=4.liK","todos polkjihgfdba`_^]\\[ZXWVUTSRQPNKJIHGFEDCBA?>=<;:9875421/.-,)'&$#nmcYML@630*(%e+","together%","tok p","told nA","tom p","tomando h","tomorrow/","tonalidadR","tone i",
"tono\\","tontoV","tony`","too:*Q8/","top)","topamos 9","toque pne_+","toquesI2","torrojaL","tortura^",
"tour#","toxasfkzzmq n","tozzi m","tráfico k","trágico j","trabajo 06","trabajos ondcA6&e(","trademark ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","tradicional n6","tragedyJ*",
"train eg","tranceC","trans 2","transcurría e","transcurreF","transfer i","transformaN#","transformación h","transformado h","transformaron e",
"transgresor 1","transmiteJF","transmiten d","transmitir nR","transmitirnos;","trío*","trapecioI","tras o^\\YNLKFE@>21)T0","trata l","tratabaK<",
"través onm]S(&#","travesI*","trayectoriaUKF4+","tree l","trent 0e","tres fYWSNFD","trianaICk","trickle i","trioD","tristeZ",
"tristemente-8","tristeza<6(","triunfaJ","triunfarNM","triunfo^$","troncoso k","true`","trulyB","truncada(j","trust+",
"truthA","tryQ8","tuT=(kF","tuktqs2zetyY","turn 7","tusG@","tutelados'","tuvieron fH","tuvo`\\NK","tv%",
"tvf8gyhbir0/","tvnymwpdT","twilight i","txcdtumlqji l","u2 l","u9ba6ffgmjiK","ua ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","uaqslwjxiwcZ","ucgd9dt12c0 6","udj'",
"udkbzka9l4s l","udwpprra6l8V","uezagfk9o8q j","ufupu2wuy;","uirzd0/","ujwqinpt4qiG","ulster n","umberto m","un pmd`SPJHGEB</'#ca^]\\TRL?;:73-,oif_YXUQIC9642.+*)%khbZWM=(lNA$FDgenK80j","una onb`\\[SIGCB<961-+&%mlhgfa_YUTA@>:50.$pj]VRNLH843*)ZQPME2/ke('FK",
"unía 7","unas keNMDB","uneL","unfzfe8f9ni$","unicef^","unida'","unido oG>","unidos iWM","unir%","unirse)",
"universal oZ","universales p","universalizando g","universidad n","universo&","uno pomkife_^ZSRQMLE@531/-+*'&%gaK76","unos kfMH>3-&K","unpmoab4y8uQ","upKAi","ups4ylw642s.",
"uptown+","uqyy4nglewu<","ur96bakqg28?","urangaM","uranoW","uribarriM","usS$","uunt4)","uusbx3pptxy p","uvi j",
"uvqyambgK","uw90wihrvzaM","uwlnpooS","uxvcr22rm 0","uyfm 4","uz83qy50a_","va^J>","válido p","vacio e*","vídeo ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"vajx8edq(","valíaJ","valióJ","valli*","valorado 7","valorar\\","vamosY","vampires e","van dY@)n","vandellasK",
"vanguardia j","vanguardista 1","variable n","varias g_WNGA97+'j","varios njgXKHEB>85/","vítor o","veJ/f","veían/","veces kW>","vega?Y(",
"veinteañeraA","velloF","venD","vena j_","venía g","venas gP#","vendaval f","vendedorM","venderWSL:8","vendida*",
"vendidasX&","vendido eLG*","vendidos lZ6/.","venenoV","venideros h","venta`","ventas g^N)","vente?","verVQH","veránN",
"verano@&","verdaderamenteT","verdaderoT","vergelD","verleQ","versátil%","versátilesG","versión'","versiones mM<7","vez omleUNM5,*(",
"vffbqdv2clcN","vió(j","viajeY4","vibrantes 3","vibrar=","victor o'","victoria(","vida pljf]QMJIFED;532.*)K","vidasW0","video j",
"videoclips:","videomúsica ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","videomusica ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","videos ponmlkjihgfedcba`_^]\\[ZYXWVUTSRPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#Q","vie#","viejas e","viejo?","viejos$","vientoX","vigor 0",
"vigorosaU)","vii8phlo2pkN","vinilos$","vinoP","virtual:$","virtuosa%","virtuosoY;7%","visa=","visadoM","visión l",
"visionario nK","vista*","vistosidad-","visualizarK","vital:","vitalidadY3","viu4iwA","vivaW2)","vivas a","vive 5",
"vives^","vivió-","vivir jJ.","vivoE1-","vjk40bq8aasJ","vjrczoyxa98,","vkdqyo a","vl8nujdtlia 0","vocal jigeRN0#P","vocales i^N@7M",
"vocalese i","vocalista 6&#@","vocalistasQP9-","voces omlRHGDA90'&M$","volN","volóP","volcán_","volo p","voluntad^","volviendo*",
"volvieran 6","vos&","voz pngf`_^]\\[ZPJIGEA<;8631,&#keK>.'WRQ%","vpuQ","vqx2xn7ti f","vrr4f2mR","vt9t3q*","vu^","vuelo'","vuelvo d",
"vvy0zvqcl7e 2","vxogqn1a7be[","vyltbsyvjbeY","waka^","walkerY","wallS","walter 2","wannaK","wantU8h","warwick*",
"water g","waterloo$","watersR%","way c63","ways l","wbe1qlvygqsV","wcwhzc8s2i]","wdnxyjkzq80 9","weXUB+%f0","weather 2",
"weaver*","web a_","well e","wembley%","were>S","wham 8","what c>2,lgK","when`E:","whenever^","where l0",
"wherever^","whgbwch6ipe*","whisper 8","white 3","whitesnake)","who e","why n4","wiiqtwuiv54J","wild n","wildcard e",
"willU/","wind 3","window ponmlkjihgfedcba`_^]\\[ZYXWVUTSRQNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#P","winner$","wire#","wishES","wishing e","with<4l","without l","wk5wlq4pbfgS",
"wkqbtldfya0W","wlsbl0yuzcc^","wm7 6","wojzo02tmckG","woman=\\P/*","won,","wonderK:9a","wonderland 3","wonders 6","wordN4",
"worldXB23","worry 9","would 0","wrong<","wsmryfsy 3","wsncT","wvsa2ceiq7uL","wvvxcwp3v8y 5","wwb779bdmy4)","www a_",
"wxapadhj0r8Y","wxhsb7pdpbi 3","wyclef^","wzldhf1jpiwC","wzrxc68gnjqQ","x25f3>","x6qzn9xiuoeK","x6vn3zkekf4D","xabi@","xejlohdbvee$",
"xers7g3N","xfrguyw1v8s$","xfudbqcplj4 1","xh l","xi2egyzo2pw n","xm a@","xpqqju7u5yc*","xv1dk9tshio a","xw1fxl3s7bk h","xx nhZUTE$2",
"xxb0nzhvj5m%","xxiW","xyX","xzK","xzologgfwp0=","y3ywicffoj4 6","y7dgdrp3pmsK","ya gcXC>0)('h","yc'","yd3tq5f9gfkK",
"yd8dcgplp-","ydd m","yeah[","yearsR","yesterday f","yfqqz6tu3fu d","ygu1bc4c4@","yn7hxmzxqv8`","ynihshyaig0 e","yo mdDAZW",
"yoaoR","yopqnpbl c","york b0i","you n[KJ96lfb`_\\Q>:,*#a<0heSEB/","young:1","your]E86he74*","yoursA","youtubePA9ponmlkihgfdcba`_^]\\[ZYXWVURQJIHGFDCB?>=<;8754321/.,+*)(&%$jeTSNMLKE@:60-'#","yqkZ","yxio6nrgva4 i",
"z0qw9p 4","z1k67uaa b","z7j1uogi02a 4","za8he50xjee e","zalssqlxxyi@","zapateroI","zbnjo88kup8 1","zencru8 f","zenitL","zf4kzl9I",
"zh3y9rwmtri h","zhqpm+","zhwvbirqd2s 4","zitrwccrqms i","zm j","znbj4ev 8","znsxeeveD","zonaJ","zone i","ztcu7mctuts_",
"zubiagaM","zucchero p","zxspivc2gnw p","zzk?");
var FN=Fs.length, WN=Ws.length, BW=window.opener;
var AR=new Array(FN), AI=new Array(FN), M2=FN>1563;
function Let(c){return c>='a'&&c<='z'||c>='0'&&c<='9'||c>'';}
function Dig(s){
 for(var i=0;i<s.length;++i){
	var c=s.charAt(i);
	if(c>='0'&&c<='9') return 0;
 }
 return 1;
}
function C(l){
 location.href=l;
}
function AW(s){
 var i,n;
 for(i=0;Let(s.charAt(i));++i);
 if(s.charAt(i)==' ') ++i;
 for(var m=1;i<s.length;){
	n=s.charCodeAt(i++)-35;
	if(n<0) n=(n+20)*92+s.charCodeAt(i++)-35;
	else if(M2) n=n*92+s.charCodeAt(i++)-35;
	AI[n]+=m++;
 }
}
function MK(s,n){
 var i;
 for(i=0;i<FN;++i) AI[i]=0;
 s=s.replace(/\*/g,'[^ ]*');
 s=s.replace(/\?/g,'[^ ]');
 s = '^'+s;
 for(i=0;i<WN;++i) if(Ws[i].search(s)==0) AW(Ws[i]);
 for(i=0;i<FN;++i) if(n) AR[i]*=AI[i]; else AR[i]=AI[i];
}
function MT(){
 var c,i,n,t="",ss="",s=document.forms[0].s.value.toLowerCase()+' ';
 for(i=0;i<FN;++i) AR[i]=M;
 for(i=n=0;i<s.length;++i){
	c=s.charAt(i);
	ss+=(c=='<')?"&lt;":c;
	if(Let(c)||c=='*'||c=='?') t+=c;
	else {
		if(t.length>L&&(D||Dig(t))) MK(t,n++);
		t="";
	}
 }
 t='La búsqueda para "<b> '+ss+'</b>".<p>\n';
 for(n=0;;++n){
	var m=0,im=-1;
	for(i=0;i<FN;++i) if(AR[i]>m) m=AR[im=i];
	if(im<0){
		if(n==0) t+="<div align=center><p><b>No hay resultados.</b></div><p>\n";
		break;
	}
	AR[im]=0;
	t+=("<b>"+(n+1)+".</b> <a href='javascript:C(\""+Fs[im].fn+"\")'>"+Fs[im].ft+"</a><br>\n"+Fs[im].fd+"<p>\n");
 }
 return t;
}
function NS(){
 if(document.getElementById) document.getElementById('txt').innerHTML=MT();
 else document.forms[0].submit();
 return false;
}
function SS(){
 if(location.search){
	var o="€,??????????????????????????????????????????????????????";
	var t="";
	for(var i=3; i<location.search.length; t+=c) {
		var c=location.search.charAt(i++);
		if(c=='+') c=' ';
		if(c=='%') {
			var v=parseInt(location.search.substring(i,i+2),16);
			if(v<128) c=String.fromCharCode(v);
			else c=o.charAt(v-128);
			i+=2;
		}
	}
	document.forms[0].s.value=t;
 }
}
//-->