<!--
function f(fn,ft,fd){
 this.fn=fn;
 this.ft=ft;
 this.fd=fd;
}
var Fs=new Array (
new f("//videos.videomusica.es/Aaron.Neville.html","Videomúsica sección videos, Aaron Neville","Videomúsica, información y videos. Aaron Neville"),new f("//videos.videomusica.es/Abba.html","Videomúsica sección videos, Abba","Videomúsica, información y videos. Abba"),new f("//videos.videomusica.es/Al.Jarreau.html","Videomúsica sección videos, Al Jarreau","Videomúsica, información y videos. Al Jarreau"),new f("//videos.videomusica.es/Amaral.html","Videomúsica sección videos, Amaral","Videomúsica, información y videos. Amaral"),new f("//videos.videomusica.es/Ana.Belen.html","Videomúsica sección videos, Ana Belén","Videomúsica, información y videos. Ana Belén"),new f("//videos.videomusica.es/Antonio.Vega.html","Videomúsica sección videos, Antonio Vega","Videomúsica, información y videos. Antonio Vega"),new f("//videos.videomusica.es/Baron.Rojo.html","Videomúsica sección videos, Barón Rojo","Videomúsica, información y videos. Barón Rojo"),new f("//videos.videomusica.es/Bee.Gees.html","Videomúsica sección videos, Bee Gees","Videomúsica, información y videos. Bee Gees"),new f("//videos.videomusica.es/Billy.Joel.html","Videomúsica sección videos, Billy Joel","Videomúsica, información y videos. Billy Joel"),new f("//videos.videomusica.es/Bobby.Caldwell.html","Videomúsica sección videos, Bobby Caldwell","Videomúsica, información y videos. Bobby Caldwell"),
new f("//videos.videomusica.es/Boney.M.html","Videomúsica sección videos, Boney M","Videomúsica, información y videos. Boney M"),new f("//videos.videomusica.es/Camilo.Sesto.html","Videomúsica sección videos, Camilo Sesto","Videomúsica, información y videos. Camilo Sesto"),new f("//videos.videomusica.es/Carole.King.html","Videomúsica sección videos, Carole King","Videomúsica, información y videos. Carole King"),new f("//videos.videomusica.es/Charles.Eddie.html","Videomúsica sección videos, Charles & Eddie","Videomúsica, información y videos. Charles & Eddie"),new f("//videos.videomusica.es/David.Bowie.html","Videomúsica, David Bowie","Videomúsica, información y videos. David Bowie"),new f("//videos.videomusica.es/Donald.Fagen.html","Videomúsica sección videos, Donald Fagen","Videomúsica, información y videos. Donald Fagen"),new f("//videos.videomusica.es/Earth.Wind.Fire.html","Videomúsica sección videos, Earth Wind & Fire","Videomúsica, información y videos. Earth Wind & Fire"),new f("//videos.videomusica.es/Elton.John.html","Videomúsica sección videos, Elton John","Videomúsica, información y videos. Elton John"),new f("//videos.videomusica.es/Fito.Fitipaldis.html","Videomúsica sección videos, Fito & Fitipaldis","Videomúsica, información y videos. Fito & Fitipaldis"),new f("//videos.videomusica.es/Fleetwood.Mac.html","Videomúsica sección videos, Fleetwood Mac","Videomúsica, información y videos. Fleetwood Mac"),
new f("//videos.videomusica.es/George.Benson.html","Videomúsica sección videos, George Benson","Videomúsica, información y videos. George Benson"),new f("//videos.videomusica.es/George.Michael.html","Videomúsica sección videos, George Michael","Videomúsica, información y videos. George Michael"),new f("//videos.videomusica.es/Incognito.html","Videomúsica sección videos, Incognito","Videomúsica, información y videos. Incognito"),new f("//videos.videomusica.es/Jamiroquai.html","Videomúsica sección videos, Jamiroquai","Videomúsica, información y videos. Jamiroquai"),new f("//videos.videomusica.es/Jose.Feliciano.html","Videomúsica sección videos, José Feliciano","Videomúsica, información y videos. José Feliciano"),new f("//videos.videomusica.es/Joss.Stone.html","Videomúsica sección videos, Joss Stone","Videomúsica, información y videos. Joss Stone"),new f("//videos.videomusica.es/Juan.Luis.Guerra.html","Videomúsica sección videos, Juan Luis Guerra","Videomúsica, información y videos. Juan Luis Guerra"),new f("//videos.videomusica.es/Katie.Melua.html","Videomúsica sección videos, Katie Melua","Videomúsica, información y videos. Katie Melua"),new f("//videos.videomusica.es/Ketama.html","Videomúsica sección videos, Ketama","Videomúsica, información y videos. Ketama"),new f("//videos.videomusica.es/La.Oreja.De.Van.Gogh.html","Videomúsica sección videos, La Oreja de Van Gogh","Videomúsica, información y videos. La Oreja de Van Gogh"),
new f("//videos.videomusica.es/Laura.Izibor.html","Videomúsica sección videos, Laura Izibor","Videomúsica, información y videos. Laura Izibor"),new f("//videos.videomusica.es/Lionel.Richie.html","Videomúsica sección videos, Lionel Richie","Videomúsica, información y videos. Lionel Richie"),new f("//videos.videomusica.es/Los.Modulos.html","Videomúsica sección videos, Los Módulos","Videomúsica, información y videos. Los Módulos"),new f("//videos.videomusica.es/Los.Panchos.html","Videomúsica sección videos, Los Panchos","Videomúsica, información y videos. Los Panchos"),new f("//videos.videomusica.es/Lou.Rawls.html","Videomúsica sección videos, Lou Rawls","Videomúsica, información y videos. Lou Rawls"),new f("//videos.videomusica.es/Luis.Eduardo.Aute.html","Videomúsica sección videos, Luis Eduardo Aute","Videomúsica, información y videos. Luis Eduardo Aute"),new f("//videos.videomusica.es/Luis.Miguel.html","Videomúsica sección videos, Luis Miguel","Videomúsica, información y videos. Luis Miguel"),new f("//videos.videomusica.es/M-Clan.html","Videomúsica sección videos, M-Clan","Videomúsica, información y videos. M-Clan"),new f("//videos.videomusica.es/Manolo.Garcia.html","Videomúsica sección videos, Manolo García","Videomúsica, información y videos. Manolo García"),new f("//videos.videomusica.es/Marc.Anthony.html","Videomúsica sección videos, Marc Anthony","Videomúsica, información y videos. Marc Anthony"),
new f("//videos.videomusica.es/Marvin.Gaye.html","Videomúsica sección videos, Marvin Gaye","Videomúsica, información y videos. Marvin Gaye"),new f("//videos.videomusica.es/Mecano.html","Videomúsica sección videos, Mecano","Videomúsica, información y videos. Mecano"),new f("//videos.videomusica.es/Mocedades.html","Videomúsica sección videos, Mocedades","Videomúsica, información y videos. Mocedades"),new f("//videos.videomusica.es/Monica.Naranjo.html","Videomúsica sección videos, Mónica Naranjo","Videomúsica, información y videos. Mónica Naranjo"),new f("//videos.videomusica.es/Oleta.Adams.html","Videomúsica sección videos, Oleta Adams","Videomúsica, información y videos. Oleta Adams"),new f("//videos.videomusica.es/Otis.Redding.html","Videomúsica sección videos, Otis Redding","Videomúsica, información y videos. Otis Redding"),new f("//videos.videomusica.es/Paul.Carrack.html","Videomúsica sección videos, Paul Carrack","Videomúsica, información y videos. Paul Carrack"),new f("//videos.videomusica.es/Pink.Floyd.html","Videomúsica sección videos, Pink Floyd","Videomúsica, información y videos. Pink Floyd"),new f("//videos.videomusica.es/Prince.html","Videomúsica sección videos, Prince","Videomúsica, información y videos. Prince-The Artist"),new f("//videos.videomusica.es/Queen.html","Videomúsica sección videos, Queen","Videomúsica, información y videos. Queen"),
new f("//videos.videomusica.es/Radio.Futura.html","Videomúsica sección videos, Radio Futura","Videomúsica, información y videos. Radio Futura"),new f("//videos.videomusica.es/Raphael.html","Videomúsica sección videos, Raphael","Videomúsica, información y videos. Raphael"),new f("//videos.videomusica.es/Rem.html","Videomúsica sección videos, R.E.M.","Videomúsica, información y videos. R.E.M."),new f("//videos.videomusica.es/Rico.html","Videomúsica sección videos, Rico","Videomúsica, información y videos. Rico"),new f("//videos.videomusica.es/Roberto.Carlos.html","Videomúsica sección videos, Roberto Carlos","Videomúsica, información y videos. Roberto Carlos"),new f("//videos.videomusica.es/Roxy.Music.html","Videomúsica sección videos, Roxy Music","Videomúsica, información y videos. Roxy Music"),new f("//videos.videomusica.es/Roy.Orbison.html","Videomúsica sección videos, Roy Orbison","Videomúsica, información y videos. Roy Orbison"),new f("//videos.videomusica.es/Sade.html","Videomúsica sección videos, Sade","Videomúsica, información y videos. Sade"),new f("//videos.videomusica.es/Shakira.html","Videomúsica sección videos, Shakira","Videomúsica, información y videos. Shakira"),new f("//videos.videomusica.es/Simply.Red.html","Videomúsica sección videos, Simply Red","Videomúsica, información y videos. Simply Red"),
new f("//videos.videomusica.es/Spandau.Ballet.html","Videomúsica sección videos, Spandau Ballet","Videomúsica, información y videos. Spandau Ballet"),new f("//videos.videomusica.es/Stevie.Wonder.html","Videomúsica sección videos, Stevie Wonder","Videomúsica, información y videos. Stevie Wonder"),new f("//videos.videomusica.es/Sting.html","Videomúsica sección videos, Sting","Videomúsica, información y videos. Sting"),new f("//videos.videomusica.es/Supertramp.html","Videomúsica sección videos, Supertramp","Videomúsica, información y videos. Supertramp"),new f("//videos.videomusica.es/Tequila.html","Videomúsica sección videos, Tequila","Videomúsica, información y videos. Tequila"),new f("//videos.videomusica.es/Terence.Trent.html","Videomúsica sección videos, Terence Trent D'Arby","Videomúsica, información y videos. Sananda Maitreya-Terence Trent D'Arby"),new f("//videos.videomusica.es/The.Carpenters.html","Videomúsica sección videos, The Carpenters","Videomúsica, información y videos. The Carpenters"),new f("//videos.videomusica.es/The.Doobie.Brothers.html","Videomúsica sección videos, The Doobie Brothers","Videomúsica, información y videos. The Doobie Brothers"),new f("//videos.videomusica.es/The.Jacksons.html","Videomúsica sección videos, The Jacksons","Videomúsica, información y videos. The Jacksons"),new f("//videos.videomusica.es/The.Manhattan.Transfer.html","Videomúsica sección videos, The Manhattan Transfer","Videomúsica, información y videos. The Manhattan Transfer"),
new f("//videos.videomusica.es/Tino.Casal.html","Videomúsica sección videos, Tino Casal","Videomúsica, información y videos. Tino Casal"),new f("//videos.videomusica.es/Triana.html","Videomúsica sección videos, Triana","Videomúsica, información y videos. Triana"),new f("//videos.videomusica.es/U2.html","Videomúsica sección videos, U2","Videomúsica, información y videos. U2"),new f("//videos.videomusica.es/Umberto.Tozzi.html","Videomúsica, Umberto Tozzi","Videomúsica, información y videos. Umberto Tozzi"),new f("//videos.videomusica.es/Van.Morrison.html","Videomúsica sección videos, Van Morrison","Videomúsica, información y videos. Van Morrison"),new f("//videos.videomusica.es/Victor.Manuel.html","Videomúsica sección videos, Victor Manuel","Videomúsica, información y videos. Victor Manuel"),new f("//videos.videomusica.es/Zucchero.html","Videomúsica sección videos, Zucchero","Videomúsica, información y videos. Zucchero"));
var L=1, D=1, M=1, Ws=new Array (
"03itdgK","05lssyqaenoH","07dtavu9rjwI","0kcet4appqR","0omja1ivpx0T","0q0ubkwcueoC","0qtrcbaqtymE","0u30mubqcaw c","10 gW1","100G8",
"10ctifjeojq c","12 h(%","127555569 onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","14 kGn","15A","150Y","158fwcg27zeP","16 hV<","175.","190 k",
"1927#","1941#","1943V","1951 a","1965P","1967P","1969M","1970 fT","1971/","1972 h",
"1973M+","1975R","1976E","1977B","1978 f","1979 l_R","1980 l'","1981 c;","1982;2","1984F%",
"1985 h","1987 86","1991W","1992:","1993 m","1994N","1995]","1996@","1998L65&","1999 m",
"1by d","1coyvkedf00 b","1jl8a20hR","1oedfjxzg5g l","1qrn8c24a[","20 7","200*","2002&","2003 m>*","2006E",
"2007@","2009A(","2010]","2011W","2012*","2014 hM","2016SF81","2017%","2018 onmlkjihgfedcba`_^\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#]","2019N6.",
"2020 onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGEDCBA@?>=<;:9876543210/.-,+*)('&%$#F","21S","22 k","24 0","25L8","26RP","275iksf2fqm 5","28@","2ao901rx m","2ezwa?",
"2hhzmrmahxu<","2kvivewM","2nf9dwlhvoc m","2q9mtjokc4a h","2tj8v2bmftyQ","2y2g6dciys8.","30,","300VR","35:$","365 0",
"3aymegoesae%","3qad8385pxa)","3v62a2j d","3x1%","40MD=","46rifqdimea l","46vgynndfziO","46y8A","49gy4oslg40_","4cagg2qmaay.",
"4dwcpqjcw3y<","4e<","4e4>","4jkis37a2je:","4k9f;","4n8jjod1h04@","4qszlr6pnX","4tyv2phg89a\\","4yg[","50 m`V4",
"52.","57ykv1d0qeeK","5qn2sjsqaje(","5roiwW","5ww-","5yc k","60 gVKFC71","6cpaoyri8d4^","6cs3pvmmv0e 8","6dedzscgbsq k",
"6f4bwqffS","6g8tmiqxnec 1","6inwzoooxru e","6kgvcwcb6ik d","6lfxgbb4ugu m","6pprs1mc4sc'","6yok4d53s5uF","6ywytbQ","6yychgx1fmw+","6yziz1flaws 8",
"6z/","70 njecRMKB:7/-*l63","7bdwP","7bmahc&","7bwwo7ctg10B","7cqheq4 c","7eyihajlt0g,","7kae99gY","7mro:","7oZ",
"7olcdlxgc0u 0","7oqnqy9bfj8N","7vstpwvmqgi&","80 kgdcba^\\WUSQOMLIGB?*l)","89am8kc@","8cufkd:","8etpsn3qdeiM","8gewtiH","8nxvha7k i","8pkju1u8zk0 o",
"8qz8fqmtsjy 5","8qzi l","90 c\\XWSQL+I","92,","9aykowwrf b","9b4f 6","9c5ypiq3lqi-","9cinkkn4$","9klbkgcvz b","9mfcbhk02s 0",
"9vjj6j7gxpy`","9xdnsS","9yktv>","álbum olkfdUKFA6/(hWR*0","álbumes jbTLK@><","álgidoQ","ángelesK","ánimoQ","â¡qué b","árabe]",
"árabesI","áspera<","â¡tan\\","â¡utópicoS","â¿S","â¿o*","ã“peraN","â€œwhatâ€™sK","â© onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","él jdVK621",
"época lPKB%","éste k","éxito khgfeca[WRNMLJIH@;80/.-)'n6l]","éxitos c]WVNKFE<43-+%$g","â® onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","ã‰l oF;","ã‰sta k","ã‰xitos^","ãlvaro@","a152e46obm0 7",
"ópera.","órganoC","a8gj9vvuh 6","a8rwz6zbjse]","añadieron_","añadir h","año lhc_YWTNMF>*'&]@;6","años nmica`^]UPKJIHGED?>:7641/.,$lkdZXNMA<30-Vg","aún d","aaron#",
"abandonóF@1.","abarcar h","abba$","abbey i","abc g","abeja=","abierta\\","abiertoI","abiertosI","aboutE>",
"abríaK","abrazarte n","abre j","abrióI5-","abriendo?","abrilSF","absolutoK","abuelo n","acabó j(","acabando i",
"acabar a","acabaron e","acabo 5","acústicosU>","acaparado&","acariciaY","accidentalS","accidente jiP","according d","aceite m",
"aceptar\\","acercándose 0","acero>","acertada m","acid 9:","ackymdc4 k","acompañadas/+","acompañadoS=8","acompañamiento\\","acompañando^",
"acompañar)","acontecíaK","acordesM","acqqvt7itp8Y","acreedor m","actúa\\","activa d","activarA","activo`TF&","actriz]'",
"actuaciones 3)i","actual`*","actuales 0","actualidad])","actualmente c","actuar h?","acudir$","acuerdo 7","acumular:","acurrucarse 3",
"adam k","adamsO","adaptándolo 0","adaptables@","adaptaciónL'","adaptacionesL","adaptarse 1","adecuado 8","adelantado i","adelantarse 1",
"adelanteN","adelanto g","además m]M","aderezado&","adiós;","adiccionesK","adictivas jf","adjetivos`","admiraciónK","admiradores k?",
"adolescente>","adoptóW","adoradores$","adoroD","adquieran k","adquirióE","adquiriendoA","adu\\","afamadoE","affirmation 7",
"afgt7trnr2k j","afloran^","africa]","africana#","after$3","agapimú'","aglutinarK3*$","agnetha$","agradable-","agradables\\",
"agradecer m","agrandarV","agresiva 8","aguasJ","aguirre&","agustito?","ahí$","ahoraJ*","ainK","aireL",
"airearonX","aires*","ajopt7zjar0>","akpebr4gseu%","al mljh\\XTRKIHCBA=<850+*($kdb^OL@?;:6/fZMJF3%nQ)","albaF","alberti'","alcalá'","alcance%","alcanzaN",
"alcanzóK6","alcanzable^","alcanzado k","alcanzando aN<","alcanzar.","alcanzaron lhge*L","alegatoF","alegra]","alejandro]J","alejo cH",
"aleluyaF","alemán-","alemaniaL","algoQ#.d","alguien 1","algunaYRM0","algunas j<)$","algunos mNK21.","aliño 8","alive*",
"all onmlkjihgfedcba`_^]\\ZYXWVUTSRQPONMLJIHGFEDCA@?>=<;:986543210/.-+*)('&#K7$[B,%","allí d","allá nVJ]","alma omf^QPMFED;9/'\\#","almasPN","alo7u0sP","alone a","alrededor\\","alright gf","altasI.(",
"alternativoW","alto hgf_[L82","always m9","américaV","amados a","amaia@","amamamos b","amante.","amaral&","amarillo]",
"amayaM","amazing 8","ambiciónK","ambiciosaS","ambientalK","ambiente?","ambigua k","ambiguo 1","america b","americana f#",
"americanasA","americans 1","amigo 2","amigosY","amo l","amorYMFC=;0jN'nG.","amour h","amplio f<","ana nL'","anatomíaA",
"and mkged^[WSR6+)c","andadura jL@8","andaluz jI","andaluza j","andrés c","andrew i\\8","angdgp9psb8 n","angelZ","angels d","anglo\\",
"anglosajón lJ;","anillo f","animadaE","aniversario$","ankirsycetw>","annabelU","anorexia e","anotherTRE","ante ki^PK/'F","anteriormente 3",
"antes j_WKF<5","anthonyJ","antiguoR","antojaba i$","antonioX?(","anuncian$","anunciar 8","última k","último 0(","últimos]F",
"únicaNK#","único`]VD>41.","únicos 3","apacibles e","aparecieron g","aparentementeN","aparición gEA7-","aparienciaSA","aparte%","apbfcvdkmxmE",
"apellido g","apenas gK","apetitosos c","apodadoQ","apoderaSQ","apogeo_?*","apostandoH","apoyado 9","apoyarK","aprendíD",
"aprenderI","aprendiD","aptasS","apuesta@","aquí hJF","aquel lhdM20VP","aquella lP","aquellos 0","aquiF","aquiles]",
"ar8d2yqgq1u_","arafqe94nD","arby 0d","arco f","ardióI","ardiente^","areTB<`","areethaA","arena%","aretha\\/",
"argentino c","argumentalK","arguments onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","arie#","ariel c","armadura(","armario$","armas g","armonía fM","armonías?$",
"armonizada>","armsP","aromas i","around 7","arrancaronU","arrebatándonos(","arrebatóE","arrebatadorH","arrebatadora^","arrebato k",
"arreglos eM","arriba n","artística i","artísticamente aV","artísticas nI","artísticoUg","arte hF","artes m","artistS","artista g^L8d]N.",
"artistas onmlkjihgfedcba_^]\\[ZYXWVUTSRPONMLJIHGFEDCB@?>=;:87654321/,+)('&%$#QA<90.-*`K","arts>","asW","así cNID:98mg.","ascendenciaF","asesinado_","asi oZ","ãšltimoI","asoma>","aspecto(",
"aspirando h","aspirarL","asturiano n","asumiendoK","at,%","aterciopeladaPE","atlanticA","atmósfera>","atrás jKE*","atractiva\\",
"atractivo\\9","atrapado#","atrapan f","atrapar\\","atraparte^Q","atraviesa>","atraviesanQ","atrayente\\","atrevido o","au8u g",
"auao50nwnvgP","audienciaY","audiencias h","augusto a","aumentar 7","aunN","aunan h","aunque^WVQLF>)$","aupóL","auparon(",
"auraQ","aureola\\","auseronU","auspicio g","auténticaC%","auténtico=","auténticos c","auteF","autenticidadJ","autodidactaI",
"automedicarse i","autorB","autora]/","autores n","avalonZ","avatares$","avecL","aventuraX","avionetaP","awD",
"awardsYN","away#","axz9cpnwns0 1","ayer(","ayudaba g","ayyyK","azaharaIC","azulIY","b3gbisdtjna]","b6zqd0s&",
"bálsamo m","bésameXD","babaji b","baby h","babylon-","bachata=","bache g","back hg","baduA","bagajeG",
"bahiaP","baila o","bailar=","bailarina]","baile ga","bailes-","bailey 3","bajón 8","bajista a_XT","bajo kjgdUTN*)i",
"baker-","balada oJ","baladas[863","balance'","balanceándose f","balazosK","ballet_","baluarte&","bandG","banda g_WUT)$k:*fb",
"bandasWA630","barón)","barbra*","baron)","barranquilla]","barreras]","barrettR","barricades_","barroI","barroco i",
"barry i*","basada)","bastantes)","batalla 1","batería kj_TK3)","bateristaT","batt>","bayP","bayou[","bazasH",
"bbcQ","beTA<*ge40","beach[","beatles[P$","beautiful 2","bebían 0","beber 7","bebiendo?","becker 2","bee*",
"been/P","begun e","belén n'","belfast m","believes f","bella[>'","bellas neMH(","bellezaIF(","bellos fe'","belongE",
"bendición=","bendita=","benegas@","bengalí i","benidormV","benny$","benson 7","beretS","bernie 4","berryK",
"besarte c","beseJ","besosG","bfhsf6fkgb4S","bfqonlm0ggu 0","bgotdgu8cho,","bibliotecaB","bicicleta]","bicycles>","bien k#*",
"bigG6","bikinaG","bilbaíno 5","bilirrubina=","billboardY6","billie\\","billy'+i","bin3jekig9s'","bipolaridad b","bird#",
"birdland h","bit b","bitesT","biznieto?","bjorn$","bkajs8wayd4#","black f","blame g","blanca,","blancasP",
"blanco fM1'm","blancos^[","blue mf^*[Q","blues omKHE>364","bluey 9","bnlsdqnj0lu(","bob[","bobby-,","boca 50","body g",
"bohemianT","boj6fl8eoxaR","boleroGD","boney-","bonitas_","bono k","boogie g3","boom h","botánicoU","botas)",
"boteP","bottom onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","bout 9","bowie 1","boy h<i","boys[","brand a","branigan l","brasil h","brasileñaY",
"brasileñas'","brazilianY","brazos n","breakT","breakfast b","breaking 4","breakthruT","breezin 7","brianTkZ","brickR",
"brillante jd^>","brillantezO","bring a","brit m>","británica b:","británico m^4*","británicosR1","broadway 7","brookingX","brota kO",
"brotherK","brothers f#","brown m9-","brusca i","bryanZ","bu26eI","buckingham 6","buen khbaTGC<;90+A","buena]K:97-","buenasC",
"burbujas=","burlóF","buscar onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","buzz:","bvauqazuh9oI","bw6sfc9u07o[","by onmlkjihgedcba`_]\\[ZYXWVUTSRQPONMLJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#fK^","by2e2m4thnm@","by2ew9.","c0blkudnyno\\",
"c3nscn89klo 4","c5s6dfiqywo(","c7wjmepf7u0 c","cálida d","cálido/","cálidos\\@","cáncerE10(","cómoTM&","ca46znjrzey a","caídoU",
"cabeza l","cables d","cabrales 5","cada j,","cadenas\\","caducidadQ","cae j","café=","calabria)","calamaro c",
"calaronF","calderónM","caldwell,","calidad mlh\\C96%$","calidez'","caliente f","calificativoN","california[","californiana f","call 4",
"callao=","called`","callejónK","calorU","camaY","camaleón 1","cambió 8","cambiando gM","cambio 7","camilo.",
"caminaré l","camino jKI","campo<","camposI","campuzano)","can g#","canaan/","canción nkYVRC)MFEBP'","cancion]","canciones nkdc`_\\XWRPMLIHGDCA?>=<:8321,+)'%$ljfba[VQ4.eK(F",
"candiA","candidez[","candoroso/","cano'L","canta nm","cantadas;","cantan.","cantandoE","cantante i`JHA843/,+;","cantantes%",
"cantar g^VP<","cantaráM","cantautorF","cantautora/","cantautores+'","cantidad.","capaces j^;93","capacidad k;","capasI","capaz maQKJI=8.(d",
"capitalF","capturaban/","capturadaP","caraY","caracterL","característico k","caracterizado$","caracterizar=","carasP","carbónI",
"carcomidoR","cardíaco 8","careless 8","cariñoY","caricia o","caricias>","carismaU","carlos]HYXM","carmona?","carneV",
"carole/","carolinaH)","carpenters e","carrackQ","carrera gfYQPGE<42'","carry,","casa]XSP5","casal i","casi d^[PMCA?.'i","caskuxE",
"caso*'","castellano$","castro)","católicaW","catalanaF","catalizar 9","catalogada<","catalogados h","catalogar d","catapultó_W",
"catapultarloV","causa m","cautivar 7","cay74#","cayendoK","cbs g)","cds$","ceE","ceilingB","ceju9kvabaoT",
"celeste o","celine*","celtic m","censuraF","centrándonos i","centró c","centroQ","century b","cercana 1","cercanos@",
"cerebralF","cerebroRQ","cewhzel76ee?","chacon 0","chainsO","champú i","championsT","changes 1","chanson h","charles\\0",
"chica(","chico k","child 8","chilenas a","china f1","chjt4xdazoc g","chocolate 0","ciega]","ciego`;","cieloJ",
"cierto:","cimientos)","cinco e","cineF","circleO4","circula f","citados 3","city hK","ciudad'","ciudades n",
"clásicas h","clásico f<0","clásicos c0","clímaxK","clanH","claptonQ","clara d","claridad l","claro h","claudicaranP",
"clayton k","cllore;","close e","clubs h","cndlbu0gW","coB","coche i","colaboración 0","colaboraciones o","colaboradora)",
"colaborarQ","coleL","colectivaT","coletazosF","colombia]","colombiana]","color of^Q,","colorido 9","comaF","combinabaK",
"combinacionesZ","come h","comentaA","comentábamosM","comenzóV8","comenzando h","comenzaronL@","comercial fIA6","comerciales^","comercialidad b8$%",
"comerse d","comes 7","comfortablyR","comienzo lkPMK<iC","comienzos me\\[H)LK","commodoresB","como lkbYXUTLIGB?=;754/+*oge_]VSOJC<9821,($njhf^QPMFA63.'mida[WNK0\\%","compás\\","compañía)'","compañera(",
"compañeroX","compactaba e","compactadas 0","compaginaban b","compaginando 2","comparadaA","comparesS","compartióE","compartirI","comparto 1",
"complemento)","completo.","complicidad 3","componíanT","componenteM8","componentes hTM","componer 2(","componiendo_","composiciónEC8","composiciones o\\J@;/*('$6",
"compositiva n<9(","compositivoM","compositor i`_QH>4.,+&3","compositoraA/&","compositores mlM/","compostura'","compromiso/","compuesta f^'","compuesto?-","compuso/",
"comunesW","con^YUTSDC65/#oea\\ZXRHA@>1+lkb[N<;720*$mhf`LGEB843.'&jcQOJ?=9)(dWPF%iVIM]K","concibióN","concierto%","conciertosR?","concretoW","concursoA","condenadosF","conduceM","conducir<",
"conduzcaQ","conectandoI","conectar a]","confesar d","confianzaA","config onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","conjugando$","conjugar d","conmigo 7","conocíamos d",
"conocerS@7","conocerse 0","conocida kU]","conocidasRK%","conocido omhaS1","conocidos lY@:3*$","conocieseS","consagrándose 5","consagróN","consagrado(",
"consagraron b","consagrarse g","consciente\\","consecuencia i]S80(","consecutivasL","conseguía%","conseguidoN%","conseguirVQJ","conseguirloN","conservan\\",
"conservando\\","considerabanM","considerada\\","considerado kJE+","considerados?","consigueF","consiguen^","consiguió l","consiguiendo d","consiguieron 3*&",
"consiste h","consolidación i","consorcioM","consumadoP","contóZ","contaba 0.","contacto 7","contador+","contagia 9","contagiarnosH",
"contagiarse 4","contagioso g","contagiosos 8-","contaronK<","contarte j","contemplarP","conteníaPK","contenida j","contenidoR","contenidos onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"content onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","contigo@D","continúa nmV'","continúeM","continuó 20","continuado[T","continuando c","continuar@(","continuaronW","continuidadK",
"contra a1LF","contradecir<","contradiccionesWK","contrapartidaW","contraria i","contrario=<","contrastada'","contratiempos(","controlK=g","convencional i",
"converger 0","convertiéndose 0","convertida=","convertidoZ1","convertirseB?","convierte@","conviertieronA","convirtiéndolos-","convirtiéndose k]\\M5","convirtió dPN?K",
"convirtiera*","convirtieran 8","convirtieron 3","convulsaK","cooke dK","cookieconsent onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","cool-","copa]","copia 0","copiasW*&",
"corazón nmYMKFED;","corazon nUD","corporal(","corre#","correctaA","corriendo&","cortes)","corto`J3","cosa$","cosas mV",
"cosechados 3","cosechar]","cosi o","cosmic:","cotidianidadI","country mg[B6#f","cowboy:","coz)","cprgk5rksc0J","críticaK",
"crazyR","creación 5","creada_","creado-$","creadorF","creamS","creando 4","crear m,","creatibidad/","creativa)(",
"creatividad iB","creativo`41g","creativos 7","crece'","crime b","crisis db","cristalina e>","cristalinasO","cristiano]K","cristinaF",
"criticado%","cropperP","cruce d","cruces;","cruzL","cruzar n","crying[","ctdr6brrvx8 9","cuéntame@h","cuídate@",
"cual l/","cualesR","cualidad^","cualidadesNC7,","cualquier o^]LB732","cualquiera oLG","cuando kjd[QNIE*K<","cuantos>","cuarteto hW","cuatroX",
"cubanosU","cueca a","cuenta l","cuente 5","cuerdas]","cuerpoF","cuestaL","cuidadasB@5&","culpa a","culto kW?",
"cumpleañosK","cumplir i","cun7paje8icV","cuotas*","curiosamenteS","curranteV","cut_","cuyaQK","cuyo g.","cww03hjhod4M",
"cye8et a","d27gtrppayk a","d2yrI","d5cr9mrlsc0 j","d77tdtsn7nk i","da m","débil(","década nmg_]WSRQKG?72/6-","décadas nm^[97'%","décima(",
"déjameM","día nmV","días&","dabaX","daddy-","dado oP","dímeloJ","danA2","dance a:8-d1","dancingB*$",
"dandoBA97\\","daniel k","danza a","danzan a","dúo e0","dúos e","dar ogdcQPI<","daría g","dark onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","darles 8",
"darse@","datalayer onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","date onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","dave k","david 1","davies b","davis o","day a/","days ed","de#b_Z=JHC1oc`[TND@5,WO:2<;-+XUGEB864/ea^\\9)&%nhfS3lY>LA0$]RQ?PI7.V'jMgdFmk*i(K",
"deaconT","deadE","debajoGA","debería 7","debidoPM","debilidadK","debilitóB","debilitamientoK","debut dXA<20","decíamosW<",
"decayendo gW","decide g","deciden)","decidióK","decir bLI;3M","declaraciónU","decliveK*","dedicabanC","dedicadaR;","dedo f",
"dee 4","deep*","define#","definen m","definición=","definir`ZJ","definitiva 8i","definitivamente*","definitivo&","degradamientoK",
"deja h]J9","dejándonosF","dejó n\\SP0%","dejaba?(","dejaban-*","dejado(","dejar d(i","dejaronXC@-","dejarse\\:7","del ifbaZXVJC:954-#onle_\\[UONA@>=<;8.,+gd`^TRQIHGDB32*)(kjh]YWSPLF?10/&%$K'cM76Em",
"deleitado%","delicada>#","delicadas e","delicadeza 4/","delicado 3","deliciaQ%","delicias b2","deliciosos h","demásME&","demoniosK",
"demostró<","denman\\","denominado m","denominanW","dentroJ>6$","depresión(","depresivas 8","deprisa i","desátameN","desafiante)",
"desapareció e","desaparecidoM-","desaparecidos a","desapareciendo 0","desaparición(","desapariciones*","desaveniencias$","desbocado<","desbordanteS","descalzos]",
"descaro cAX","descartarY","descendió 6","descomunalT","desconfiar?","describiendo a","describir(","descubrió>","descubrimientoOA","descubrir`^",
"descubrirlosX","descuidada(","desde mkfc^]WRPNDC6'&$MJ:1","desempolvando$","desencadenante 0","desenfrenada f","desenvuelvía%","deseo i","desesperada j","desgarradaPE",
"desgarradoraP","deslizándose^","deslocado g","deslumbrante j","desmedida.","desnuda j>","desnudesF","desparpajo g","despiertaH","después jgM80",
"despuntóV","despuntaba g","destacados 5","destacandoY","destinoL","desván n","desvaneciera e","desvanecimiento*","detallesY","deteriorar(",
"deterioroK)","detonante 0","detrás$","detroitK","deuR","devaneos%","devoción:","dfe3s3)","di l","di0 2",
"dia mUMKC7'","dió fdPM","diamante o","diamondR","diamondsS","dianaB","diariosA","dias kW1","dicesD","dicho m",
"diciembre 8","dictadura a","didn+","die:","dieronC?","diez 5","difíciles k","diferencias n","diferentesM-%","dificil\\Y>7%$",
"dificiles(","dificultadI","difruta 3","diganV","diggin<","digna m","dignas>","digo n","diguehwmorc n","dime cl",
"dimensión k","dimmi l","dinamismo 3","dineroK","dion*","dionne*","dios'","dioses?","diríaA","dirección iA",
"directamenteQ","directoH73%","director iF","directos 3&","disco gd_XV<;963-,&P20*","discográficaG<g","discográfico d-A","discografía`$","discos kYXRPG;:852/.)%dVL","discoteca 2",
"discurrido 1","discusionesK","disfrutabanP","disfrutando dc$","disfrutar mhdXM9","disfrutarlo%","disfruto,","dislumbraba d","disminuidos n","disoluciónXWI@$",
"disparesL;i","dispuestas\\","dispuestoI","disquera;","distanciaY","distina)","distinguidasE","diva'N","diversión 3","diversidad*h",
"diverso h","diversosA5%","divididaR","divinaN4","divino o","dje0/","djfgb 9","djklltlmnds&","dkytjloxgmq f","dluhzqhlcme d",
"dlxpnif0yksW","dmgvs2j05ha^","dnrxd6v4 6","do,0","dockP","doctorados m","dojvw>","dolly*","dolor k","dominicano=",
"don bTQA9^]64,#","donâ€™tO","donald 2","donde nmkdb]WSRPNMKA510)F%h","donna o","donostiarras@","doobie f","dorada e%","dormirH","dos nUMKJ;5F",
"dosis(","dotándolo m","dotadoE8","dotesI,","downO4g","dr:","dream 9","dreamer b","dreams+[6","drogas eR8K",
"drove[","dtpqoafxc=","dtvbcg6thdk 4","dublinesaA","duda\\VQMF6k","dudoD","dueñoKE","dueños onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.,+*)('&%$#-","duelaV","duende;",
"duermanI","duetoO","duetosK","duke`","dulceP@","dulzura<>","duophonic 0","duper<","duque 1","dura 1",
"duraciónR","durante fF6i","duro(","dustT","dut5reu6pqm]","dxdkywilt74B","dylan[","dzhje11cgW","dznqcmpcqxq 2","dzsue5ugxf4]",
"e3 k","earth 3","easyB0","eazjxniqnqi.","ecologíaI","económicaK","edén i","edad nVG>","eddie 0","edema i",
"edge k","editado;","eduardo jF","educaciónRO","efímero 0","efecto$","eftlkww542g+","egocéntricoS","egocentrismo d","egs'",
"ehpe7b4fx8,","ehqg6>","ehulq#","ejecuciónF","ejerce]","el lb_[XROB92nec]QLG=;:+(oaWH/m\\JE87-'%ihfUPNA<5.,&jTSD>$kYI@?310dV6)gMF*K","elaboradasL8","electrónica 1","electrónico 3","electrónicosU:",
"electro:","elegancia jZGE97\\","elegante fK6","elegantes e","elegidas 4","elemento)","elenco 3","elevarles$","elixir(","ella_]\\A>/",
"ellas lF1a2","ello mh\\WT:.,","ellos kge^[XWUMD@?>;3+fcT$","elocuente&","eloise i","eltonQ4","elvis[","embajadora]","embarcadoU","embelesar l",
"emblemático k","embrujada i","emergentesA","emi 0","emigró>","emisoras 0","emoción nH6#","emocionándonosP","emocionalK","emocionar a",
"emocionarmeF","emocionarnos=","emocionarteI","emociones nmQJ;('","emotividad dB4","empape>","empaticenQ","empezó[KGE","empezarK","empezaron[",
"empiecen 2","empiezaI","empiezanF","empiezoN","empresariales n","en bYXJC<&eSQPI:91l_^\\ZWRG=;4/,jfUTODB+$#okcaE?730('d[F>ngA85-*%m`VL@.2)6]NMihK","enérgica/","enérgicas f","enérgicoK","enamoraJ",
"enamoróV","enamorado oU","enamorarJ","encandilaJ","encanto l\\PA:9%","encantos 8","encargóP","encauzadoC","encerrabaS","encerradoD",
"encienda 2","encogerF","encontrabaM","encontraban d","encontramosM","encontrar h:%","encontrarnos 8","encuentre%","encuentres]","encuentroD",
"endWE","endlessB","energía fcP.93:","enero 1","enfermoN","enganchados+","enganchar^","engancharte;0","englishman a","engranaje@",
"enmascarandoF","enoZk","enormeYEB.","enoughK","ensayarC","enseñándonos g","enseguida<","entenderN","enternecernos=","enterradas d",
"enterrados d","entonacionesV","entonces lhdM0","entradaM@","entramado'","entrando/","entre kfJ$5","entrecruzabanN","envidiableGB","envidiables k",
"envoltorio d","envolturas>","envolvente f","envolverá o%","envolverteQ","envolviéndote'","envolviendo>","eo7iwlmfprm:","eo8r1w8qrgo[","eoqu a",
"eqlnl8D","eqp1s#","equivocaría 5","equvoqut1vmA","era igROKIEB?872*)d","eranF?63$","eresM","ericQ","erizarmeF","erranteC",
"erupción^","erykahA","es kjihecba_[ZYXWVUTNKHECBA@?<:850/-)('$mdQOLGD=;64321,+*&nlgf^PJ>97#]R.%o`\\ISMF","esa lke^MA=82/-)","esas[WKF4Q","escándaloV","escándalos 8","escénicoF","escalofriante f","escapan'",
"escena 9","escenario\\[TK","escenas;","esclavitudK","escondeA","esconditeN","escritor 0","escucha]","escuchabaP","escuchadas e>",
"escuchadoM","escuchamos*","escuchando\\I","escuchar:9*#","escucharleQ","escuche a","escucho,","escuela mU","escultura i","ese lb^]\\YSC;7*(#gQMA0",
"esencia jR>3(","esferas.","esguince i","esoXHA%","esos fd^XPMLKA0(3)","españa hUNF.)'5","español nlc`^F?;)NL.(&","española iNM","españoles nM","espacio@>&",
"espada 5","espaldarazo&","espaldas@7","esparce(","espírituL3","especial md^]UQNMGD;#","especialesD","espectáculos-","espectacular mlS3","espectacularesR:",
"espectacularidad 3","espectante d","espectro l","esperadosN","esperando$","esperarNH6","espiritual(","espiritualidad m","espléndido`","espontaneidadW",
"esposas a","esrb6yvZ","esseY","est#","esta ba\\WPONMA<:6","estáM,+Y","estásM","estéI","estã¬loB","estaba fWRA)",
"estaban 3","estaciones(","estadoQ","estados hVM","estadounidenseW0+","estamos e;?","estando gd?","estarF+","estaré d","estaréis 7",
"estas,","estatuaU","estatus b($","este omhdWPNB?<76.#f]%","estilo ihVJICA?<6f","estilos o;5*%","esto]M","estos$","estoy`@","estrafalario 4",
"estrellaVEB&","estrellatoKA","estremecedorasF","estremecedores 8","estremecerte m","estribillosW","estrictasR","estructuraI","estudiaba>","estudio(",
"estudios i","estupendasC","estuvo hK","etapa kjeB8521)aM(","etapas 8","eterna b","eternamente(","eterno.","euY","europa hVNM-",
"europeW","europeos&","eurovisiónVM$","eva&","evans k","even b","ever a%","everybodyW#","everywhere 6","evidente 0",
"evidentemente d","evitar 8","evocando:","evoluciónL7","evolucionó 6","evolucionando_R","ewjciC","exX","exageraciónM","excéntricoK",
"excelencia(","excelente 2","excentricitésN","excepciónM","excepcional/'","excepcionales 3","exceptuandoL","exhalan l","existían 6","existencia 4",
"existencial d","exitosa 8","exitosasT","exkwkqI","experimental dR1","experimentalesZ","experimentarI","expertosW","explain m","explicaciones d",
"explorarI","explosión*","explosionar 3","explosivo c","explotado n","explotando 3","exponentesQ","expresaP","expresabanW","exquisita\\4",
"exquisitas?","exquisitoQ","extensaF","extenso mY","exterior^","extraidos 9","extraordinaria-","extraordinario e1","extravaganteTS1","extrayendo&",
"eyeW","eyed f^Qm","eyesZ7Q","ezk9rhnnvwe l","f5q4y 9","f8ksqdsztugH","fácilA4\\","férreo g","fértilesS","faceta n<8(i",
"facetas n","facilidadF1","factura i","fagen 2","faith a8","fake^","fallecimientoP","fallidoL","fallo 8","falsete f[3",
"falsetes 3","falsetto*","famaE/-+m","fame k61","familia gM?","famosaRP%","famosoL$","famosos iD'","fans$","fantástica f^.",
"fantásticas o","fantasy 3","farian-","farrell-","fascinantes 3","física#","físicamenteS","físico(","físicos n","fast 8",
"fastuoso 3","fatalX","father 8","favorI","fearsO","febrero%","fechaQ","feelWg/","feelin g","feelingO7",
"feliciano;","feliz;","fell d<","femenina]ON/","femeninas$","femmeL","fenómenoV","fentaniloS","fernandoX","ferryZ",
"festival$","festivalesV)","fever*","fgb9cvwdn04[","fichar;","fielYI>","fields a","fieles h","fiestaL","fiestas@",
"fifa]","figuerasN","figuras 2","figure 8","fijó<","fijarse k","filaI","filántropa]","filipinasF","filosóficoR",
"fin me('C","fina j","final iecPK*","finales mlcOKIC*","finalizándolaL","finalización j","finalizada 6","finalizando a","findE","fineW/",
"finura\\","fire;+3","firmado i","firmar i","firme)","fitipaldis 5","fito 5","five g","fj9ruzimczqT","fk9iqnq883o o",
"flackA","flagelantesT","flame,","flamenca j","flamenco j?","flamencosI?","fleetwood 6","flicteaO","flood>","flor n?",
"flores?","florida 2","floydR","fluye:","fly_R","fm8ggdigcwyJ","fmjgnedhkby i","fnfzfwlm72c*","folk mhf&","food h",
"fool b#f","for_>,#kO%","forjando&","forjarseK","forma li^UPIF;4(d:2","formó cXB","formaban g6)","formacíones g","formación g\\@?9)M","formacionesM",
"formadaM)","formado e\\*","formados&","forman jTI*","formar cWUHA*(","formaron hg_WTEC:0*","fornaciari o","fortuna m","forzados(","fotos a",
"found k","fovcbmkuw0-","fragile a","fragilidad(","francésM","francesaL","franciaL","franciscoM","frank?-","frankie*",
"franklin\\A/","franquistaF","frío=","freddieT","free aWT","frenéticoJ","frente kjhebZH?3","fresco*","frescura@?c","friaH",
"frialdad j","frida$","friend 9/","friendsT","frjctF","from hbA4#0","frontier 2","fruto 0","ftbwo6cetuk n","fué m",
"fue mld_\\XSRIA@><8UPNMLEg0K","fuenteW","fuentes@","fuera l","fueron igcaWNK?-%","fuerteI","fuerza^PLKF<3.","fuerzasM@","fueseN","fugaK",
"fun 6","function onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","fundíanI","fundadoresM","fundamentalT","fundamentalesB","fundamentalismoK","funk gdSG:93","funky gE<:38","fusión mH?93",
"fusiona j","fusionando,","futuraU","futuro iK","fuwryuderhcD","fwqpqycqgp8)","g2n0tkfrqhyT","género omG?","géneros 1","gafas[",
"gagaT","gamble^E","ganándoloA","ganóVG/","ganando;","ganar=","gang 9","garayM","garcíaX&I","garde@",
"gargantasE","gary_","gatoY","gaviota'","gaye_A90K","gckghm7gmwm`","gees*","genéticaI","generabaK","generación/-*`",
"generaciones mVG+","generalO&","generationS","generosamenteE","generosidad m","genial dS?7","genialidad jR9","genioS","genios(","genteJ",
"gentleman m","genuina)","genuino`T1","george m87","georgia>","germen)","gerry/","gestosV","getEOK","getsemani.",
"gettS","gf8qy_","ghaqfH","ghetto 72","ghettosK","giae7yz7ghiG","gibb*","gigR","gigantes(","gimme$",
"gira])$i","giras[V7","girl m:-+1","give bK:7","gix2pbrbxcq-","gjulpdcct3m b","gklpl4fhzus]","glam i1","glamour\\Z","gloria ml",
"glorias d","gmmc0z0vg04C","gmt c","goTO60-h4","goffin/","gogh c@","goingK","gold_>a","golpeT(","goma i",
"gone 3","gonna:0","goodE#","goodbye eb","goodnight+","gordon a","gordyK","gospel mOE","gotKJ/^[","gotta-",
"gowebnppuom 5","gozaY","gozaderaJ","grabado i","gracias f^\\NKH;4'mL","grado h","grammy mkhd`OG;86/+","grammys hfeYWKEB7*%","gran lhgTPONIFBA:-kfVQi","grand#",
"grande 9.","grandes olf\\[PKHBA97)'","grapevineK","graveV","grease*","greatR","greatest 7","green 0","greyA","griega'",
"groove 3","groovin h","ground g`","grove f","grupo jhg^\\XWTSQLIHB@53-)'$kifcaZR?9M6*","grupos hRQC5*&i","gs069dndiyk 3","gtag onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","guíaM","guerraK=",
"guess 4","guille&","guilty*","guitarra kj;7&_","guitarrasTD","guitarristaTP&?","gusto hbG","guyZ","gxepv4kolz0+","gxqjx7fkmna 5",
"gypsy 6","h6kyavn8ons 4","h9tevfisdyoS","ha mjhgYTPMLHDCA@=:851.+*]V'%o","hábil+","había b","habían(","haber n`5.","habernos m","habichuela?",
"habiendoG","habilidadesA","habilidosaO","habitaciónL","habla kV","hablábamosK","hablamosVE","hablando e`;","hablar kD&Rg","habría)",
"habreísM","hacía j(","hacían 7","hace`]RJ-","hacen j\\N","hacer oj97","hacernos=","hacerteI","hacia d_RL:6","haciendo[R72D",
"had<","hadley_","hagaM","hale\\","hall k6","halo d","han oljc^]ZUM@:10/.)(mkhG&$","hao 8","happeningK","haráF",
"hard d","hardest 4","hardline d","haritz@","hasM(3","hasta mkih]PE>61+)WM","hauser h","have mk","haven k","hay mkWVF:54,",
"hayá%","hccbfuziJ","hcumwrfxg4e+","head a2","heal 8","healingK","heardK","heart aA4#P","heartbreaker*","heaven>0*#",
"heavy)i","hecha b","hecho ol]YVQGDA:8/($m@","hekjnahwihwH","helloB","hemorragias]","here 7RO0","herederos@","hermana 0","hermanas aM",
"hermano_","hermanos ge*#)","hermes)","hermosasG%#","hermosoP","hermosos/","heroína(","herramientas 7","heterogéneaF","hewson k",
"hgjsbrubxQ","hgzgwkwlmgmT","hh3hgusk7pmM","hhx6rgrkgf0 h","hicieron bR832i","hieloE","hierro(","highK","higher`","hijoL?",
"hillsA>","himno kF","hipnóticos-","hippie<","hips]","hispanaV@","hispano]LD@;'c","hispanoaméricaM","históricosM","historia nkgYLF1/*(j",
"historiasN+","hit 0","hitosM","hizo ebA?0)(","hjf3e2zgnkg 5","hkm0ih8slcgF","hlguyxtmwe4 0","hllcc_","hm8ehtn9rmwJ","hmhezd9bsb4 d",
"hmkshplxnxe`","ho7796 g","hodgson b","holding d","hollerK","holliday\\","hollywoodE","hombre omiSQME=%#K'","home b0-^","homenaje(",
"homenajeaban_","homosexual k","honestidad=","honorN","honoris m","hooker m","hopeO","hora mgd(","horasC","hospital(",
"house 90","howPQ*","hoy nVUPML7)'m","hpx&","hro0wkv4yjoU","hrzgzrqnj58Z","hspefI","hsq4b+","hubieran-","hucknall^",
"huecoF=5","huella d\\X","huevo i","huff^E","humano n","humanos k","humo e","hung a","hurt 0","hurtinE",
"hurtsW","huzwP","hvwnfdadvssQ","hwukrS","i4uyofazwpa 7","i6ibauwboda*","i9st43hymbyQ","iâ€™veP","iba gd*","iberoamérica.",
"ibn5dzaw4eqO","icR","icteria i","id6zoy a","identidad\\UGD?","identificarL","identificaremosV","idiomasL","ido^:M&","if>a^d",
"iglesiaW","igualMBA863*","igualdad k","igualmente ga?","ihs*","iikae8wi0s0$","ik l","ikermdasvtg n","il o","ilegal i",
"illánX","ilusionarseI","im1uv8dk00sO","imágenes onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","imán\\","imagen ig[LK<841$","imaginaciónI","imborrable 0","imj4t7oidi0,","immortality*",
"impávidoS","impasiblesV","impedido.","impedieron c","impedimentos n","imperio m","impidióP","implicación/","importante kSM","importantes<*",
"imposible.*$#","impregna#","impregnándonos n","imprescindible b","impulsóK","impulsaron d","in k><762-,ba[PO3*%R","inadvertido 0","inalcanzablesM","inamovible[",
"incalculable(","incial)","incialesT","inciaron f","incluía*","incluida fW","incluido m+","incluso leMA1)$m","incluye+","incluyen*",
"incluyendo onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","incognito 9","incombustibleV","incomprensión k","incondicionalG","inconformista iS","inconfundible;V","inconfundibles j","incorporación fM","increibles j.",
"india#","indiferente-","indiscutible g","indiscutibles 8","indispensables 2","individualidad 8","inevitable 8","inexorable1$","inexpertaA","infante c",
"infartoF","infierno)","influencia d[TI0","influenciado f0","influencias<","influyó*","influyente j","influyentes`L51","información`^","ingeniería k",
"ingenio k","inglésZM)","inglaterra a%","inglesa:","ingredientes 9","ingresó 6","inicial fc","inicialesW","iniciarB","iniciaron j?",
"inicio onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","inicios a_^]","inimaginablesM","inmaculada'","inmediato 8","inmortal 1","innatasN","innerK","innuendoT","innumerables$",
"inolvidableF","inolvidables.(","inquietudesI","insaciableI","insanity:","inseparable 4","insertarOA9onmlkjhgfecba`_^]\\[ZYXWVUTQPJIHGFDCB?>=<;8754321/.,+*)(&%$idSRNMLKE@:60-'#","inside 7*","inspiración kW@9","inspirada n'",
"inspiradas j$","inspirado`","instanteP","instrumentación j","instrumentales h","instrumentista m`","instrumentos dWC","insuficiencia i","integrante'","intencionesU",
"intensidad'","intentaseA","intento iL","interesantes 2","interior hP","internacional])&","internacionales:","internacionalizar i","internacionalmenteV","internos c",
"interpretabaK","interpretación dVO8*.","interpretaciones hVJ.","interpretado^","interpretar d;'","interpretarla.","interpretativaP","intimistaI","introducidos k","introducing d",
"introspección>","intuición]","invita 9","ioJ","ipiñaM","irW","iris f","irlanda mA>","irlandés m","irlandesa mk",
"irrefrenable d","irrepetibleS","is onmlkjihgedcba`_^][ZYXWVUTSRQONMLKJIHGFDCBA@?>=<;:987654321/.-,+)('&$f\\P0#E*%","island 2","islands*","isn`","isnâ´t`","it fW:$[K4/#g","itâ€™sW","italiana l",
"italianas l","italiano olM","italianos o","ius84sd0hra;","iv5ojxem6fuD","ivan m","ixdnnw99R","iyiol$","izaskunM","izgwdsrq1eq 8",
"iziborA","izodvbmtdh0^","izugarria onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","izzpC","j0r7cukawg 0","j1sa1t3m<","j3we3 0","j789gid1kay m","j7oqepfeW","jóvenesA",
"jackson hgB","jacksons g","jaenV","jamásPN.","jamiroquai:","japónVL","japan,","jardínU","jarreau%","javier cM",
"jay:","jazzUOGE?>;32,:97%h","jazzman/","jcm4h9rom'","jdwljhqf4 2","je2scisqmpe_","jealousZ","jean]9","jesús j","jesucristo.",
"jesus f8","jfjjs0xsm9mC","jhtdwimy.","jillA","jltj5ktfyw8^","jnvy7srofq#","joaquin c","jocelyn 9","joel'+","john m_TQ4",
"jones o","josé j?M;","joseL)'","joshua k","joss<","joven dA<","joyas`^(","jpmxjmais04?","jppna5pqrpwL","jq2dvwsviio 8",
"jr k","js onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","js6yqyzszmo 2","jtxv02tyr5a 3","juan jUM?=&","judaísmoK","julián i","juntóK","juntaron c","juntarse 0",
"junto\\RIDB@2/,(#X","juntos c","just f`>e","justiciaN","justoK","juvenilUL","juventud lA(","k1ljplq1v6y\\","k2ldicb5ejg:","k7oajjdshs8S",
"kadajqv6sdkG","kamakiriad 2","karen e","katie>","kay:","kcW","kcpc18sg6ua\\","keeble_","kemp_","kenny f^*",
"ketama?","kgjfpcjwkyg(","kgrqhwfjq[","khaled?","ki5p5veewyeW","kiki 4","kindT","king\\4/","kissS\\","kjlmejl5yqmV",
"klvq0iazh1a a","kmz4panwlae i","knd i","knowW#^","konde5c7og8Z","kool 9","kop3cuvd2qq o","kpdjqbthay 1","kqa n","kqvwyu4bdmo 8",
"kszyhtq i","kvc5rcl0bis 7","kvdmlk3ksyg-","kwnfwzem6swL","kytmvki 2","kz.","kzxndlvzs3k%","l0cvofsuhc4 3","l0etbwiE","l3d7unj3qck)",
"l6vyj)","l7vrsuS","la h_[OD<,+#aZXW4&$eb^HB:1ol`VU=;83/fdTSLJGE?20-ncQPN>65YF\\RA9%I@7.gM*'mK()]kij","lópez c","lía'","líder^","laderaN","ladoGM","ladyEY","lag4zjyx89gI",
"lago j","lakjahibl2y=","lamentablemente jF","landslide 6","líneaK","lanois k","lanza 5","lanzándose a","lanzadaN","largaE*(i)",
"largo^[Y*'","larry k","las nldb`_\\[WVTSNLJHGFE@><;:843.-+*)(&kfeaOI21,%mg]R$K'M6","late/","lately m","latenteL","latidoDF","latina]YVU","latino]JG;","latinoamericanoN",
"latinos;","laura lYA","lava^","lb6a a","lbjvz0[","le mYSRONMKJE+'#a(i","león m","lead,","learn:","learningR",
"leave b_","lee m\\U","lefhnn7rl4w h","legado mYS?.","legal i","lejanaP","lejosA","lengua@","lenguajes f","leon^",
"les gf^WMLD:3-)h@","letOKA4d31","letra fa)'","letras mjhWRLIB@54&$","levantarL","leyendaYVK(","leyendas`","leyre@","lhcp4mwabgy k","libertadN?)'n",
"libertadesF","lider gU5","liderada:9","liderando aQ","liderazgo b","lie]0","lies 6","lifeO41h`\\","light;","like>#E/",
"limpia e","limpiamente>","limpiasO","linaresV","linda#","lindsay 6","linguaM","lion m4","lionelB","lis?",
"lista e*('","listas f_M6","listen f","little bP6d0","live,%","livingQ","ljntnoc81oaV","ll_gE","llama^)","llamaba 1",
"llamabanM","llamada ibA","llamado jgW90-","llamadosM","llamandoH","llamativos-","llave-","llegóE+Q","llegando o]\\I8,?","llegarWMIA>5",
"llegaríanU","llegaran 8","llegaron d","llenaSPOKA3,","llenóF","llenandoT","llenarnos 4","llenas oj[PIGFB43#","lleno maS'","llenos e\\ZXO<%-",
"lleva>:9,i","llevóKF/(","llevaba 8","llevado 8","llevanVD","llevar?:(","llevaríaI","llevarlaA","llevaron gK","llora@",
"llueva=","lluvia jS","lndvD","lo on`_^[YUTSQLJEBA>=940-'jd\\VFD1*)(gfM8iK","locaM","localizarloW","loco c","locura dM@","loggins f","logical b",
"logos onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","lograQ","logróPK","lograba 8","lograban 0","logrado kM+.","logrando kOL;8","lograron lV-*)","logroL","lokos?",
"londresTi%","lonely[","long b_BfeQP","look c","looking k","losJH>=;9842,#fa[ZXVTONGA<5'mjhb`]\\YUSRQIEB:/.(&onkd_^@10-%ligWPFDC6eL?+cK3)$7*M","lose a","losingW","louE","louisiana#",
"love kfea`ZWTPKB60/,%83\\<7E*","lovely`","lover%","loving d6#P","lrbsv9svuc8 2","ltK","ltsetg48568R","lubnaN","lucesK","lucha i(",
"luciano o","luego 1","lugar kd]MD3","lugaresM.","luis)GF=","lujo`[XNA7","lumczizrhwe=","lunaL%","lute-","luzNB=%dC",
"lw/","lycqvyrzzw0U","lz8djptsaneX","m0k83spgeb8 j","m2/","m4ozctfmh44 f","m4tjsn0qtme f","m50q19ivxnmN","m7v55glqria#","ma-",
"más mc_^[XWUTMD43/,'onkjebYQPKJIGF:71)&%$lh]SE?6520.*(g`<8fdVRL","máter\\","máximas*","máximo 3","máximosQ","méxicoN","ma1u.","módulosC","mónicaN","mañana j",
"mac 6","madre nk","madres a","madrid?","madrileña iU?","madurez@","maduroL8","maestraC","maestría kh","maestro m7%",
"maestros j7","maggieH","magia d\\[Z:9P","magicT","magistral+","magnetismo@","maitreya d","majestuosidad 7","makeK6/","mala(",
"malo)","mambo h","mameknqg1gL","mamma$","manE74$W+","mana=","manantiales 7","mandolinasW","mandos k@","manera d:",
"manhattan h","manilaF","manoOH","manoloI","manos a8","mantenerK+'","mantenerse k","mantenido)","manteniendoT","mantienen)",
"mantuvoF@","manuel'n","manzaneraZ","múltiplesK","música lkjifedb][XVRPNJFDA>;850/,+)(%og^TQI942-$m`YUSK=31.\\7*","músicoYQIB(a","músicos mK3i","maquillajeL","mar&F","maravilla 3",
"maravillas j","maravillosa'","maravillosas f7,","maravillosoA","maravillosos h","marcJ","marcóUK/*","marcada\\XL/","marcado jGC","marcando j",
"marcar*","marcas onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","mares 5","marga(","mariL'","mariachiG","marinero 5","mars 1","marta&","martín@",
"martínez@","marthaK","martin_","marvin_A90K","masasV","mascar i","masculina d","masquerade 7","massachusetts*","massielF",
"místico dC","matices 72","míticoTK93","matter+","matthew a","matthewman\\","maunick 9","maurice 3*","mayHT","mayoV(",
"mayor nlh_WL.","mayoría kP@>","mayores]KE","maysa 9","mcdonald f","me hb`][TOJEC:754$#MKDB,dcL<0/^","mecano@'L","mechanicsQ","mediados ga^F+","medicinales 9",
"medinaIC","medio_3(K","mejor jQOI=6d","mejores nOMKH3'&+","melancólica^","melancólicas j","melancólico'","melancolíaQ","melina.","melodíaI90'",
"melodías jfXB?4$#","melua>","memoriaVTI20.","menos c?","mensajeraI","menta o","menteS","mentes\\S","mentiría:","mercado d>5-NA",
"mercury<T","mercyK","mereceJ","mesN","mesaGY","mesesF6","mestizajeU?7","meteóricaP","metro 0","mezcla>",
"mezclanS","mg b","mgb736cazvs@","mgqr4 0","mh&","mhznckwbkam=","mi ldLIG=:0'&VJD(.","mia$","miénteme?","michael hgfB8",
"mick^","midnightK$","miedoH","miedos(","miembro kRM","mientras cP>","miguelG","mikeQ>","milenioW<","miles o",
"milk 0","millónY","million>","millones kYWVRLG:8.*&","mineP9E","mineápolisS","ministroK","minute f","minutosR","mio'",
"mirabaF","miraclesK","mirarK","mis h%I","miseriaK","mismaMA","mismísimaA","mismo dXM-)","mismos'","miss>",
"mississippi m","misteriosa[","misticismo d","mitad d","mitificaciónW","mito g$","mitosM","mjewkssl8ic:","mjjzyH","mk7xgm72'",
"ml5yqmmfx4cL","mmmA","mmoau\\","mmotazlnpimH","mmydosjjp5u 6","mocedadesM","modaU.","modelo]","modernaU","modernoL",
"moldeando:","momento fbP*M","momentos kfF","moments b","mondays e","moneyR","montañaN","montero@","moonW","moondance m",
"moonlighting%","morada)","moralK","more edZ8*0","morir i.","moriria&","mornin%","morrison m","mortis d","mostrarN",
"mostrarnos:","motivados 8","motownBg;K","mountainK","movementW","moverse g","moviéndoseP","movida iU?","movimiento_","moyvynkdecc/",
"mrP","ms'","msvtomkjdqs*","mtvW&","much 4*#","muchas nm`^QP'","mucho oDAg","muchos kjc[YMJ7430-%$]","muerte kh[TSK%i0*F","muestraCB90",
"muestran a4","mujer]OA/L","mujeres]","mullen k","multi m`<","multinstrumentista,","mundial]0.)","mundialesV","mundo olkd_YTNMLJI?=;:1.,)]GD","muralla'",
"murcianoH","muroR$","musa\\","musicYQfZN","musical nf]ZQONLKFEBA?2.+*'&$ihcUm@","musicales g`^OMIF<70&$","musicalmente i^I","must mT","muy njd[ZVNJF2,D","mv 6",
"myA;42,`W#aQP","mysterious k","mystery[","n9w0jvyeie8M","nacha(X","nachoXL","nació aF>#","nacida]","nacidoV","nacieron 4",
"nacimiento`;","nacionalA","nacionales&","nacionalidades-","nadaQ.","nadandoJ","nadie-V","name kd","nâºF","nâº1F",
"número a[LC<;6+)kTi","númerosB$k8.","naranjoN","nareaX","narraciónN","natalA","nativa#","nativo m","naturalIE7/:","naturales@",
"naturalezaY","naturalidad j","navajasL","navidad;","ncvjwzdqtbmG","ne6msf1ghfk h","necesariaA9","necesarioB>","necesidadI","necesitado 9",
"necesitoG&","needK","negraK7U","negro fQO","negrosP","nelsonS","nen5efe6jsg(","neoyorkino d","neoyorkinos h","neumonía(",
"never#E","neville#","new onmlkjgfedcb`^]\\[ZYXWVUTRQPONMKJIHGFEDCBA@?>=<;:987654310/.-,+*)('&%$#ih_SLa2","nfary9e9jo0&","ngultmh88 b","nhsooozymke;","ni?n","niña@","niñeraA","niño`F",
"niñosE","nicks 6","nieto?","nigelX","nigeriana\\","night ma76[B*","nightfly 2","nigor d","nikita 4","nina\\",
"nine>","ningún m","ninguna\\VG","nirj5m63oig`","nivelMB'2","njcwH","njxQ","njz8osfin7mL","nlfi)","nnpygql9piyM",
"no omhgfd[XUTQNLGFA@:843*%$#kc]\\MKIC?-)(iV7l0","noche jV","nombre onldXWUN:*#SMg","nombres onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#L","nominaciones;","nominadaO","nominado<","nooemrcws e","normal c","norman_",
"normasR","norte n>","nos hcbaSMGC1.*(eF>9%n","nosotros k(","nostalgia ke","not 0","notable a;","notablemente 6*","notables g","notas 9:",
"nothingS,%","notoriedad l","novenoM","noventa 0","nowTb^P","nqavfx3nxumB","nqxvmlve62u g","nrbjhgx2abq d","nt5rglvmf9o l","ntg50exbbtc_",
"nube o","nuestraVTQ.","nuestras nV","nuestroDQ","nuestros kWA>1","nueva khdNM@520#","nuevas 71$","nuevo idXWIEA<650*K","nuevos nmgM?$N","numbR",
"numerosas lV","numerosos kY:7*)&8$","nunca.I","nuojyuy7riy'","nutriéndose\\","nuwsf0pk3lkE","nvhncth8pdsR","nvq6vjyte:","nwi9r7xz4F","nyhmzqt8uumB",
"nynlvwxmrm8@","o24dxeqykgg 7","o41g7woeu6oE","o8W","o8la/","o9f6w6xd1wiX","oaW","oído@","oasis?","oawrdidao58>",
"obús i","obraC","obras$","obsesiva l","obstinadaK","obstructiva i","obtenidos$","obteniendo f","obtuviendo>","obtuvieron f-",
"obtuvo[","oc m","océano hI","ocasión j","ocasiones od[","oceanía]","ochenta_%","ocho>","octubre ha","ocupar@",
"oddity 1","odioso d","odstb4kp91kV","oe3qkbo5sG","oecbz6vtydg:","of bT76420$kh`\\WQ93-+aPO","of8nlfk'","oferta)","offS","oficial]",
"ofrece 9","ofrecerV","ofrecieron f","ogov9k9f17cC","ogw5dhiaeig;","ohZ[","ohje k","oidos hA@>","ojala=","ojbyk54rhtwZ",
"ojosK","oldZ","oletaO","olmkcj03fhw d","olvidarT;2","olvidarnos h","olvidarteL","olvido.","om5#","on dbaZTO:741#gWRPK<0B,",
"onâ€K","once e","oneWTO8/$k","only_e[","operaciones i","operator\\","opkjnridqxq:","optimismoX","options onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","opwudidgv1e<",
"oq5wfx2usl4 j","oqej4lt9lbm?","oqwqg1s0nq4 l","or,k%","orígenes)","orbison[","orchestra i","orden m","ordinary\\","oreja c@",
"original%","originalidadC9%","orleans#","oroVQ;","orquesta i","ortodoxoK","ortodoxos?","ory e","osS","os6ib1mdsbu 9",
"oscar eB","oscura^","oscuras[","oscuro^S","oscuros d","otisAP","otorgóK","otorgadosY","otra nF5$M","otras onjfdPl",
"otroXM(","otros onmlkjihgfedcba`_^]\\ZYXWVUTSRQPONMKJIHGFEDCB@?>=<;:987654210/.-,+)('&%$#[A3*L","otvh5cv9z1a%","outW2*","overZQ","overture b","ovwk77jrwwZ","owgg5fx7bxyL","own 6","oy9ffrzxz0o,",
"oyente/","pa;","pá?","página`^","pájaros iI","pálido[","pánico i","pérdidaF","pócima 9","póker i",
"póstumaP","póstumas[","póstumoP","pablo@","padre 0kK","pahxnwxnjm8M","painP8","pais]NA","paisleyS","palabrasC",
"palacios j","palmarés`","paloma'","palpableT","panal=","panchosD","pangeM","panorama ncUNF@?'&","panteraN","púber gK",
"públicoOI870&","públicos 80%","púrpuraS","para onlkjgba`][SMLG@=<98641(dXKJECB>5.*cWIH;)0iNA","paró 0","paradógicamenteK","paradise\\","parado m]V","paradojaM","parecía dB<(",
"parecido:","pareciendoP","pared 5","parkS","parroquiaC","partícularesZ","parte kje_YUKIFEBA6/-T*(","partesBR","participar)","particular o^[PI1,&(",
"partir k","parton*","pasó i0h","pasaba kiF","pasabanV","pasadoK5","pasando$","pasarK","pasarán`.","pasión'%d.",
"pasionesD","paso jdZN;.VM$","paternaF","paul ki\\9Q","pavarotti o","pdzcqbgcs74B","pearlsS","peces'","peculiaridades 3","pegadizas$",
"pegadizosW-","peggy\\","película cE*","películasV$","penaJF","penetrabaE","pensando;","pensarC","pepe?","pequeñaN",
"períodoW","percepción'","percusión jK","percusionista 3","perdóname.","perdedor i","perder@:7","perdidasN","perdidoRLI","perdudarán(",
"perduraZ","perdurará.","perfección m","perfeccionándose i","perfeccionarC","perfectamente\\Q","perfecto\\6*)","performing>","periodos 7(","permanecerS",
"permanecerá 1","permaneceránV","permaneció f","permanecido h","permaneciendoL","permiten$","permitió@","permitido h^","permitieron i","permitir g",
"permitirse 7","pero omkjhgedb]YXUPNGEBA;8('%$lSMK?<0*","perpetuoD","perroU","personaYKF","personajeN","personal dI7","personalesK6","personalidadV/","personas 4",
"pertenecía_P","perteneciente lRMF1/","pesadillaP","pesarXK","pese]TS,","pettigrew 0","pez 5","pflE","philZ$","philadelphia^E",
"philarmonia i","philip 3","pianistaOA4/+","pianoA/'+","pido'","piece 0","pieces 9","piel nU,","piensaD","pienso n",
"pies]","piezas h2","pilarK","pilares]","pinkR","pinochet a","pintorF","pintura i","pioneroK","pioneros^[WE-",
"pistas gR","pistoletazoP","pitifulP","pjfoqxjgbrs e","plásticasI","placerM","plagadaK4","planeta-*","planta n","plasmadosA",
"plasmar(","plastic 1","platero 5","platino<;","plays#","plaza c","plena^","plenamenteR","plenoV?9*","pmsqspmtu98A",
"pmwjk\\","poéticasI","pocas`]P","pocoXWS0g&","pocosQJ2.^","podía<7","podían 3","podemos hP:8*%","poderYH/","poderíoN",
"poderosa d","poderoso\\TK)","poderososM&","podido h","podría kZQLIA=","poesíaI4'=","poetaF(","pojt93xbsV","police a","polifacética]",
"polifacéticasG","polifacéticoJ","polpularidadL","ponerK","pop kgb_]\\ZUSONJIGB@87621/,+&%fc0(XL","popular la*","popularidad hYI86.*","popularizóFE","popularizaron$","por ca_YXSRQPONHGCBA?=73/+lgedK<521.-)#hf^I;98'&%$ki\\VFm:0(M*",
"poros(","porqueK","portal onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","portetI","poseeQ","poseedor i^E;","poseedoraO","poseedorasB(","poseer`B2","poseerlo d",
"posibilidad 0","posibleG7","positiva 3","positivismo 9","poso-","posteriores d<","posteriormenteO","powell i","powerS","ppjnku 6",
"pqynedi-","prácticamente k2-","príncipe d","precariedadK","precioJ","predilectos%","prefieroI","preludio i","premiado hE","premio md<;",
"premios mkea`WVTGA>87+*Y&","prenderse l","preparándonosC","presaA","presenta n","presentándonos n","presentó 2","presentado.","presentaraA","presley[",
"pretenda 2","pretendía<","pretenderS","pretty[","pride k","primer f[UG0-*i;","primera]R*)","primeras 9","primero+","primerosZVLF",
"primoX(","prince]B?S","principal 3","principalmente f-","principeK","principioWMK","principios cbSE","pro n5","problema?","problemas ecW8(",
"procesoI","prodigio`","prodigiosa'","producción c8ki","producciones>","produceMi","producidoX2","producirse d","productor i`PMH.$","productora]A",
"profesionalV","profundaV<","profundamenteU","profundas j?","profundidad j7","profundidadesO","profundoEP","progresivo jbRC","progresoY","prolíficasS",
"prometedor i","pronto gV","propia medM","propiedad onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","propio mkMH$","propios%","proponeJ","proporcionó hW","proporcionaban 3","protestaF",
"provecho 8","provenienteP","provocaciónV","provocador 41","proyecciónB","proyectosN","prueba,","psíquicos n","psicodelia dR3","psychiatriqueN",
"publicó 2","publicaciónP(","publicadosT","pucjagfgdpm j","pudíeramosK","pudiera g","pudieras 8","pudoK","pueblo c","puede`^I(",
"pueden d","puedoL","puerilA<","puerta j'","puertas-","puertoriqueño;","puertorriqueñoJ","pulmón(","pulmonar i","punta 5",
"punto kc[QK@*i","puntual d","punzante a","pura 3","pureza>(","purgatorioN","puristas%","puro c0","purpureS","push onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"puso nA","put<","pvsc5vdrasw j","pxif9e0465eB","pxsgocwifag 1","py5lontuw2a=","pytxtjm 6","pzxaqijiiaaY","q0nnpzt n","q0nviqoeiaw?",
"q38z'","q6ibmvzopfcN","q80I","q9rqpa@","qbgtsmyftrg%","qde5nmy7wtu/","qecaj62vvec&","qf6xu70o73c 6","qgxbbd5bve4#","qjzjhl+",
"qk a","qkyqntf11eg f","qmvgszwpqN","qrdzjj7 o","qskdxzkz/","qtxlcsvkkvy-","quéJ;hV","quédateH","que a[UHCB5&#nh^ZXTSOD><;1+%jeb_G?=4$k`\\LE2/.-,'lfc]YWQNJ976omgI@0*)iP83A:d(VFMK","quedan jeA",
"quedar d","quedara b","quedaría`J","quedarse 3","quedes]","queen$T","queenâ€™s m","quería c","querer 9","queridaF",
"querrás o","quién nMJA>","quien a]I@","quienes j","quieres cC.","quiero njdcYMC","quietest b","quilates j","quimiI","quinto k)",
"quiso i","quitóK","quizás kd'D","qwzfgxtuoro 7","qzg6kwekg 7","qzte+","r2rsp43rmg 3","r8pmsmtxy5s n","récord h.","régimenF",
"raamE","rabia j","radioZWT0U","rafael'","ragcf0sawjyL","raging%","raices j?<","rainS","rainy e","ramasI",
"ramilleteA","randb g","rango mN","raphaelV","rapidW","raspberryS","rasputin-","rítmica 3","rítmico gc","rawlsE",
"ray\\","reK%","real nf","realidad h%","realizó[","realizaciónK","realizandoV","reasons 3","rebelde c","rebosan 9",
"rebosantes j","rechazoK","recogen 3","recompensado m","recompensados 7","reconocidaN","reconocidoY","reconociese:","reconocimiento haI)&","reconocimientosTNMG:*&",
"recopiladosP","recordadas k","recordar c[M","recordaréis%","recordaremos(","recordarteN","recordsA0","recorriendo n","recreo(","recubierta f^",
"recuerdo 01","recuperarse i","red 0^","reddingAP","referencia kZR","referente i/","referimosG","refinado 2","reflejabaR","reflejaban 6",
"reflejarlo\\","reflejarse/","reflexiónK","reforzadas j","regalado b","regalaron e","reggae o?","registered onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","registradoM","registro[",
"reina]\\","reino>","reinventarse dV","reinvindicación h=","reinvindicativasI","relación n","relaciones k","relataF","relataba n","relevancia g",
"religionW","relojD","remake$","renacimiento i","renal i","renunciar 6","repentina 0","repertorioE","reportó a","representantesY",
"reproductor 2","resistir j","resistiré)","resistirse>$","respectP","respectivos onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","respetado(","respetados 1","respirarI","restoV",
"resultado\\KA","resultadosN","resurgido c","retirada 8","retiro+","retomarK","retornóN","retorno dL$","retraidos$","revoluciónUK",
"revolucionaron c","revulsivo gA?","reyYJ","rhapsodyT","rhlM","rhythmO","rica j/","ricas?","richard e","richieB",
"rick b","rico mY2X","ricosI7","ride e","ridgeley 8","riendaI","riendas g","right<^","ring-","riqueza 3(",
"ritmo okgcXSJH<6","ritmosX=;83-","river+","rivers-","rjlsiassuisK","rl 3","rnb\\OE0%","road i","robertaA","robertoYM",
"robin*","rock omigdb[WTSRLC;532/.kUNI+&jcH61f)","rockeros)","rocket 4","rodeaba(","rodeado d","rodearlos d","rodríguez j","rodriguez c","roger bTQ",
"rogersS*","rojo)","roll mk[6/+c)","rolling[?$","románticas l[","románticoKD","romantic i_L","romanticismoYD","romeo=","romero o",
"rompiendoK","ronca m","ronstadt#","room 2","rosa=j","rosasF@","rosenvingeF","rosita&","rossB","rot c",
"rotaP","rotundoNL","roxyQZ","roy[","royce]","rrbfqecpj3aS","rrvtagpuzze c","rs'","rsecdio9dh0 i","rudeza#",
"ruiz i","rumba?","rumor j","rumours 6","running f","rvtvssztu50#","rxgg9izhvakF","ry0wxgsxdeeT","ryan i","rzq1vkbqyfyE",
"s1piz1olyps<","s1wfoqxkdq8;","s3fbgocjlpiF","s3q80mk7bxe g","s7jtu$","síA.","séG","séptimoM","sólamenteP","sólas a",
"sólo h^YL=:93.)'nPC<$","sólos.","sabía j","sabe n\\V","saberA","sabido oH=$'","sabiendoQ","sabina c","saborQD0","sacar 8",
"sad 4","sade\\","sagrado g","saigon+","sailboat>","salónE/+m","salida\\MK","salido$","salir og&","salmonelosis i",
"salsa?J","salta c","salto g8&","salud(","sam dK","samba h;","símboloS","sameZ","san@(","sanaciónN",
"sanada d","sananda d","sanar 9","sangre f#","santiagoU","santos=","sanz]J","satisfyQ","saturday*","saxo_",
"saxofonista m","say`4B","sb7u5xvnE","sceneZ","school b>","scmj8F","scottA","se omlkjhgfeb`_[ZWTRQJECB=<:987620+$#^PM3*%icA?dKISN(","seña\\UGD?","sean$",
"seasons/","sebas&","secasI","sección onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","secretariaM","sectaK","seda(","sedosaE","sedosas 3","seducciónSE",
"seeE","seems 4","seguidamente(","seguido$","seguir igcVK$","segunda dR","segundo 2(","segundosF","segura@","seguro]M",
"seis 6","selloK","semanas fLi","semejante m","semillaU7","sencillas$","sencillezY","sencillo f","sencillos&","sendaK@",
"sensacionales d","sensibilidad onaI>=64(","sensible`^4#","sensibles[","sensual\\'#","sensualidad\\K-","sentadoP","sentidas 3","sentidosYXI","sentimental*(",
"sentimentalmente n'","sentimientoOK#","sentimientos^PFDB('","sentir m]I.","sentirme#","senza o","separación 2","separado c","separara b","separarmeX",
"separaron 0","september 3","septiembre.","ser gc]\\[YQE@>:/.,)h","sera;","será%","seránN","sería)","serían'","seres k",
"serie eP%","seriesA","sesenta 0","sesto.","set a","seven d6","sex 8i","sexoK8","sexualK","sexy oS)",
"shake:g","shakira]","shape a","she[`","sherpa)","shineAR0","shining 3","short_","should*","shoulderQ",
"showT","si d^JA:90'D","sido]G0-","siempre jhVU@?:93.$d1i%\\","siendo m][KI><0.'V","siente d","sientoM","sieteN@","siglo mg]YVTSKE$2","sign d",
"significa)","significó=","significar(","significara e","sigo d","sigue mI0*","siguen`2*","siguió d","silencioN","simónU",
"simbolizanD","simone\\","simpatía%","simplemente hcV","simples e","simply 0^","simplyred^","sin khdQMKI=:7-)'%\\6F","sinatra?.","sinfónico bRC",
"sing e3","singleW0","singlesP","sino)","sintetizadorZ*","sintonía%","sinuoso#","sir 4`","sister d","sitio(",
"sitiosL@","sittinP","sj$","sjmmaigigbg e","sk(","skyR","skyway 2","slaveZ","slowlyF","smooth 0\\",
"snvnvlayU","so 74","soñaban g","sobranJ","sobre ngf`[YXUGE;4k^&","sobredosisS","sobrenombre m","sobrevivir(","sobreviviréN","sobreviviremosM",
"sobrino?","social/K","sociales n","sofisticado 2","sol n","solapa f","solas a","soldadito 5","solista 632","solitario gaOKB8(#2",
"soloGC","soltura g%","sombra)","sombrasK","somebody aT*","something:^","son mlihgedba`_]\\[ZXVUSRONMLKJHGFEDCA>=<;876541/.-+(&%#oj^YWTQPIB@?9320,*)'nf:$kc","sonando@*","sonar 20","song b43",
"songs 4","sonido mkfb^ED7620,)RLH:9$","sonidos e\\ZS@95-U>3:","sonora o3*","sonorasA0(","sonoridadI","sonyN","sopaH","soplarI","sordomuda]",
"sorpredentemente*","sorprendiéndonos m","sorry 4","souY","soul g`SHE<:931#m^\\OKA;,hfdPQ70","soulmanK","soyYnV","space:1","spandau_","speak h",
"spector$","spell<","spencer\\","spice h","spirito o","squeezeQ","sr j","sr2yo>","st0ffuqk3ouY","standing 4",
"star 3","stars^","start+","started^","statonA","stayAd","stayin*","steely 2","stepA","steve_P",
"stevieK:96`","steviewonder`","still 94/k","sting oa","stivel cH","stone[$<3","stones?","stopT#P6","story_","stranger b",
"stream*","streetE","streets kf","streisand*","strongP","stuart\\","stuck,B","su jeba`YTOD=:7-lkf^XH?83.'nc_UNMJGEA@>;65/,&][WLIFCB40+%$#og\\RQ<9*VmS2d1hP(Ki","suaveG6","suaves e5",
"suavizaciónH","sube n","sucedido j","sucias)","sucumbir 8","sudafrica]","sudamericana a","sueñoW=","sueciaL","suecos$",
"sueltaI","suerte](X","suficienteL","sugerente\\-2","suicidaron d","sujetaba 0","suma 3","sumamos 9","sumarF4,)","sumarle m",
"sumergasO","sumieron 8","sumne a","sunO74","sunny-","sunrise^","sunshine`","super c<","superación(","superado h(",
"superarF","superconocida 3","superfluas>","superior'","superlópez c","superstar e.","superstition`","supertramp b","supo 7","supusoT(",
"sureñoH","sureñosI","surgían[","surgen j","surgió d2&","surgido j$","surgieron f_","surrealistasI","sus onljifeb`YXUTSQPMGEDB?>;651/.+'mkhgdc_^ZOLIHFCA932)&%]\\[WVNJ@=40,#a<:7-*RK8$(","suspender]",
"sustituir*","suz4@","swbgjzf3mb0 f","sweet/","sweetest\\","swing h","sxjialnmpnkA","sydR","t0on9tbnkd8U","t2nujwmmhkgN",
"t3w3izq5sdm f","t7bkgteqgsmY","t8S","tí n","tándemE64","técnicaO","términoW","tómameM","ta42xu2uxla-","taboo\\",
"tacones i","take b#","takes$","takin f","tal kd","talón]","talante 4","talento aSQJBA<1iP","talentosA7","tallaQ",
"también l]SQ?<10%","tambienE3","tammiK","tan gf_[OLGA<;30/i\\P.%","tango 6","tanta.","tantas(","tanto nhgdMLJC%","tú n]5.lGDCM","tapestry/",
"típica a","tarde g2","tarqueH","tatareadoM","tatuó*","título 2","taupin 4","taylorT","tcqN","tdh1iwb33k i",
"te ofYQOGF;9(&lhMJ]","tearsO","technology>","teclados j","tecnoL","tejado 5","telón>","tele j","televisión e","tell#",
"tema ni^WL7","temática k","temas he]\\[ONMLB60/'%i<8*","temperamento&","temptedQ","ten)","tenía k<","tendencias 1","tendernessP","tendido n",
"tenemos m","tener d6)","tengoJ;","tenido g","teniendoV6","tenor[3","tensiones 6","tentarD","tequila c","tercer d_&",
"terence 0d","ternura eF>(","terrellK","tesoros(","textosI","tez^","thanZ*","that 43","thatâ€™sP","the md_ZQO?>962-*$ea`^\\SA8+hTKkbPB7fWR#[4g3",
"them aR>","theme onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","thereE9g","theseP","they ae4","thing o9^E","thisZ7%","thomas a","thriller h","through_K",
"ti nX;","tiñóS","ticket e","tiempo jidRM5$I","tiempos dML6*+","tienda d","tiene fd\\QJ]C","tienen 5","tiernoD","tierraH",
"tigre i","tildandoQ","tildar^","tim h","timbre o]QG#","timeW","times#","tino i","tinte^","tintesW",
"tipoY","tirados i","titubeantesK","titulada oE","titulado dW;*&","tizaU","tkdmiyrmbik#","tkulh9otlz4'","tmvapchumpeO","to`_[ZRA<:/*gdTPKE840hfe",
"tocan^","tocandoC","tocar dA","tocarteU","toda\\YUQPMK75/*'","todas nm20:","todavía d`PF","todo oige`^WUJBA?;:82-)'&nmf[YXMGFEDC=4.khK","todos onkjihgfeca`_^]\\[ZYWVUTSRQPONKJIHGFEDCBA?>=<;:9875421/.-,)'&$#mlbXML@630*(%d+","together%",
"tok o","told mA","tom o","tomando g","tomorrow/","tonalidadQ","tone h","tono[","tontoU","tony_",
"too:*P8/","top)","topamos 9","toque omd^+","toquesI2","torrojaL","tortura]","tour#","toxasfkzzmq m","tozzi l",
"tráfico j","trágico i","trabajo 06","trabajos nmcbA6&d(","trademark onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","tradicional m6","tragedyJ*","train df","tranceC","trans 2",
"transcurría d","transcurreF","transfer h","transformaN#","transformación g","transformado g","transformaron d","transgresor 1","transmiteJF","transmiten c",
"transmitir mQ","transmitirnos;","trío*","trapecioI","tras n][XNLKFE@>21)S0","trata k","tratabaK<","través nml\\R(&#","travesI*","trayectoriaTKF4+",
"tree k","trent 0d","tres eXVRNFD","trianaICj","trickle h","trioD","tristeY","tristemente-8","tristeza<6(","triunfaJ",
"triunfarNM","triunfo]$","troncoso j","true_","trulyB","truncada(i","trust+","truthA","tryP8","tuS=(jF",
"tuktqs2zetyX","turn 7","tusG@","tutelados'","tuvieron eH","tuvo_[NK","tv%","tvf8gyhbir0/","tvnymwpdS","twilight h",
"txcdtumlqji k","u2 k","u9ba6ffgmjiK","ua onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","uaqslwjxiwcY","ucgd9dt12c0 6","udj'","udkbzka9l4s k","udwpprra6l8U","uezagfk9o8q i",
"ufupu2wuy;","uirzd0/","ujwqinpt4qiG","ulster m","umberto l","un olc_ROJHGEB</'#b`]\\[SQL?;:73-,nhe^XWTPIC9642.+*)%jgaYVM=(kNA$FDfdmK80i","una nma_[ZRIGCB<961-+&%lkgfe`^XTSA@>:50.$oi\\UQNLH843*)YPOME2/jd('FK","unía 7","unas jdNMDB","uneL",
"unfzfe8f9ni$","unicef]","unida'","unido nG>","unidos hVM","unir%","unirse)","universal nY","universales o","universalizando f",
"universidad m","universo&","uno onljhed^]YRQPMLE@531/-+*'&%f`K76","unos jeMH>3-&K","unpmoab4y8uP","upKAh","ups4ylw642s.","uptown+","uqyy4nglewu<","ur96bakqg28?",
"urangaM","uranoV","uribarriM","usR$","uunt4)","uusbx3pptxy o","uvi i","uvqyambgK","uw90wihrvzaM","uwlnpooR",
"uxvcr22rm 0","uyfm 4","uz83qy50a^","va]J>","válido o","vacio d*","vídeo onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","vajx8edq(","valíaJ","valióJ",
"valli*","valorado 7","valorar[","vamosX","vampires d","van cX@)m","vandellasK","vanguardia i","vanguardista 1","variable m",
"varias f^VNGA97+'i","varios mifWKHEB>85/","vítor n","veJ/e","veían/","veces jV>","vega?X(","veinteañeraA","velloF","venD",
"vena i^","venía f","venas fO#","vendaval e","vendedorM","venderVRL:8","vendida*","vendidasW&","vendido dLG*","vendidos kY6/.",
"venenoU","venideros g","venta_","ventas f]N)","vente?","verUPH","veránN","verano@&","verdaderamenteS","verdaderoS",
"vergelD","verleP","versátil%","versátilesG","versión'","versiones lM<7","vez nlkdTNM5,*(","vffbqdv2clcN","vió(i","viajeX4",
"vibrantes 3","vibrar=","victor n'","victoria(","vida okie\\PMJIFED;532.*)K","vidasV0","video i","videoclips:","videomúsica onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#","videomusica onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#",
"videos onmlkjihgfedcba`_^]\\[ZYXWVUTSRQONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#P","vie#","viejas d","viejo?","viejos$","vientoW","vigor 0","vigorosaT)","vii8phlo2pkN","vinilos$",
"vinoO","virtual:$","virtuosa%","virtuosoX;7%","visa=","visadoM","visión k","visionario mK","vista*","vistosidad-",
"visualizarK","vital:","vitalidadX3","viu4iwA","vivaV2)","vivas`","vive 5","vives]","vivió-","vivir iJ.",
"vivoE1-","vjk40bq8aasJ","vjrczoyxa98,","vkdqyo`","vl8nujdtlia 0","vocal ihfdQN0#O","vocales h]N@7M","vocalese h","vocalista 6&#@","vocalistasPO9-",
"voces nlkQHGDA90'&M$","volN","volóO","volcán^","volo o","voluntad]","volviendo*","volvieran 6","vos&","voz omfe_^]\\[ZYOJIGEA<;8631,&#jdK>.'VQP%",
"vpuP","vqx2xn7ti e","vrr4f2mQ","vt9t3q*","vu]","vuelo'","vuelvo c","vvy0zvqcl7e 2","vxogqn1a7beZ","vyltbsyvjbeX",
"waka]","walkerX","wallR","walter 2","wannaK","wantT8g","warwick*","water f","waterloo$","watersQ%",
"way b63","ways k","wbe1qlvygqsU","wcwhzc8s2i\\","wdnxyjkzq80 9","weWTB+%e0","weather 2","weaver*","web`^","well d",
"wembley%","were>R","wham 8","what b>2,kfK","when_E:","whenever]","where k0","wherever]","whgbwch6ipe*","whisper 8",
"white 3","whitesnake)","who d","why m4","wiiqtwuiv54J","wild m","wildcard d","willT/","wind 3","window onmlkjihgfedcba`_^]\\[ZYXWVUTSRQPNMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#O",
"winner$","wire#","wishER","wishing d","with<4k","without k","wk5wlq4pbfgR","wkqbtldfya0V","wlsbl0yuzcc]","wm7 6",
"wojzo02tmckG","woman=[O/*","won,","wonderK:9`","wonderland 3","wonders 6","wordN4","worldWB23","worry 9","would 0",
"wrong<","wsmryfsy 3","wsncS","wvsa2ceiq7uL","wvvxcwp3v8y 5","wwb779bdmy4)","www`^","wxapadhj0r8X","wxhsb7pdpbi 3","wyclef]",
"wzldhf1jpiwC","wzrxc68gnjqP","x25f3>","x6qzn9xiuoeK","x6vn3zkekf4D","xabi@","xejlohdbvee$","xers7g3N","xfrguyw1v8s$","xfudbqcplj4 1",
"xh k","xi2egyzo2pw m","xm`@","xpqqju7u5yc*","xv1dk9tshio`","xw1fxl3s7bk g","xx mgYTSE$2","xxb0nzhvj5m%","xxiV","xyW",
"xzK","xzologgfwp0=","y3ywicffoj4 6","y7dgdrp3pmsK","ya fbWC>0)('g","yc'","yd3tq5f9gfkK","yd8dcgplp-","ydd l","yeahZ",
"yearsQ","yesterday e","yfqqz6tu3fu c","ygu1bc4c4@","yn7hxmzxqv8_","ynihshyaig0 d","yo lcDAYV","yoaoQ","yopqnpbl b","york a0h",
"you mZKJ96kea_^[P>:,*#`<0gdREB/","young:1","your\\E86gd74*","yoursA","youtubeOA9onmlkjhgfecba`_^]\\[ZYXWVUTQPJIHGFDCB?>=<;8754321/.,+*)(&%$idSRNMLKE@:60-'#","yqkY","yxio6nrgva4 h","z0qw9p 4","z1k67uaa a","z7j1uogi02a 4",
"za8he50xjee d","zalssqlxxyi@","zapateroI","zbnjo88kup8 1","zencru8 e","zenitL","zf4kzl9I","zh3y9rwmtri g","zhqpm+","zhwvbirqd2s 4",
"zitrwccrqms h","zm i","znbj4ev 8","znsxeeveD","zonaJ","zone h","ztcu7mctuts^","zubiagaM","zucchero o","zxspivc2gnw o",
"zzk?");
var FN=Fs.length, WN=Ws.length, BW=window.opener;
var AR=new Array(FN), AI=new Array(FN), M2=FN>1563;
function Let(c){return c>='a'&&c<='z'||c>='0'&&c<='9'||c>'';}
function Dig(s){
 for(var i=0;i<s.length;++i){
	var c=s.charAt(i);
	if(c>='0'&&c<='9') return 0;
 }
 return 1;
}
function C(l){
 location.href=l;
}
function AW(s){
 var i,n;
 for(i=0;Let(s.charAt(i));++i);
 if(s.charAt(i)==' ') ++i;
 for(var m=1;i<s.length;){
	n=s.charCodeAt(i++)-35;
	if(n<0) n=(n+20)*92+s.charCodeAt(i++)-35;
	else if(M2) n=n*92+s.charCodeAt(i++)-35;
	AI[n]+=m++;
 }
}
function MK(s,n){
 var i;
 for(i=0;i<FN;++i) AI[i]=0;
 s=s.replace(/\*/g,'[^ ]*');
 s=s.replace(/\?/g,'[^ ]');
 s = '^'+s;
 for(i=0;i<WN;++i) if(Ws[i].search(s)==0) AW(Ws[i]);
 for(i=0;i<FN;++i) if(n) AR[i]*=AI[i]; else AR[i]=AI[i];
}
function MT(){
 var c,i,n,t="",ss="",s=document.forms[0].s.value.toLowerCase()+' ';
 for(i=0;i<FN;++i) AR[i]=M;
 for(i=n=0;i<s.length;++i){
	c=s.charAt(i);
	ss+=(c=='<')?"&lt;":c;
	if(Let(c)||c=='*'||c=='?') t+=c;
	else {
		if(t.length>L&&(D||Dig(t))) MK(t,n++);
		t="";
	}
 }
 t='La búsqueda para "<b> '+ss+'</b>".<p>\n';
 for(n=0;;++n){
	var m=0,im=-1;
	for(i=0;i<FN;++i) if(AR[i]>m) m=AR[im=i];
	if(im<0){
		if(n==0) t+="<div align=center><p><b>No hay resultados.</b></div><p>\n";
		break;
	}
	AR[im]=0;
	t+=("<b>"+(n+1)+".</b> <a href='javascript:C(\""+Fs[im].fn+"\")'>"+Fs[im].ft+"</a><br>\n"+Fs[im].fd+"<p>\n");
 }
 return t;
}
function NS(){
 if(document.getElementById) document.getElementById('txt').innerHTML=MT();
 else document.forms[0].submit();
 return false;
}
function SS(){
 if(location.search){
	var o="€,??????????????????????????????????????????????????????";
	var t="";
	for(var i=3; i<location.search.length; t+=c) {
		var c=location.search.charAt(i++);
		if(c=='+') c=' ';
		if(c=='%') {
			var v=parseInt(location.search.substring(i,i+2),16);
			if(v<128) c=String.fromCharCode(v);
			else c=o.charAt(v-128);
			i+=2;
		}
	}
	document.forms[0].s.value=t;
 }
}
//-->